Repository saeloun/miru-web, pull requests merged in 2022-12, with the labels that each got.

#805 Cypress signup specs
  app/views/devise/registrations/new.html.erb
  cypress/constants/selectors/auth.js
  cypress/e2e/auth/login.spec.js
  cypress/e2e/auth/signup.spec.js
Labels: PR: unreviewed

#815 remove test email variable
  cypress/e2e/auth/signup.spec.js
Labels: PR: reviewed-approved

#819 Fixes libffi load error in CI
  .github/workflows/validations.yml
Labels: PR: reviewed-approved

#818 Resolved issue for date and day mismatch
  app/javascript/src/components/TimeTracking/MonthCalender.tsx
  app/javascript/src/components/TimeTracking/index.tsx
Labels: PR: partially-approved

#814 download invoice, amount format and invoice dashboard amount static b…
  app/controllers/internal_api/v1/invoices_controller.rb
  app/javascript/src/components/Invoices/common/MoreOptions.tsx
  app/javascript/src/helpers/currency.ts
Labels: PR: unreviewed

#840 Upgraded the ruby version in docker to 3.1.3
  Dockerfile.local
  deployment/fly/Dockerfile.production
  deployment/fly/Dockerfile.staging
Labels: PR: reviewed-approved

#838 Fixed broken search functionality on the client’s page and project page
  app/javascript/src/common/AutoComplete.tsx
  app/javascript/src/common/AutoSearch/SearchDropdown.tsx
  app/javascript/src/common/AutoSearch/index.tsx
  app/javascript/src/components/Clients/List/Header.tsx
  app/javascript/src/components/Clients/List/SearchDataRow.tsx
  app/javascript/src/components/Projects/List/Header.tsx
  app/javascript/src/components/Projects/List/SearchDataRow.tsx
  app/javascript/src/components/Team/List/Header.tsx
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#810 Profile settings cypress specs
  app/javascript/src/components/Profile/Header.tsx
  app/javascript/src/components/Profile/UserDetail/index.tsx
  cypress/constants/routes/paths.js
  cypress/constants/selectors/profile.js
  cypress/e2e/profile/personal.spec.js
  cypress/fixtures/image.png
  cypress/fixtures/logo.png
Labels: PR: reviewed-approved

#843 Fix-failing-invoice-download-test
  cypress/e2e/invoices/invoiceDownload.spec.js
Labels: PR: reviewed-approved

#845 Fix flaky tests
  spec/requests/internal_api/v1/reports/time_entry/download_spec.rb
  spec/requests/internal_api/v1/team_members/details/update_spec.rb
Labels: PR: reviewed-approved

#834 Update elasticsearch readme
  README.md
Labels: PR: unreviewed

#856 Fixed new line items white space alignment on multiple entries modal
  app/javascript/src/components/Invoices/MultipleEntriesModal/index.tsx
Labels: PR: reviewed-approved

#802 Refactor generate invoice controller & view
  app/controllers/internal_api/v1/generate_invoice_controller.rb
  app/presenters/project_members_presenter.rb
  app/services/generate_invoice/new_line_items_service.rb
  app/views/internal_api/v1/generate_invoice/index.json.jbuilder
Labels: PR: unreviewed

#865 Removed entries from generate invoice won't be visible on the saved invoice
  app/javascript/src/mapper/generateInvoice.mapper.ts
Labels: PR: merged

#827 Mobile responsive navigation menu and invoice list page
  app/javascript/src/StyledComponents/SidePanel/index.tsx
  app/javascript/src/common/Pagination.tsx
  app/javascript/src/components/App.tsx
  app/javascript/src/components/DisplayView.tsx
  app/javascript/src/components/Invoices/InvoiceSummary/index.tsx
  app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
  app/javascript/src/components/Invoices/List/Header.tsx
  app/javascript/src/components/Invoices/List/MoreOptions.tsx
  app/javascript/src/components/Invoices/List/RecentlyUpdated/index.tsx
  app/javascript/src/components/Invoices/List/Table/TableHeader.tsx
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Invoices/List/Table/index.tsx
  app/javascript/src/components/Invoices/List/container.tsx
  app/javascript/src/components/Invoices/List/index.tsx
  app/javascript/src/components/Main.tsx
  app/javascript/src/components/Navbar/Header.tsx
  app/javascript/src/components/Navbar/Mobile/Header.tsx
  app/javascript/src/components/Navbar/Mobile/MoreOptions.tsx
  app/javascript/src/components/Navbar/Mobile/Navigation.tsx
  app/javascript/src/components/Navbar/Options.tsx
  app/javascript/src/components/Navbar/UserActions.tsx
  app/javascript/src/components/Navbar/UserInfo.tsx
  app/javascript/src/components/Navbar/index.tsx
  app/javascript/src/components/Navbar/utils.tsx
Labels: PR: reviewed-approved

#858 Sent Invoice button
  app/controllers/internal_api/v1/invoices_controller.rb
  app/javascript/src/components/Invoices/List/container.tsx
  app/javascript/src/components/Invoices/List/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceForm/SendInvoice/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceForm/SendInvoice/utils.tsx
  app/javascript/src/utils/getBadgeStatus.ts
  app/mailers/invoice_mailer.rb
  app/models/invoice.rb
  spec/models/invoice_spec.rb
Labels: PR: reviewed-approved

#862 TimesheetEntry Model Fixed Searchkick
  app/models/timesheet_entry.rb
  config/initializers/elasticsearch.rb
  config/initializers/sidekiq.rb
Labels: PR: reviewed-approved

#806 Generate invoice page updates
  app/javascript/src/components/Invoices/Generate/Container.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceLineItems.tsx
  app/javascript/src/components/Invoices/Invoice/LineItem.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/Filters/index.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/index.tsx
  app/javascript/src/components/Invoices/common/CompanyInfo/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceDetails/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceForm/Header/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceTable/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceTotal/index.tsx
  app/javascript/src/components/Invoices/common/LineItemTableHeader/index.tsx
  app/javascript/src/components/Invoices/common/ManualEntry/index.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/EditLineItems.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/NewLineItemStatic.tsx
  app/javascript/src/components/Invoices/common/NewLineItemTable/Header.tsx
  app/javascript/src/components/Invoices/common/NewLineItemTable/index.tsx
  app/javascript/src/components/Invoices/common/utils.js
Labels: PR: reviewed-approved

#821 Resolved date and day mistmatch issue
  app/javascript/src/components/TimeTracking/MonthCalender.tsx
  app/javascript/src/components/TimeTracking/index.tsx
Labels: PR: partially-approved

#825 Fixed the space between radio buttons on create client
  Gemfile.lock
  app/javascript/src/components/Clients/Modals/AddProject.tsx
  app/javascript/src/components/Projects/Modals/AddEditProject.tsx
  tailwind.config.js
Labels: PR: unreviewed

#842 Refactor team controller update action
  app/controllers/internal_api/v1/team_controller.rb
  app/policies/team_policy.rb
  app/services/team/update_service.rb
  spec/services/team/update_service_spec.rb
Labels: PR: unreviewed

#869 Fix failing invoice specs cypress
  app/javascript/src/components/Invoices/common/ManualEntry/index.tsx
  cypress/constants/selectors/invoices.js
  cypress/e2e/invoices/invoice.spec.js
  cypress/support/commands.js
Labels: PR: reviewed-approved

#870 moreoptions button removed from generate invoice page
  app/javascript/src/components/Invoices/Edit/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceForm/Header/index.tsx
Labels: PR: reviewed-approved

#844 Fixes radio button label not visible in add team member
  app/javascript/src/components/Team/modals/AddEditMember.tsx
Labels: PR: reviewed-approved

#841 Delete marked dead fns
  app/models/company.rb
  app/models/invoice.rb
  app/models/project.rb
  spec/models/company_spec.rb
  spec/models/invoice_spec.rb
  spec/models/project_spec.rb
Labels: PR: unreviewed

#881 Add Rspec Retry
  Gemfile
  Gemfile.lock
  spec/spec_helper.rb
Labels: PR: unreviewed

#878 Add Ruby 3.2 and kill Fly
  .ruby-version
  Dockerfile.local
  Dockerfile.test
  Gemfile
  Gemfile.lock
  deployment/fly/Dockerfile.production
  deployment/fly/Dockerfile.staging
  deployment/fly/fly.production.toml
  deployment/fly/fly.staging.toml
Labels: PR: unreviewed

#863 Feature/show fixed working hours on teams page
  .ruby-version
  Dockerfile.local
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/controllers/internal_api/v1/team_controller.rb
  app/javascript/src/components/Team/List/Table/TableHead.tsx
  app/javascript/src/components/Team/List/Table/TableRow.tsx
  app/javascript/src/components/Team/modals/AddEditMember.tsx
  app/javascript/src/mapper/team.mapper.ts
  app/models/company.rb
  app/models/invoice.rb
  app/models/project.rb
  app/policies/employment_policy.rb
  app/views/internal_api/v1/team/index.json.jbuilder
  deployment/fly/Dockerfile.production
  deployment/fly/Dockerfile.staging
  deployment/fly/fly.production.toml
  deployment/fly/fly.staging.toml
  package.json
  spec/models/company_spec.rb
  spec/models/invoice_spec.rb
  spec/models/project_spec.rb
  spec/requests/internal_api/v1/team/index_spec.rb
  spec/requests/internal_api/v1/team/update_spec.rb
  spec/spec_helper.rb
Labels: PR: unreviewed

#887 Updated pipeline by breaking steps
  .buildkite/pipeline.yml
  .buildkite/template.yml
  .rspec
  Gemfile
  Gemfile.lock
  app/javascript/src/components/payments/Table/index.tsx
  package.json
  scripts/ci/eslint.sh
  scripts/ci/rspec.sh
  scripts/ci/rubocop.sh
  scripts/ci/setup.sh
  yarn.lock
Labels: PR: unreviewed

#890 Refactor pipeline steps
  .buildkite/pipeline.yml
  .rspec
  scripts/ci/eslint.sh
  scripts/ci/rubocop.sh
Labels: PR: reviewed-approved

#889 remember me default checkbox selected
  app/views/devise/sessions/new.html.erb
Labels: PR: unreviewed

#848 Refactor profile update action
  app/controllers/internal_api/v1/profile_controller.rb
  app/javascript/src/apis/axios.ts
  app/javascript/src/common/Toastr.tsx
  app/services/update_profile_settings_service.rb
  config/locales/devise.en.yml
  spec/requests/internal_api/v1/profile/update_spec.rb
Labels: PR: unreviewed

#831 Refactor timesheet entry controller
  app/controllers/internal_api/v1/time_tracking_controller.rb
  app/controllers/internal_api/v1/timesheet_entry_controller.rb
  app/presenters/clients_presenter.rb
  app/services/time_tracking_index_service.rb
Labels: PR: reviewed-approved

#851 Add API to get list of user companies
  app/controllers/internal_api/v1/workspaces_controller.rb
  app/policies/workspace_policy.rb
  app/views/internal_api/v1/workspaces/index.json.jbuilder
  config/routes/internal_api.rb
  spec/requests/internal_api/v1/workspaces/index_spec.rb
Labels: PR: partially-approved

#872 Refactor time entry report view
  app/controllers/internal_api/v1/reports/time_entries_controller.rb
  app/views/internal_api/v1/reports/time_entries/index.json.jbuilder
Labels: PR: reviewed-approved
