Repository saeloun/miru-web, pull requests merged in 2022-11, with the labels that each got.

#735 Update reset email links
  app/javascript/src/components/InvoiceEmail/index.tsx
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/mailers/invoice_mailer/invoice.html.erb
Labels: PR: unreviewed

#731 Added filters on multiple new line items on model
  app/controllers/internal_api/v1/generate_invoice_controller.rb
  app/javascript/src/components/Invoices/MultipleEntriesModal/Filters/DateRange.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/Filters/SearchTeamMembers.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/Filters/index.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/Footer.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/Header.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/Table.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/index.tsx
  app/javascript/src/components/Invoices/common/utils.js
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#733 Limit projects clients access for employees
  app/controllers/internal_api/v1/time_tracking_controller.rb
  app/models/user.rb
  app/policies/time_tracking_policy.rb
  spec/requests/internal_api/v1/time_tracking/index_spec.rb
Labels: PR: reviewed-approved

#758 Fixed viewing timesheet entries of other members
  app/javascript/src/components/TimeTracking/MonthCalender.tsx
  app/javascript/src/components/TimeTracking/index.tsx
Labels: PR: reviewed-approved

#743 Set invoice status to sent only if applicable
  app/mailers/invoice_mailer.rb
Labels: PR: unreviewed

#762 Round off if the minutes sent from the api are in decimal while displaying
  app/javascript/src/helpers/hhmmParser.ts
Labels: PR: reviewed-approved

#763 Uncheck all invoices checkbox when invoices are unselected by the user
  app/javascript/src/components/Invoices/List/Table/TableHeader.tsx
  app/javascript/src/components/Invoices/List/Table/index.tsx
Labels: PR: reviewed-approved

#750 Fix: use badge components across the app
  app/javascript/src/components/Projects/Details/index.tsx
  app/javascript/src/components/Projects/List/project.tsx
  app/javascript/src/components/Reports/outstandingInvoices/Container/TableRow.tsx
  app/javascript/src/components/payments/Table/TableRow.tsx
Labels: PR: reviewed-approved

#748 Reference input added to invoice generate
  app/javascript/src/components/Invoices/Edit/index.tsx
  app/javascript/src/components/Invoices/Generate/Container.tsx
  app/javascript/src/components/Invoices/Generate/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceDetails/index.tsx
  app/models/invoice.rb
  app/views/mailers/invoice_mailer/invoice.html.erb
  db/seeds/09_invoice.rb
  spec/factories/invoices.rb
  spec/models/invoice_spec.rb
Labels: PR: partially-approved, frontend

#765 Remove faker from seed files
  db/seeds/10_addresses.rb
  db/seeds/11_devices.rb
  db/seeds/12_previous_employment.rb
Labels: enhancement, PR: unreviewed, PR: reviewed-approved, PR: partially-approved

#755 711-Added logic to only update non billed time entries
  app/controllers/application_controller.rb
  app/controllers/concerns/set_current_details.rb
  app/controllers/internal_api/v1/application_controller.rb
  app/controllers/internal_api/v1/time_tracking_controller.rb
  app/controllers/internal_api/v1/timesheet_entry_controller.rb
  app/javascript/src/components/TimeTracking/EntryCard.tsx
  app/javascript/src/components/TimeTracking/index.tsx
  app/models/current.rb
  app/models/timesheet_entry.rb
  app/policies/timesheet_entry_policy.rb
  spec/models/timesheet_entry_spec.rb
  spec/policies/timesheet_entry_policy_spec.rb
  spec/requests/internal_api/v1/timesheet_entries/index_spec.rb
Labels: PR: unreviewed

#764 Fixed UtilityFunctions::InvalidDatePassed
  lib/utility_functions.rb
Labels: PR: reviewed-approved

#759 Restrict timesheet entries to be added to only one invoice
  app/controllers/internal_api/v1/generate_invoice_controller.rb
  spec/requests/internal_api/v1/generate_invoice/index_spec.rb
Labels: bug, PR: unreviewed, PR: reviewed-approved, PR: partially-approved

#760 Invoice list page fix bugs
  app/javascript/src/components/Invoices/InvoiceSummary/index.tsx
  app/javascript/src/components/Invoices/List/RecentlyUpdated/index.tsx
  app/javascript/src/components/Invoices/List/container.tsx
  app/javascript/src/helpers/currency.ts
  app/javascript/src/helpers/index.ts
  app/javascript/stylesheets/application.scss
Labels: PR: partially-approved

#745 Invoice filter UI update
  app/javascript/src/StyledComponents/Button.tsx
  app/javascript/src/StyledComponents/SidePanel/Body.tsx
  app/javascript/src/StyledComponents/SidePanel/Footer.tsx
  app/javascript/src/StyledComponents/SidePanel/Header.tsx
  app/javascript/src/StyledComponents/SidePanel/index.tsx
  app/javascript/src/StyledComponents/index.tsx
  app/javascript/src/common/CustomCheckbox.tsx
  app/javascript/src/common/CustomRadio.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceSettings.tsx
  app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
  app/javascript/src/components/Invoices/List/Header.tsx
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Invoices/List/Table/index.tsx
  app/javascript/src/components/Invoices/List/container.tsx
  app/javascript/src/components/Invoices/List/index.tsx
  app/javascript/src/components/Invoices/common/CompanyInfo/index.tsx
  app/javascript/src/utils/getBadgeStatus.ts
  app/javascript/stylesheets/application.scss
Labels: PR: reviewed-approved

#768 Default month view on /time-tracking
  app/javascript/src/components/TimeTracking/index.tsx
Labels: enhancement, PR: unreviewed, PR: reviewed-approved, PR: partially-approved, frontend

#739 Remove default scope 'kept' from projects & clients model
  app/controllers/internal_api/v1/generate_invoice_controller.rb
  app/controllers/internal_api/v1/time_tracking_controller.rb
  app/controllers/internal_api/v1/timesheet_entry_controller.rb
  app/models/client.rb
  app/models/project.rb
  spec/models/client_spec.rb
Labels: PR: unreviewed

#771 Fix refresh invoices list after sending invoice
  app/javascript/src/components/Invoices/List/SendInvoice/index.tsx
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Invoices/List/Table/index.tsx
  app/javascript/src/components/Invoices/List/container.tsx
  app/javascript/src/components/Invoices/List/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceForm/SendInvoice/index.tsx
  app/javascript/src/components/Invoices/popups/SendInvoice/index.tsx
Labels: PR: unreviewed

#777 Fixed 0 value on first render by adding loading to clients page
  app/javascript/src/components/Clients/List/index.tsx
Labels: PR: reviewed-approved

#776 Invoice summury click actions
  app/javascript/src/components/Invoices/InvoiceSummary/index.tsx
  app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
  app/javascript/src/components/Invoices/List/RecentlyUpdated/index.tsx
  app/javascript/src/components/Invoices/List/container.tsx
Labels: PR: reviewed-approved

#761 Stripe payment webhooks
  .env.example
  Gemfile
  Gemfile.lock
  app/controllers/invoices/payments_controller.rb
  app/controllers/webhooks/stripe_controller.rb
  app/models/invoice.rb
  app/services/invoice_payment/add_payment.rb
  app/services/invoice_payment/checkout.rb
  app/services/invoice_payment/stripe_checkout_fulfillment.rb
  app/services/invoice_payment/stripe_payment_intent.rb
  config/routes.rb
  lib/stripe_checkout.rb
  spec/cassettes/InvoicePayment_StripePaymentIntent/_process/returns_the_stripe_intent_object.yml
  spec/cassettes/InvoicePayment_StripePaymentIntent/_process/won_t_return_stripe_intent_object_when_there_is_no_associated_invoice.yml
  spec/cassettes/InvoicePayment_Success/_process/updates_invoice_with_payment_intent_to_paid_status_by_confirming_payment_in_stripe.yml
  spec/cassettes/Invoices_PaymentsController/GET_success/doesn_t_mark_invoice_status_as_paid.yml
  spec/requests/invoices/payments_controller_spec.rb
  spec/services/invoice_payment/stripe_checkout_fulfillment_spec.rb
  spec/services/invoice_payment/stripe_payment_intent_spec.rb
Labels: PR: partially-approved

#773 Created TimeInput reusable styled component
  app/javascript/src/StyledComponents/TimeInput/index.tsx
  app/javascript/src/StyledComponents/TimeInput/validate.ts
  app/javascript/src/StyledComponents/index.tsx
  app/javascript/src/components/TimeTracking/AddEntry.tsx
  app/javascript/src/helpers/validateTimesheetEntry.ts
  app/models/timesheet_entry.rb
  spec/models/timesheet_entry_spec.rb
Labels: PR: reviewed-approved

#780 Single invoice download
  Gemfile.lock
  app/javascript/src/apis/invoices.ts
  app/javascript/src/components/Invoices/Edit/index.tsx
  app/javascript/src/components/Invoices/Invoice/Header.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceActions.tsx
  app/javascript/src/components/Invoices/Invoice/index.tsx
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Invoices/common/InvoiceForm/Header/index.tsx
  app/javascript/src/components/Invoices/common/MoreButton.tsx
  app/javascript/src/components/Invoices/common/MoreOptions.tsx
  app/javascript/src/components/Invoices/common/utils.js
Labels: PR: reviewed-approved, PR: partially-approved

#791 Added instructions to run elasticsearch on latest macos
  README.md
Labels: PR: unreviewed

#779 auto expandable input has been added
  app/javascript/src/components/TimeTracking/AddEntry.tsx
  package.json
  yarn.lock
Labels: PR: unreviewed

#788 Some Cleanups
  Gemfile.lock
  app/controllers/internal_api/v1/invoices_controller.rb
  app/helpers/internal_api/v1/workspaces_helper.rb
  app/helpers/workspaces_helper.rb
  app/models/client.rb
  app/models/project.rb
  app/services/date_range_service.rb
  app/services/time_entries/filters.rb
  spec/helpers/internal_api/v1/workspaces_helper_spec.rb
  spec/models/client_spec.rb
Labels: PR: unreviewed

#794 Fixed DateRange service bug
  app/services/date_range_service.rb
Labels: PR: reviewed-approved

#784 Fix: can edit non billed entries
  app/controllers/internal_api/v1/timesheet_entry_controller.rb
  spec/models/timesheet_entry_spec.rb
  spec/requests/internal_api/v1/timesheet_entries/update_spec.rb
Labels: PR: reviewed-approved

#803 Fix outstanding reports spec
  app/models/client.rb
  spec/requests/internal_api/v1/reports/outstanding_overdue_invoices/index_spec.rb
Labels: PR: reviewed-approved

#781 Accounts Aging report API
  app/controllers/internal_api/v1/reports/accounts_aging_controller.rb
  app/services/reports/accounts_aging/fetch_overdue_amount.rb
  app/views/internal_api/v1/reports/accounts_aging/index.json.jbuilder
  config/routes/internal_api.rb
  spec/requests/internal_api/v1/reports/accounts_aging/index_spec.rb
Labels: PR: partially-approved, feature

#804 Fix intent id string generation logic
  .eslint-rules/imports/enforced.js
  spec/services/invoice_payment/stripe_checkout_fulfillment_spec.rb
Labels: PR: reviewed-approved

#801 Modify time entry report
  app/controllers/internal_api/v1/reports/time_entries_controller.rb
  app/services/reports/time_entries/result.rb
  spec/requests/internal_api/v1/reports/time_entry/index_spec.rb
Labels: PR: unreviewed, backend
