Repository saeloun/miru-web, pull requests merged in 2022-10, with the labels that each got.

#693 Created CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: PR: unreviewed

#692 Trim leading zero from dates in Time Tracking
  app/javascript/src/components/time-tracking/DatesInWeek.tsx
  app/javascript/src/components/time-tracking/Index.tsx
Labels: PR: reviewed-approved, hacktoberfest-approved

#645 Multiline select, search and filter on generate invoice
  app/controllers/internal_api/v1/companies_controller.rb
  app/controllers/internal_api/v1/generate_invoice_controller.rb
  app/controllers/internal_api/v1/reports/time_entries_controller.rb
  app/javascript/src/apis/generateInvoice.ts
  app/javascript/src/components/Invoices/Edit/InvoiceTable.tsx
  app/javascript/src/components/Invoices/Edit/index.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceTable.tsx
  app/javascript/src/components/Invoices/Generate/index.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/index.tsx
  app/javascript/src/components/Invoices/api/generateInvoice.ts
  app/javascript/src/components/Invoices/common/utils.js
  app/models/project.rb
  app/models/timesheet_entry.rb
  app/policies/company_policy.rb
  app/policies/generate_invoice_policy.rb
  app/services/time_entries/filters.rb
  app/views/internal_api/v1/companies/index.json.jbuilder
  app/views/internal_api/v1/generate_invoice/index.json.jbuilder
  config/initializers/pagy.rb
  db/seeds/08_timesheet_entry.rb
  lib/utility_functions.rb
  spec/policies/generate_invoice_policy_spec.rb
  spec/requests/internal_api/v1/companies/index_spec.rb
  spec/requests/internal_api/v1/generate_invoice/index_spec.rb
  spec/requests/internal_api/v1/generate_invoice/show_spec.rb
Labels: PR: partially-approved, Do not merge

#697 Add link on sidebar brand logo to time tracking page
  app/javascript/src/components/Navbar/index.tsx
Labels: PR: reviewed-approved, hacktoberfest-approved

#646 Redirected user if 403 error received
  app/controllers/concerns/error_handler.rb
  app/javascript/src/apis/axios.ts
  app/javascript/src/components/Clients/Details/index.tsx
  app/javascript/src/components/Projects/Details/index.tsx
  config/locales/en.yml
  spec/requests/internal_api/v1/clients/create_spec.rb
  spec/requests/internal_api/v1/companies/create_spec.rb
  spec/requests/internal_api/v1/companies/update_spec.rb
  spec/requests/internal_api/v1/invitations/create_spec.rb
  spec/requests/internal_api/v1/projects/create_spec.rb
  spec/requests/internal_api/v1/projects/show_spec.rb
  spec/requests/internal_api/v1/projects/update_spec.rb
Labels: PR: partially-approved

#700 Github action validation configuration updated
  .github/workflows/validations.yml
Labels: PR: reviewed-approved, hacktoberfest-approved

#694 Update StyledComponents typography from lowerCamelCase to CamelCase
  app/javascript/src/StyledComponents/Badge.tsx
  app/javascript/src/StyledComponents/index.tsx
  app/javascript/src/components/time-tracking/EntryCard.tsx
  config/webpack/alias.js
  tsconfig.json
Labels: PR: reviewed-approved, hacktoberfest-approved

#683 Created lineitem rate calculation helper function and used it across the app
  app/javascript/src/common/ChartBar/index.tsx
  app/javascript/src/components/Clients/Details/index.tsx
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/components/InvoiceEmail/InvoiceInfo.tsx
  app/javascript/src/components/InvoiceEmail/InvoiceTotalSummary.tsx
  app/javascript/src/components/Invoices/Edit/InvoiceTable.tsx
  app/javascript/src/components/Invoices/Edit/InvoiceTotal.tsx
  app/javascript/src/components/Invoices/Edit/NewLineItemTable.tsx
  app/javascript/src/components/Invoices/Generate/ClientSelection.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceDetails.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceTable.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceTotal.tsx
  app/javascript/src/components/Invoices/Generate/ManualEntry.tsx
  app/javascript/src/components/Invoices/Generate/NewLineItemTable.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceInfo.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceTotalSummary.tsx
  app/javascript/src/components/Invoices/Invoice/LineItem.tsx
  app/javascript/src/components/Invoices/InvoiceSummary/index.tsx
  app/javascript/src/components/Invoices/List/Header.tsx
  app/javascript/src/components/Invoices/List/InvoiceSearch/SearchedDataRow.tsx
  app/javascript/src/components/Invoices/List/SendInvoice/index.tsx
  app/javascript/src/components/Invoices/List/SendInvoice/utils.ts
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/Table.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/EditLineItems.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/NewLineItemStatic.tsx
  app/javascript/src/components/Invoices/common/utils.js
  app/javascript/src/components/Invoices/popups/SendInvoice/index.tsx
  app/javascript/src/components/Invoices/popups/SendInvoice/utils.tsx
  app/javascript/src/components/Profile/BankAccountDetails/index.tsx
  app/javascript/src/components/Profile/Organization/Import/importModal.tsx
  app/javascript/src/components/Projects/Details/index.tsx
  app/javascript/src/components/Projects/List/project.tsx
  app/javascript/src/components/Reports/Container/ReportRow.tsx
  app/javascript/src/components/Reports/outstandingInvoices/Container/TableRow.tsx
  app/javascript/src/components/Reports/outstandingInvoices/Container/index.tsx
  app/javascript/src/components/Reports/revenueByClient/Container/TableRow.tsx
  app/javascript/src/components/Reports/revenueByClient/Container/index.tsx
  app/javascript/src/components/payments/Table/TableRow.tsx
  app/javascript/src/components/time-tracking/AddEntry.tsx
  app/javascript/src/components/time-tracking/DatesInWeek.tsx
  app/javascript/src/components/time-tracking/EntryCard.tsx
  app/javascript/src/components/time-tracking/Index.tsx
  app/javascript/src/components/time-tracking/MonthCalender.tsx
  app/javascript/src/components/time-tracking/WeeklyEntriesCard.tsx
  app/javascript/src/helpers/cashFormater.ts
  app/javascript/src/helpers/dateParser.ts
  app/javascript/src/helpers/debounce.ts
  app/javascript/src/helpers/hhmmParser.ts
  app/javascript/src/helpers/index.ts
  app/javascript/src/helpers/lineTotalCalc.ts
  app/javascript/src/helpers/ordinal.ts
  app/javascript/src/helpers/outsideClick.ts
  app/javascript/src/helpers/validateTimesheetEntry.ts
  app/javascript/src/mapper/editInvoice.mapper.ts
  tsconfig.json
Labels: PR: unreviewed

#688 Added SearchTimeEntries functionality
  app/javascript/src/common/SearchTimeEntries.tsx
  app/javascript/src/common/SyncAutoComplete.tsx
  app/javascript/src/components/time-tracking/Index.tsx
Labels: PR: partially-approved

#677 Common components for invoice
  app/javascript/src/components/InvoiceEmail/InvoiceDetails.tsx
  app/javascript/src/components/Invoices/CompanyInfo.tsx
  app/javascript/src/components/Invoices/Edit/InvoiceTable.tsx
  app/javascript/src/components/Invoices/Edit/index.tsx
  app/javascript/src/components/Invoices/Generate/CompanyInfo.tsx
  app/javascript/src/components/Invoices/Generate/Container.tsx
  app/javascript/src/components/Invoices/Generate/CustomComponents.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceTotal.tsx
  app/javascript/src/components/Invoices/Generate/NewLineItemTable.tsx
  app/javascript/src/components/Invoices/Generate/index.tsx
  app/javascript/src/components/Invoices/Invoice/CompanyInfo.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceDetails.tsx
  app/javascript/src/components/Invoices/common/CompanyInfo/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceDetails/ClientSelection.tsx
  app/javascript/src/components/Invoices/common/InvoiceDetails/Styles.ts
  app/javascript/src/components/Invoices/common/InvoiceDetails/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceForm/Header/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceTable/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceTotal/DiscountMenu.tsx
  app/javascript/src/components/Invoices/common/InvoiceTotal/index.tsx
  app/javascript/src/components/Invoices/common/LineItemTableHeader/index.tsx
  app/javascript/src/components/Invoices/common/ManualEntry/index.tsx
  app/javascript/src/components/Invoices/common/NewLineItemTable/index.tsx
Labels: PR: partially-approved

#701 Fix cypress specs in invoices
  app/javascript/src/components/Invoices/common/InvoiceTable/index.tsx
  app/javascript/src/components/Invoices/common/NewLineItemTable/index.tsx
  cypress/e2e/invoices/invoice.spec.js
Labels: PR: reviewed-approved

#698 temp mobile view for invoice list
  app/javascript/src/components/Invoices/InvoiceSummary/index.tsx
  app/javascript/src/components/Invoices/List/Header.tsx
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Invoices/List/Table/index.tsx
  app/javascript/src/components/Invoices/List/container.tsx
  app/javascript/src/components/Main.tsx
  app/javascript/src/components/Navbar/index.tsx
  app/javascript/stylesheets/application.scss
Labels: PR: partially-approved

#695 Autosize timesheet notes textarea only on focus to avoid incorrect height and scroll issue
  app/javascript/src/components/time-tracking/AddEntry.tsx
Labels: PR: unreviewed

#705 Revert "Autosize timesheet notes textarea only on focus to avoid incorrect height and scroll issue"
  app/javascript/src/components/time-tracking/AddEntry.tsx
Labels: PR: reviewed-approved

#595 Add API for invoice payment download for admin
  app/controllers/internal_api/v1/invoices_controller.rb
  app/policies/invoice_policy.rb
  app/services/invoice_payment/pdf_generation.rb
  config/routes/internal_api.rb
  spec/policies/invoice_policy_spec.rb
  spec/requests/internal_api/v1/invoices/download_spec.rb
Labels: PR: unreviewed

#718 Fly production deployment configuration added
  .github/workflows/fly.yml
  deployment/fly/Dockerfile.production
  deployment/fly/Dockerfile.staging
  deployment/fly/fly.production.toml
  deployment/fly/fly.staging.toml
  lib/tasks/fly.rake
Labels: PR: partially-approved

#699 Update viewed state invoices to overdue
  app/services/update_invoice_status_to_overdue_service.rb
  spec/services/update_invoice_status_to_overdue_service_spec.rb
Labels: PR: reviewed-approved

#719 Elastic search reindexing issue fixed
  app/models/timesheet_entry.rb
  lib/tasks/fly.rake
Labels: PR: unreviewed

#716 Fix organization settings page
  app/javascript/src/components/Profile/Organization/Edit/index.tsx
  app/views/internal_api/v1/companies/index.json.jbuilder
Labels: PR: reviewed-approved, hacktoberfest-approved

#717 broken UI on new invoice page fixed
  app/javascript/src/components/Invoices/Generate/InvoiceSettings.tsx
  app/javascript/src/components/Invoices/Generate/index.tsx
  app/javascript/stylesheets/application.scss
Labels: PR: partially-approved

#720 add Dockerfile and docker-compose to containerize application
  Dockerfile.local
  docker-compose.yml
Labels: PR: reviewed-approved

#680 Stripe Payment Entry
  .env.example
  Gemfile
  Gemfile.lock
  app/controllers/invoices/payments_controller.rb
  app/controllers/webhooks/stripe_controller.rb
  app/models/invoice.rb
  app/services/invoice_payment/add_payment.rb
  app/services/invoice_payment/checkout.rb
  app/services/invoice_payment/stripe_checkout_fulfillment.rb
  app/services/invoice_payment/stripe_payment_intent.rb
  config/routes.rb
  lib/stripe_checkout.rb
  spec/cassettes/InvoicePayment_StripePaymentIntent/_process/returns_the_stripe_intent_object.yml
  spec/cassettes/InvoicePayment_StripePaymentIntent/_process/won_t_return_stripe_intent_object_when_there_is_no_associated_invoice.yml
  spec/cassettes/InvoicePayment_Success/_process/updates_invoice_with_payment_intent_to_paid_status_by_confirming_payment_in_stripe.yml
  spec/cassettes/Invoices_PaymentsController/GET_success/doesn_t_mark_invoice_status_as_paid.yml
  spec/requests/invoices/payments_controller_spec.rb
  spec/services/invoice_payment/stripe_checkout_fulfillment_spec.rb
  spec/services/invoice_payment/stripe_payment_intent_spec.rb
Labels: PR: partially-approved

#726 Apply bill_status filter as "unbilled" on fetching new line items
  app/controllers/internal_api/v1/generate_invoice_controller.rb
  app/views/internal_api/v1/generate_invoice/index.json.jbuilder
  spec/requests/internal_api/v1/generate_invoice/index_spec.rb
Labels: bug, PR: unreviewed, PR: reviewed-approved, PR: partially-approved

#715 Invoice list page updated
  app/javascript/src/StyledComponents/Avatar.tsx
  app/javascript/src/StyledComponents/Tooltip.tsx
  app/javascript/src/StyledComponents/index.tsx
  app/javascript/src/common/Pagination.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceStatus.tsx
  app/javascript/src/components/Invoices/InvoiceSummary/index.tsx
  app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
  app/javascript/src/components/Invoices/List/Header.tsx
  app/javascript/src/components/Invoices/List/InvoiceSearch/SearchedDataRow.tsx
  app/javascript/src/components/Invoices/List/MoreOptions.tsx
  app/javascript/src/components/Invoices/List/RecentlyUpdated/index.tsx
  app/javascript/src/components/Invoices/List/Table/TableHeader.tsx
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Invoices/List/Table/index.tsx
  app/javascript/src/components/Invoices/List/container.tsx
  app/javascript/src/components/Reports/Filters/index.tsx
  app/javascript/src/components/Reports/outstandingInvoices/Container/TableRow.tsx
  app/javascript/src/utils/getBadgeStatus.ts
Labels: PR: partially-approved

#712 renamed time-tracking and updated imports
  app/javascript/src/components/TimeTracking/AddEntry.tsx
  app/javascript/src/components/TimeTracking/DatesInWeek.tsx
  app/javascript/src/components/TimeTracking/EntryCard.tsx
  app/javascript/src/components/TimeTracking/MonthCalender.tsx
  app/javascript/src/components/TimeTracking/SelectProject.tsx
  app/javascript/src/components/TimeTracking/WeeklyEntries.tsx
  app/javascript/src/components/TimeTracking/WeeklyEntriesCard.tsx
  app/javascript/src/components/TimeTracking/index.tsx
  app/javascript/src/constants/routes.ts
Labels: PR: unreviewed, hacktoberfest-approved

#728 fix size of current password input field on personal settings page
  app/javascript/src/components/Profile/UserDetail/index.tsx
Labels: PR: reviewed-approved

#651 Date picker edit timesheet entry
  app/javascript/src/common/CustomDatePicker/index.tsx
  app/javascript/src/components/Reports/revenueByClient/Filters/index.tsx
  app/javascript/src/components/Reports/revenueByClient/index.tsx
  app/javascript/src/components/TimeTracking/AddEntry.tsx
  app/javascript/src/components/TimeTracking/index.tsx
  config/webpack/alias.js
  tailwind.config.js
Labels: enhancement, PR: unreviewed, PR: reviewed-changes-requested, PR: partially-approved, frontend, hacktoberfest-approved

#727 Api integration recently updated invoices
  app/javascript/src/components/Invoices/List/RecentlyUpdated/index.tsx
  app/javascript/src/components/Invoices/List/container.tsx
  app/javascript/src/components/Invoices/List/index.tsx
Labels: PR: reviewed-approved, hacktoberfest-approved

#734 Fix invoice date details on edit invoice
  app/javascript/src/components/Invoices/Edit/index.tsx
Labels: PR: reviewed-approved

#741 Handled uncaught exception
  cypress.config.ts
  cypress/e2e/invoices/invoice.spec.js
  cypress/support/commands.js
  cypress/support/e2e.ts
Labels: PR: reviewed-approved

#737 Bug in the line items list when editing a line item
  app/javascript/src/components/Invoices/common/NewLineItemRow/EditLineItems.tsx
Labels: PR: reviewed-approved

#730 Added invoice status to the view invoice on mail
  app/javascript/src/components/InvoiceEmail/Header.tsx
Labels: PR: reviewed-approved, hacktoberfest-approved

#740 I#738: Add basic `Sentry` setup to Miru-Web
  .env.example
  Gemfile
  Gemfile.lock
  config/initializers/sentry.rb
Labels: PR: unreviewed, hacktoberfest-approved

#723 Remove complex queries from client.rb and project.rb
  Gemfile.lock
  app/controllers/internal_api/v1/clients_controller.rb
  app/controllers/internal_api/v1/generate_invoice_controller.rb
  app/controllers/internal_api/v1/invoices_controller.rb
  app/controllers/internal_api/v1/projects/search_controller.rb
  app/javascript/src/apis/clients.ts
  app/javascript/src/components/Invoices/Edit/index.tsx
  app/models/client.rb
  app/models/company.rb
  app/models/project.rb
  app/policies/client_policy.rb
  app/views/internal_api/v1/invoices/edit.json.jbuilder
  app/views/internal_api/v1/projects/search/index.json.jbuilder
  config/routes/internal_api.rb
  db/seeds/06_projects.rb
  spec/models/client_spec.rb
  spec/models/project_spec.rb
  spec/policies/client_policy_spec.rb
  spec/requests/internal_api/v1/clients_controller_spec.rb
  spec/requests/internal_api/v1/projects/search_spec.rb
Labels: enhancement, PR: unreviewed, PR: reviewed-changes-requested, PR: partially-approved

#747 Fixed invoice pdf attachment font family
  app/views/invoices/pdf.html.erb
Labels: PR: reviewed-approved, hacktoberfest-approved

#752 Fixed invoice pdf styles
  app/controllers/internal_api/v1/invoices_controller.rb
  app/mailers/invoice_mailer.rb
  app/services/invoice_payment/pdf_generation.rb
  app/views/invoices/pdf.html.erb
  app/views/layouts/pdf.html.erb
Labels: PR: reviewed-approved, hacktoberfest-approved

#742 Fixed authorization bug on actions
  .rubocop.yml
  app/controllers/internal_api/v1/generate_invoice_controller.rb
  app/controllers/internal_api/v1/invoices_controller.rb
  app/controllers/internal_api/v1/project_members_controller.rb
  app/controllers/internal_api/v1/projects_controller.rb
  app/controllers/internal_api/v1/team_controller.rb
  app/policies/client_policy.rb
  app/policies/generate_invoice_policy.rb
  app/policies/invoice_policy.rb
  app/policies/project_member_policy.rb
  app/policies/project_policy.rb
  app/policies/team_policy.rb
  spec/policies/client_policy_spec.rb
  spec/policies/generate_invoice_policy_spec.rb
  spec/policies/invoice_policy_spec.rb
  spec/policies/project_policy_spec.rb
  spec/policies/team_policy_spec.rb
Labels: PR: partially-approved, hacktoberfest-approved

#753 Fixed currency format on invoice pdf attchament
  app/views/invoices/pdf.html.erb
  app/views/layouts/pdf.html.erb
Labels: PR: partially-approved

#754 Fix currency style on invoice pdf
  app/views/invoices/pdf.html.erb
  app/views/layouts/pdf.html.erb
Labels: PR: reviewed-approved

#751 Revert the payments-info
  .env.example
  Gemfile
  Gemfile.lock
  app/controllers/invoices/payments_controller.rb
  app/controllers/webhooks/stripe_controller.rb
  app/models/invoice.rb
  app/services/invoice_payment/add_payment.rb
  app/services/invoice_payment/checkout.rb
  app/services/invoice_payment/stripe_checkout_fulfillment.rb
  app/services/invoice_payment/success.rb
  config/routes.rb
  lib/stripe_checkout.rb
  spec/cassettes/InvoicePayment_Success/_process/invoice_will_be_in_sent_status_even_when_checkout_session_is_not_created.yml
  spec/cassettes/InvoicePayment_Success/_process/invoice_will_be_in_sent_status_until_payment_is_complete_through_checkout_page.yml
  spec/cassettes/InvoicePayment_Success/_process/updates_invoice_as_paid_by_confirming_payment_in_stripe.yml
  spec/cassettes/InvoicePayment_Success/_process/updates_invoice_with_payment_intent_to_paid_status_by_confirming_payment_in_stripe.yml
  spec/requests/invoices/payments_controller_spec.rb
  spec/services/invoice_payment/stripe_checkout_fulfillment_spec.rb
  spec/services/invoice_payment/success_spec.rb
Labels: PR: partially-approved

#714 updated client.rb file removed unnecessary line
  app/models/client.rb
Labels: PR: unreviewed

#756 Update README links from getmiru.com to miru.so
  README.md
  app.json
Labels: PR: unreviewed

#757 Move `reply_to` email in environmental configuration
  .env.example
  app/mailers/invoice_mailer.rb
  app/mailers/send_weekly_reminder_to_user_mailer.rb
  app/mailers/user_invitation_mailer.rb
Labels: PR: unreviewed
