Repository saeloun/miru-web, pull requests merged in 2022-08, with the labels that each got.

#597 Navbar restyle
  app/assets/images/NavAvatar.svg
  app/assets/images/PurpleMiruLogoWithText.svg
  app/controllers/users/registrations_controller.rb
  app/javascript/src/components/App.tsx
  app/javascript/src/components/Main.tsx
  app/javascript/src/components/Navbar/index.tsx
  app/javascript/src/components/Profile/Layout.tsx
  app/javascript/src/components/Profile/RouteConfig.tsx
  app/javascript/src/components/Profile/UserDetail/index.tsx
  app/javascript/src/constants/index.tsx
  app/javascript/src/constants/routes.ts
  app/views/companies/show.html.erb
  app/views/layouts/application.html.erb
  app/views/partial/_navbar.html.erb
  config/routes.rb
  spec/requests/users/registrations/purge_avatar_spec.rb
  spec/requests/users/registrations/update_spec.rb
Labels: PR: partially-approved

#598 Create Previous Employments API for Admin and Owner
  app/controllers/internal_api/v1/users/previous_employments_controller.rb
  app/policies/users/previous_employment_policy.rb
  app/views/internal_api/v1/users/previous_employments/_previous_employment.json.jbuilder
  app/views/internal_api/v1/users/previous_employments/create.json.jbuilder
  app/views/internal_api/v1/users/previous_employments/index.json.jbuilder
  app/views/internal_api/v1/users/previous_employments/show.json.jbuilder
  app/views/internal_api/v1/users/previous_employments/update.json.jbuilder
  config/routes/internal_api.rb
  spec/policies/users/previous_employment_policy_spec.rb
  spec/requests/internal_api/v1/users/previous_employments/create_spec.rb
  spec/requests/internal_api/v1/users/previous_employments/index_spec.rb
  spec/requests/internal_api/v1/users/previous_employments/show_spec.rb
  spec/requests/internal_api/v1/users/previous_employments/update_spec.rb
Labels: PR: unreviewed, feature

#607 Fix failiing tests for root page
  app/javascript/src/components/Navbar/index.tsx
Labels: PR: reviewed-approved

#606 Made quantity and rate field as editable in new and edit invoice
  app/controllers/dashboard_controller.rb
  app/javascript/src/components/Invoices/common/NewLineItemRow/EditLineItems.tsx
  spec/requests/dashboards/index_spec.rb
  spec/requests/internal_api/v1/reports/outstanding_overdue_invoices/index_spec.rb
Labels: PR: unreviewed

#601 Added currency symbol to invoice details page
  app/javascript/src/components/InvoiceEmail/InvoiceDetails.tsx
  app/javascript/src/components/Invoices/Edit/InvoiceTable.tsx
  app/javascript/src/components/Invoices/Edit/InvoiceTotal.tsx
  app/javascript/src/components/Invoices/Edit/index.tsx
  app/javascript/src/components/Invoices/Generate/Container.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceTable.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceTotal.tsx
  app/javascript/src/components/Invoices/Generate/index.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceDetails.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceLineItems.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceTotalSummary.tsx
  app/javascript/src/components/Invoices/Invoice/LineItem.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/NewLineItemStatic.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/index.tsx
Labels: PR: unreviewed

#566 Fix: Unable to add member to project
  app/controllers/internal_api/v1/project_members_controller.rb
  app/javascript/src/components/Projects/Details/EditMembersList.tsx
  app/javascript/src/components/Projects/Details/EditMembersListForm.tsx
  app/javascript/src/components/Projects/Details/index.tsx
  app/javascript/src/mapper/project.mapper.ts
  app/models/project.rb
  spec/models/project_spec.rb
Labels: PR: reviewed-approved

#567 Create Devices API with Index, Create, View and Update methods
  app/controllers/internal_api/v1/users/devices_controller.rb
  app/policies/users/device_policy.rb
  app/views/internal_api/v1/users/devices/_device.json.jbuilder
  app/views/internal_api/v1/users/devices/create.json.jbuilder
  app/views/internal_api/v1/users/devices/index.json.jbuilder
  app/views/internal_api/v1/users/devices/show.json.jbuilder
  app/views/internal_api/v1/users/devices/update.json.jbuilder
  config/routes/internal_api.rb
  spec/factories/devices.rb
  spec/models/device_spec.rb
  spec/policies/users/device_policy_spec.rb
  spec/requests/internal_api/v1/users/devices/create_spec.rb
  spec/requests/internal_api/v1/users/devices/index_spec.rb
  spec/requests/internal_api/v1/users/devices/show_spec.rb
  spec/requests/internal_api/v1/users/devices/update_spec.rb
Labels: PR: partially-approved, feature, Do not merge

#609 Combine previous employments APIs for Employee and Admin
  app/controllers/internal_api/v1/previous_employments_controller.rb
  app/policies/previous_employment_policy.rb
  app/policies/users/previous_employment_policy.rb
  app/views/internal_api/v1/previous_employments/_previous_employment.json.jbuilder
  app/views/internal_api/v1/previous_employments/create.json.jbuilder
  app/views/internal_api/v1/previous_employments/index.json.jbuilder
  app/views/internal_api/v1/users/previous_employments/index.json.jbuilder
  config/routes/internal_api.rb
  spec/policies/previous_employment_policy_spec.rb
  spec/policies/users/previous_employment_policy_spec.rb
  spec/requests/internal_api/v1/previous_employments/create_spec.rb
  spec/requests/internal_api/v1/previous_employments/index_spec.rb
  spec/requests/internal_api/v1/users/previous_employments/create_spec.rb
  spec/requests/internal_api/v1/users/previous_employments/index_spec.rb
  spec/requests/internal_api/v1/users/previous_employments/show_spec.rb
  spec/requests/internal_api/v1/users/previous_employments/update_spec.rb
Labels: enhancement, PR: unreviewed, PR: reviewed-approved

#600 Delete autogenerated file and code
  cypress.config.ts
  cypress/plugins/index.js
Labels: PR: reviewed-approved

#610 Update Addresses API
  app/controllers/internal_api/v1/addresses_controller.rb
  app/policies/address_policy.rb
  app/views/internal_api/v1/addresses/create.json.jbuilder
  app/views/internal_api/v1/addresses/index.json.jbuilder
  config/routes/internal_api.rb
  spec/policies/address_policy_spec.rb
  spec/requests/internal_api/v1/addresses/create_spec.rb
  spec/requests/internal_api/v1/addresses/index_spec.rb
  spec/requests/internal_api/v1/addresses/show_spec.rb
  spec/requests/internal_api/v1/addresses/update_spec.rb
Labels: PR: reviewed-approved

#611 Fix show specs in Devices API
  spec/requests/internal_api/v1/users/devices/show_spec.rb
Labels: bug, PR: unreviewed, PR: partially-approved

#585 Revenue By Client reports filter
  app/controllers/internal_api/v1/reports/client_revenues_controller.rb
  app/javascript/src/apis/reports/clientRevenue.ts
  app/javascript/src/components/Reports/api/revenueByClient.ts
  app/javascript/src/components/Reports/revenueByClient/Container/index.tsx
  app/javascript/src/components/Reports/revenueByClient/Filters/index.tsx
  app/javascript/src/components/Reports/revenueByClient/index.tsx
  app/models/client.rb
  app/models/invitation.rb
  app/models/invoice.rb
  config/routes/internal_api.rb
  spec/requests/internal_api/v1/reports/client_revenue/index_spec.rb
Labels: enhancement, PR: unreviewed, PR: reviewed-approved, PR: partially-approved

#614 Invoice view issue fixed
  app/javascript/src/components/InvoiceEmail/InvoiceDetails.tsx
Labels: PR: partially-approved

#602 Specs for generate invoice
  app/javascript/src/common/CustomCheckbox.tsx
  app/javascript/src/components/Invoices/Edit/Header.tsx
  app/javascript/src/components/Invoices/Edit/InvoiceTable.tsx
  app/javascript/src/components/Invoices/Edit/NewLineItemTable.tsx
  app/javascript/src/components/Invoices/Generate/ClientSelection.tsx
  app/javascript/src/components/Invoices/Generate/Header.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceDetails.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceTable.tsx
  app/javascript/src/components/Invoices/Generate/NewLineItemTable.tsx
  app/javascript/src/components/Invoices/List/Header.tsx
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Invoices/List/Table/index.tsx
  app/javascript/src/components/Invoices/popups/SendInvoice/index.tsx
  cypress/constants/routes/paths.js
  cypress/constants/selectors/invoices.js
  cypress/e2e/invoices/invoice.spec.js
  cypress/fixtures/fake.js
  cypress/support/commands.js
Labels: PR: reviewed-approved

#616 Fix: Unable to add a team member with rate as 0.0
  app/javascript/src/components/Projects/Details/EditMembersListForm.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#615 Fix: User logo not appearing on team page issue fixed
  app/helpers/application_helper.rb
  spec/helpers/application_helper_spec.rb
  spec/requests/internal_api/v1/team/index_spec.rb
Labels: bug, PR: unreviewed, PR: reviewed-approved

#619 Remove profile picture from team page
  app/javascript/src/components/Team/List/Table/TableHead.tsx
  app/javascript/src/components/Team/List/Table/TableRow.tsx
Labels: PR: partially-approved

#620 Ui fixes for employee role
  app/javascript/src/components/Clients/List/Header.tsx
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/components/Profile/SubNav.tsx
  app/javascript/src/components/Projects/List/project.tsx
  app/javascript/src/components/Team/List/Header.tsx
Labels: PR: partially-approved

#623 Remove photo check condition for employees
  cypress/e2e/team/teamPageForEmployee.spec.js
Labels: PR: reviewed-approved

#622 Rename reports
  app/javascript/src/components/Reports/reportList/index.tsx
Labels: PR: reviewed-approved

#625 Reduce heroku slug size
  .slugignore
Labels: PR: unreviewed, WIP

#621 Team page ui fixes
  app/javascript/src/components/Team/List/Table/TableRow.tsx
  app/javascript/src/components/Team/modals/AddEditMember.tsx
  app/javascript/src/components/Team/modals/DeleteMember.tsx
Labels: PR: reviewed-approved

#628 Fix report names
  app/javascript/src/components/Reports/outstandingInvoices/index.tsx
  app/javascript/src/components/Reports/revenueByClient/index.tsx
  app/javascript/src/components/Reports/timeEntry/index.tsx
Labels: PR: reviewed-approved

#627 Invoice viewed status added
  app/controllers/invoices/view_controller.rb
  db/seeds/05_clients.rb
  spec/requests/invoices/view_spec.rb
Labels: PR: partially-approved

#630 Update toast error messages
  config/locales/devise.en.yml
Labels: PR: reviewed-approved

#629 Delete project on client page patch
  app/controllers/internal_api/v1/projects_controller.rb
  app/javascript/src/components/Clients/Details/index.tsx
  app/javascript/src/components/Projects/Details/index.tsx
  app/javascript/src/components/Projects/List/index.tsx
  app/javascript/src/components/Projects/Modals/DeleteProject.tsx
Labels: PR: reviewed-approved, ready-to-merge

#633 Make month time frame in uppercase
  app/javascript/src/components/Clients/Details/index.tsx
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/components/Projects/Details/index.tsx
Labels: PR: reviewed-approved

#634 Change color of paid status
  app/javascript/src/utils/getStatusTag.ts
Labels: PR: reviewed-approved
