Repository saeloun/miru-web, pull requests merged in 2022-05, with the labels that each got.

#333 Use react router for invoice page
  app/controllers/internal_api/v1/invoices_controller.rb
  app/javascript/src/apis/invoices.ts
  app/javascript/src/components/Invoices/Invoice/InvoiceTotalSummary.tsx
  app/javascript/src/components/Invoices/Invoice/index.tsx
  app/javascript/src/components/Invoices/RouteConfig.tsx
  app/views/internal_api/v1/invoices/show.json.jbuilder
  app/views/internal_api/v1/partial/_client.json.jbuilder
  app/views/internal_api/v1/partial/_company.json.jbuilder
  app/views/internal_api/v1/partial/_invoice.json.jbuilder
  app/views/internal_api/v1/partial/_invoice_line_item.json.jbuilder
  config/routes.rb
  config/routes/internal_api.rb
  spec/requests/internal_api/v1/invoices/show_spec.rb
Labels: PR: unreviewed

#355 Invoice address spacing fixed
  app/javascript/src/components/Invoices/Generate/CompanyInfo.tsx
Labels: PR: partially-approved

#357 Heroku One Click deploy added
  README.md
  app.json
Labels: PR: partially-approved

#358 Perform actions project details page
  app/javascript/src/components/Invoices/Generate/ClientSelection.tsx
  app/javascript/src/components/Projects/Details/index.tsx
  app/javascript/src/components/Projects/List/index.tsx
  app/javascript/src/components/Projects/Modals/DeleteProject.tsx
Labels: PR: unreviewed

#353 Fixes unit_amount for zero_decimal_currencies
  app/models/invoice.rb
  app/services/invoice_payment/checkout.rb
  spec/models/invoice_spec.rb
Labels: PR: partially-approved

#356 Multiline modal invoice
  .eslintrc
  app/javascript/src/components/Invoices/Generate/Container.tsx
  app/javascript/src/components/Invoices/Generate/CustomComponents.tsx
  app/javascript/src/components/Invoices/Generate/Header.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceTotal.tsx
  app/javascript/src/components/Invoices/Generate/InvoiveTable.tsx
  app/javascript/src/components/Invoices/Generate/NewLineItemRow.tsx
  app/javascript/src/components/Invoices/Generate/NewLineItemTable.tsx
  app/javascript/src/components/Invoices/Generate/index.tsx
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/FilterSelect.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/Footer.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/Header.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/Table.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/index.tsx
  app/javascript/src/components/Invoices/api/generateInvoice.ts
  app/javascript/src/components/Projects/Modals/AddEditProject.tsx
  app/javascript/src/components/Projects/Modals/DeleteProject.tsx
  app/javascript/src/components/time-tracking/WeeklyEntries.tsx
  tailwind.config.js
Labels: PR: unreviewed

#360 Eastern time default us
  app/views/companies/show.html.erb
  public/javascripts/org.js
Labels: bug, PR: unreviewed, PR: partially-approved, frontend

#365 [SECURITY]Remove stripe secret key
  .env.example
Labels: PR: reviewed-approved

#362 Help option under settings
  app/assets/images/help_icon.png
  app/views/partial/_navbar.html.erb
  config/locales/en.yml
Labels: PR: partially-approved

#366 Timesheet UI alignment
  app/javascript/src/components/time-tracking/DatesInWeek.tsx
Labels: PR: unreviewed

#346 Adds ability to generate and send InvoicePDF as an attachment.
  Gemfile
  Gemfile.lock
  app/mailers/invoice_mailer.rb
  app/models/invoice.rb
  app/services/invoice_payment/pdf_generation.rb
  app/views/invoices/pdf.html.erb
  app/views/layouts/pdf.html.erb
  config/initializers/grover.rb
  package.json
  spec/mailers/previews/invoice_preview.rb
  yarn.lock
Labels: PR: reviewed-approved

#364 Reports filter addition
  app/javascript/src/apis/axios.ts
  app/javascript/src/components/Reports/Container/TableRow.tsx
  app/javascript/src/components/Reports/Container/index.tsx
  app/javascript/src/components/Reports/Filters/index.tsx
  app/javascript/src/components/Reports/Header/index.tsx
  app/javascript/src/components/Reports/context/EntryContext.tsx
  app/javascript/src/components/Reports/index.tsx
  app/javascript/src/components/Reports/interface.ts
  app/javascript/stylesheets/application.scss
  app/views/reports/index.html.erb
  spec/requests/reports/index_spec.rb
Labels: PR: reviewed-approved

#368 Sidekiq web authentication added
  .env.example
  config/application.rb
  config/environments/development.rb
  config/routes.rb
Labels: PR: partially-approved

#361 Deleted project visible bug
  app/models/client.rb
  app/models/project.rb
  public/javascripts/org.js
  spec/models/client_spec.rb
Labels: bug, PR: unreviewed, PR: reviewed-approved, PR: reviewed-changes-requested, PR: partially-approved

#374 disable cypress tests on ci
  .github/workflows/validations.yml
Labels: PR: partially-approved

#371 Fixed filename
  app/javascript/src/common/CustomDatePicker/index.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceDetails.tsx
Labels: PR: unreviewed

#370 Created MIT License
  LICENSE
Labels: PR: reviewed-approved

#373 Auto billable checkbox
  app/javascript/src/components/time-tracking/AddEntry.tsx
  app/javascript/src/helpers/hhmm-parser.ts
Labels: bug, PR: unreviewed, PR: partially-approved, Do not merge

#372 Overdue outstanding integration
  app/javascript/src/components/Clients/Details/index.tsx
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/helpers/cashFormater.ts
  app/javascript/src/helpers/currencySymbol.ts
  app/javascript/src/mapper/client.mapper.ts
Labels: PR: partially-approved, feature

#375 Send button functionality invoice
  app/javascript/src/components/Invoices/Generate/Header.tsx
  app/javascript/src/components/Invoices/Generate/index.tsx
  app/javascript/src/components/Invoices/modals/SendInvoice/index.tsx
  app/javascript/src/components/Invoices/modals/SendInvoice/utils.ts
  app/javascript/src/mapper/generateInvoice.mapper.ts
Labels: PR: partially-approved

#363 Stripe connect integration
  app/assets/images/connected_check.svg
  app/controllers/internal_api/v1/payment_settings_controller.rb
  app/controllers/payment_settings_controller.rb
  app/javascript/src/apis/payment-settings.ts
  app/javascript/src/components/payment_settings/index.tsx
  app/models/company.rb
  app/models/stripe_connected_account.rb
  app/policies/payment_setting_policy.rb
  app/policies/payment_settings_policy.rb
  app/views/companies/show.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/internal_api/v1/payment_settings/connect_stripe.json.jbuilder
  app/views/internal_api/v1/payment_settings/index.json.jbuilder
  config/routes.rb
  config/routes/internal_api.rb
  db/migrate/20220506085404_create_stripe_connected_accounts.rb
  db/schema.rb
  spec/factories/stripe_connected_accounts.rb
  spec/models/stripe_connected_account_spec.rb
  spec/policies/payment_settings_policy_spec.rb
  spec/requests/payment_settings/index_spec.rb
Labels: PR: unreviewed, Do not merge

#378 Avatar image issue resolved
  app/assets/images/avatar_payments.svg
  app/javascript/src/components/payment_settings/SideNav.tsx
Labels: PR: partially-approved

#379 invoice edit send functionality
  app/javascript/src/components/Invoices/Invoice/BackButton.tsx
  app/javascript/src/components/Invoices/Invoice/Header.tsx
  app/javascript/src/components/Invoices/Invoice/index.tsx
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
Labels: PR: reviewed-approved

#380 [SPECS]Stripe connect controller specs
  app/controllers/concerns/error_handler.rb
  app/controllers/payment_settings_controller.rb
  app/policies/payment_settings_policy.rb
  spec/requests/internal_api/v1/payment_settings/connect_stripe_spec.rb
  spec/requests/internal_api/v1/payment_settings/index_spec.rb
  spec/requests/payment_settings/refresh_stripe_connect_spec.rb
Labels: PR: partially-approved

#349 Filter reports
  .github/workflows/validations.yml
  Gemfile
  README.md
  app/assets/images/avatar.svg
  app/controllers/internal_api/v1/reports_controller.rb
  app/models/timesheet_entry.rb
  app/services/report/filters.rb
  app/views/internal_api/v1/reports/index.json.jbuilder
  spec/requests/internal_api/v1/reports/index_spec.rb
Labels: PR: partially-approved, Do not merge

#385 toastr fix
  app/controllers/internal_api/v1/project_members_controller.rb
  app/javascript/src/apis/axios.ts
  app/javascript/src/components/Projects/Details/EditMembersList.tsx
  app/javascript/src/components/Projects/Details/EditMembersListForm.tsx
  app/javascript/src/components/Projects/Details/index.tsx
Labels: PR: reviewed-approved

#382 Toaster redesign
  app/assets/images/alert-error-close.svg
  app/assets/images/error-octagon.svg
  app/assets/images/info-circle.svg
  app/assets/images/info-close-icon.svg
  app/assets/images/success-check-circle.svg
  app/assets/images/success-close-icon.svg
  app/assets/images/warning-close-icon.svg
  app/assets/images/warning-triangle.svg
  app/javascript/src/common/Toastr.tsx
  app/javascript/src/components/Clients/Details/index.tsx
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/components/Invoices/Generate/Header.tsx
  app/javascript/src/components/Projects/List/index.tsx
  app/javascript/src/components/time-tracking/Index.tsx
  app/javascript/src/constants/index.ts
  app/javascript/src/constants/index.tsx
  app/javascript/stylesheets/application.scss
  db/schema.rb
Labels: PR: partially-approved

#387 client search enhancements
  app/javascript/src/components/Clients/List/AutoComplete.tsx
  app/javascript/src/components/Clients/List/Header.tsx
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/mapper/client.mapper.ts
  app/javascript/stylesheets/application.scss
  package.json
  yarn.lock
Labels: PR: partially-approved

#388 Add unauthenticated action for client invoice view
  app/controllers/invoices/view_controller.rb
  app/views/invoices/view/show.html.erb
  config/routes.rb
  spec/requests/invoices/view_spec.rb
Labels: PR: partially-approved

#394 Multiple decimal value issue on client list page
  Gemfile.lock
  app/javascript/src/components/Clients/List/index.tsx
Labels: PR: partially-approved

#377 Sort timeline entries
  app/javascript/src/components/Invoices/Generate/InvoiveTable.tsx
  app/javascript/src/components/Invoices/Generate/NewLineItemTable.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/index.tsx
Labels: PR: unreviewed

#391 [Perf]Benchmark elasticsearch vs active record for large number of rows
  Gemfile
  Gemfile.lock
  lib/benchmarking/benchmarker.rb
Labels: PR: reviewed-approved

#393 Add wait_until option while generating pdf via grover
  app/services/invoice_payment/pdf_generation.rb
Labels: PR: partially-approved

#395 Fix: Show entered date on the calendar on invoice page
  app/javascript/src/common/CustomDatePicker/index.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceDetails.tsx
Labels: PR: partially-approved

#399 Fix: Develop
  app/javascript/src/components/Invoices/Generate/InvoiceDetails.tsx
Labels: PR: reviewed-approved

#400 folder typo issue resolved
  app/javascript/src/components/Invoices/Generate/index.tsx
  app/javascript/src/components/Invoices/Invoice/index.tsx
  app/javascript/src/components/Invoices/List/index.tsx
  app/javascript/src/components/Invoices/popups/BulkDeleteInvoices.tsx
  app/javascript/src/components/Invoices/popups/DeleteInvoice.tsx
  app/javascript/src/components/Invoices/popups/SendInvoice/index.tsx
  app/javascript/src/components/Invoices/popups/SendInvoice/utils.tsx
Labels: PR: reviewed-approved

#345 Project filter search
  .gitignore
  app/controllers/internal_api/v1/projects_controller.rb
  app/models/company.rb
  app/views/internal_api/v1/projects/index.json.jbuilder
  db/schema.rb
  spec/models/company_spec.rb
  spec/requests/internal_api/v1/projects/index_spec.rb
Labels: PR: unreviewed

#401 Report filter enhancement
  app/javascript/src/apis/reports.ts
  app/javascript/src/components/Invoices/Generate/index.tsx
  app/javascript/src/components/Reports/Filters/filterOptions.ts
  app/javascript/src/components/Reports/Filters/index.tsx
  app/javascript/src/components/Reports/Filters/style.ts
  app/javascript/src/components/Reports/Header/NavigationFilter.tsx
  app/javascript/src/components/Reports/Header/index.tsx
  app/javascript/src/components/Reports/api/applyFilter.ts
  app/javascript/src/components/Reports/context/EntryContext.tsx
  app/javascript/src/components/Reports/index.tsx
  app/javascript/src/utils/dateUtil.ts
  app/javascript/src/utils/getStatusTag.ts
Labels: PR: partially-approved

#383 Employee dropdown
  .vscode/settings.json
  app/controllers/internal_api/v1/timesheet_entry_controller.rb
  app/controllers/time_tracking_controller.rb
  app/javascript/src/apis/timesheet-entry.ts
  app/javascript/src/components/time-tracking/AddEntry.tsx
  app/javascript/src/components/time-tracking/Index.tsx
  app/javascript/src/components/time-tracking/MonthCalender.tsx
  app/views/time_tracking/index.html.erb
  spec/requests/internal_api/v1/timesheet_entries/create_spec.rb
  spec/requests/internal_api/v1/timesheet_entries/destory_spec.rb
  spec/requests/internal_api/v1/timesheet_entries/update_spec.rb
Labels: PR: partially-approved, feature, frontend

#403 Fix timetracking on develop
  Gemfile.lock
  app/javascript/src/components/time-tracking/Index.tsx
  app/javascript/src/components/time-tracking/WeeklyEntries.tsx
  app/javascript/src/components/time-tracking/WeeklyEntriesCard.tsx
Labels: PR: partially-approved

#404 Fix failures after dependencies upgradation
  .rubocop.yml
  Gemfile.lock
  app/models/client.rb
  app/models/company.rb
  app/models/company_user.rb
  app/models/identity.rb
  app/models/invoice.rb
  app/models/invoice_line_item.rb
  app/models/project.rb
  app/models/project_member.rb
  app/models/role.rb
  app/models/stripe_connected_account.rb
  app/models/timesheet_entry.rb
  app/models/user.rb
  app/views/companies/new.html.erb
  app/views/companies/show.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  db/migrate/20220112072044_create_active_storage_tables.active_storage.rb
  db/schema.rb
Labels: PR: partially-approved

#406 Fix: Address overlapping
  app/javascript/src/components/Invoices/Invoice/CompanyInfo.tsx
Labels: PR: reviewed-approved

#408 multiline modal text wrap issue resolved
  app/javascript/src/components/Invoices/MultipleEntriesModal/Table.tsx
Labels: PR: reviewed-approved

#407 removed payment link from navbar
  app/views/partial/_navbar.html.erb
Labels: PR: partially-approved

#409 Fix: Edit invoice page layout
  app/javascript/src/components/Invoices/Edit/InvoiceTable.tsx
  app/javascript/src/components/Invoices/Edit/index.tsx
Labels: PR: reviewed-approved

#410 Fix: Logged hours not upto two decimal places
  app/javascript/src/components/Clients/Details/index.tsx
Labels: PR: partially-approved

#405 Enable direct charges on standard connnected accounts
  app/services/invoice_payment/checkout.rb
Labels: PR: partially-approved

#402 Fix invoice formatting bugs
  Gemfile
  app/services/invoice_payment/pdf_generation.rb
  app/views/invoices/pdf.html.erb
Labels: PR: partially-approved

#413 Remove i18n gem
  Gemfile
Labels: PR: reviewed-approved

#412 Readme update
  README.md
Labels: PR: unreviewed

#416 Implement delete on show invoice page
  app/javascript/src/components/Invoices/Invoice/Header.tsx
  app/javascript/src/components/Invoices/Invoice/index.tsx
  app/javascript/src/components/Invoices/popups/DeleteInvoice.tsx
Labels: PR: reviewed-approved

#415 [BugFix]Create customer for connected account instead of platform
  app/models/client.rb
  spec/models/client_spec.rb
Labels: PR: unreviewed

#417 Refactor specs
  spec/models/company_spec.rb
  spec/requests/internal_api/v1/projects/index_spec.rb
Labels: PR: partially-approved

#418 Honeybadger gem added for error reporting
  Gemfile
  Gemfile.lock
Labels: PR: partially-approved

#419 Bundle audit gem added
  .github/workflows/validations.yml
  Gemfile
  Gemfile.lock
Labels: PR: unreviewed

#420 Validate user details before inviting
  app/models/user.rb
  app/views/devise/invitations/_new.html.erb
  config/initializers/devise.rb
  db/migrate/20220527065234_remove_default_value_from_names.rb
  db/schema.rb
  spec/requests/users/invitations/create_spec.rb
Labels: PR: reviewed-approved

#414 Companies API
  Gemfile.lock
  app/controllers/internal_api/v1/companies_controller.rb
  app/helpers/companies_helper.rb
  app/javascript/src/apis/companies.ts
  app/policies/company_policy.rb
  config/routes/internal_api.rb
  spec/requests/companies/create_spec.rb
  spec/requests/company_spec.rb
  spec/requests/internal_api/v1/companies/create_spec.rb
  spec/requests/internal_api/v1/companies/index_spec.rb
  spec/requests/internal_api/v1/companies/update_spec.rb
Labels: PR: reviewed-approved, backend

#425 UI/invoice email 2
  app/assets/images/Instagram.svg
  app/assets/images/MiruWhiteLogowithText.svg
  app/assets/images/PaypalDropdown.svg
  app/assets/images/StripeDropdown.svg
  app/assets/images/Twitter.svg
  app/assets/images/miruLogoWithText.svg
  app/controllers/invoices/view_controller.rb
  app/javascript/src/components/InvoiceEmail/Header.tsx
  app/javascript/src/components/InvoiceEmail/InvoiceDetails.tsx
  app/javascript/src/components/InvoiceEmail/InvoiceInfo.tsx
  app/javascript/src/components/InvoiceEmail/InvoiceTotalSummary.tsx
  app/javascript/src/components/InvoiceEmail/PayOnlineMenu.tsx
  app/javascript/src/components/InvoiceEmail/index.tsx
  app/javascript/src/components/Invoices/Invoice/CompanyInfo.tsx
  app/mailers/invoice_mailer.rb
  app/views/invoice_mailer/invoice.html.erb
  app/views/invoices/view/show.html.erb
  app/views/layouts/mailer.html.erb
  spec/mailers/invoice_mailer_spec.rb
  spec/mailers/previews/invoice_preview.rb
  spec/requests/internal_api/v1/clients/index_spec.rb
  spec/requests/invoices/view_spec.rb
Labels: PR: partially-approved
