Repository saeloun/miru-web, pull requests merged in 2022-09, with the labels that each got.

#637 Format invoice design
  app/views/mailers/invoice_mailer/invoice.html.erb
Labels: PR: reviewed-approved

#626 Bug - Edit delete icon is not showing for a few timesheet entries
  app/assets/images/delete.svg
  app/assets/images/edit.svg
  app/javascript/src/components/Profile/UserDetail/index.tsx
  app/javascript/src/components/time-tracking/EntryCard.tsx
  app/javascript/src/components/time-tracking/WeeklyEntriesCard.tsx
  tailwind.config.js
Labels: bug, PR: unreviewed, PR: partially-approved, ready-to-merge, frontend, Testing

#618 Update weekly mailer content
  README.md
  app/mailers/send_weekly_reminder_to_user_mailer.rb
  app/views/mailers/invoice_mailer/invoice.html.erb
  app/views/mailers/invoice_mailer/invoice.text.erb
  app/views/mailers/send_weekly_reminder_to_user_mailer/notify_user_about_missed_entries.html.erb
  app/views/mailers/send_weekly_reminder_to_user_mailer/notify_user_about_missed_entries.text.erb
  app/views/mailers/user_invitation_mailer/send_user_invitation.html.erb
  config/initializers/monkey_patches/active_support/time_with_zone.rb
  config/initializers/monkey_patches/date.rb
  spec/mailers/send_weekly_reminder_to_user_mailer_spec.rb
  spec/monkey_patches/active_support/time_with_zone_spec.rb
  spec/monkey_patches/date_spec.rb
Labels: enhancement, PR: unreviewed, PR: partially-approved, backend, Testing

#638 Fix the navbar
  app/javascript/src/components/Main.tsx
  app/javascript/src/components/Navbar/index.tsx
Labels: PR: partially-approved

#639 Fix: Datepicker not working when visiting the edit invoice page
  app/javascript/src/common/CustomDatePicker/index.tsx
Labels: PR: reviewed-approved

#640 Hide unused frontend components
  app/javascript/src/components/Invoices/List/Header.tsx
  app/javascript/src/components/Invoices/List/index.tsx
  app/javascript/src/components/Navbar/index.tsx
  app/javascript/src/components/Profile/Organization/Payment/index.tsx
  app/javascript/src/components/Projects/List/Header.tsx
  app/javascript/src/components/Reports/Header/index.tsx
  app/javascript/src/components/Reports/outstandingInvoices/index.tsx
  app/javascript/src/components/Reports/revenueByClient/index.tsx
  app/javascript/src/components/Reports/timeEntry/index.tsx
  app/javascript/src/components/Reports/totalHoursLogged/index.tsx
  app/javascript/src/components/Team/List/Header.tsx
  app/javascript/src/components/payments/Header.tsx
Labels: PR: partially-approved

#642 fix phone number not showing bug
  app/controllers/internal_api/v1/clients_controller.rb
  app/javascript/src/components/Clients/Modals/EditClient.tsx
  app/javascript/src/components/Clients/Modals/NewClient.tsx
  spec/requests/internal_api/v1/clients/show_spec.rb
Labels: PR: reviewed-approved

#641 Fix: Inaccurate quantity while generating a invoice
  app/javascript/src/components/Invoices/Generate/NewLineItemTable.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/NewLineItemStatic.tsx
Labels: PR: partially-approved

#650 Fix flaky tests
  spec/requests/internal_api/v1/team_members/details/update_spec.rb
Labels: PR: partially-approved

#635 Broken-edit-project-patch
  app/javascript/src/components/Projects/Modals/AddEditProject.tsx
  app/models/client.rb
  spec/models/client_spec.rb
Labels: bug, PR: unreviewed, PR: reviewed-approved, PR: draft, PR: partially-approved, frontend

#647 Handled invoice number edit issue
  app/javascript/src/components/Invoices/Edit/index.tsx
Labels: PR: partially-approved

#648 Updated bin setup for sustainable web development
  .env.example
  bin/setup
  bin/yarn
  config/database.yml
Labels: PR: unreviewed

#653 Fixed invoice time entries hourly value along with invoice pdf
  app/javascript/src/components/Clients/Details/index.tsx
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/components/InvoiceEmail/InvoiceTotalSummary.tsx
  app/javascript/src/components/Invoices/Edit/Header.tsx
  app/javascript/src/components/Invoices/Edit/NewLineItemTable.tsx
  app/javascript/src/components/Invoices/Edit/index.tsx
  app/javascript/src/components/Invoices/Generate/ManualEntry.tsx
  app/javascript/src/components/Invoices/Generate/NewLineItemTable.tsx
  app/javascript/src/components/Invoices/Invoice/LineItem.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/Table.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/index.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/EditLineItems.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/NewLineItemStatic.tsx
  app/javascript/src/components/Invoices/common/utils.js
  app/javascript/src/components/Projects/Details/index.tsx
  app/javascript/src/mapper/editInvoice.mapper.ts
  app/models/client.rb
  app/models/project.rb
  app/services/invoice_payment/pdf_generation.rb
  spec/models/client_spec.rb
Labels: PR: reviewed-approved

#658 navbar breaking fix
  app/javascript/src/components/Main.tsx
Labels: PR: reviewed-approved

#643 Fix: Client not selected when generating invoice from project details page
  app/javascript/src/components/Invoices/Generate/ClientSelection.tsx
Labels: PR: reviewed-approved

#661 Fly deployment added
  .dockerignore
  .github/workflows/fly.yml
  Dockerfile.staging
  babel.config.js
  config/database.yml
  config/environments/production.rb
  fly.staging.toml
  lib/tasks/fly.rake
Labels: PR: reviewed-approved

#663 Fix bug datepicker on add manual entry
  app/javascript/src/components/payments/Modals/AddManualEntry.tsx
Labels: PR: partially-approved

#659 Fixed manual time entries, editing entries on invoice generation and editing pages
  app/javascript/src/components/Invoices/Generate/ManualEntry.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/EditLineItems.tsx
  app/javascript/src/helpers/hhmm-parser.ts
Labels: PR: partially-approved

#660 Fix invoices new line item entries
  app/javascript/src/components/Invoices/Edit/InvoiceTable.tsx
  app/javascript/src/components/Invoices/Edit/NewLineItemTable.tsx
  app/javascript/src/components/Invoices/Edit/index.tsx
  app/javascript/src/components/Invoices/Generate/CustomComponents.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceTable.tsx
  app/javascript/src/components/Invoices/Generate/NewLineItemTable.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/Table.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/index.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/index.tsx
  app/javascript/src/components/Invoices/common/NewLineItemTable/Header.tsx
Labels: PR: partially-approved

#665 Fix data-cy on edit invoice
  app/javascript/src/components/Invoices/Edit/NewLineItemTable.tsx
Labels: PR: reviewed-approved

#667 Puppeteer configuration added for fly
  Dockerfile.staging
Labels: PR: unreviewed

#668 Readme updated with bin/setup
  README.md
Labels: PR: reviewed-approved

#673 Fix the flaky test
  spec/requests/internal_api/v1/reports/outstanding_overdue_invoices/index_spec.rb
Labels: PR: reviewed-approved

#674 Contributors List added to readme
  README.md
Labels: PR: unreviewed

#679 Added slack invite to readme
  README.md
Labels: PR: unreviewed

#681 Change cypress base url
  package.json
Labels: PR: reviewed-approved

#654 Fixed billable error on the timesheet entries
  app/javascript/src/components/time-tracking/AddEntry.tsx
  app/javascript/src/components/time-tracking/BillTag.tsx
  app/javascript/src/components/time-tracking/EntryCard.tsx
  app/javascript/src/styledComponents/Badge.tsx
  app/javascript/src/styledComponents/index.tsx
Labels: PR: unreviewed
