Repository saeloun/miru-web, pull requests merged in 2022-07, with the labels that each got.

#538 Invoice search
  app/controllers/internal_api/v1/invoices_controller.rb
  app/javascript/src/components/Invoices/List/Header.tsx
  app/javascript/src/components/Invoices/List/InvoiceSearch/SearchDropdown.tsx
  app/javascript/src/components/Invoices/List/InvoiceSearch/SearchedDataRow.tsx
  app/javascript/src/components/Invoices/List/index.tsx
  app/javascript/src/helpers/debounce.ts
  app/models/invoice.rb
  spec/requests/internal_api/v1/invoices/index_spec.rb
Labels: PR: partially-approved

#542 Fix Project Screen edit functionality
  app/javascript/src/components/Projects/Modals/AddEditProject.tsx
Labels: PR: partially-approved

#539 Add API for outstanstding and overdue invoices report
  app/controllers/internal_api/v1/reports/outstanding_overdue_invoices_controller.rb
  app/models/client.rb
  app/views/internal_api/v1/reports/outstanding_overdue_invoices/index.json.jbuilder
  config/routes/internal_api.rb
  spec/requests/internal_api/v1/reports/client_revenue/index_spec.rb
  spec/requests/internal_api/v1/reports/outstanding_overdue_invoices/index_spec.rb
  spec/requests/internal_api/v1/reports/time_entry/download_spec.rb
  spec/requests/internal_api/v1/reports/time_entry/index_spec.rb
Labels: PR: partially-approved

#548 Time Entry Report Bug
  app/javascript/src/components/Reports/Container/TableRow.tsx
  app/javascript/src/components/Reports/Container/index.tsx
Labels: bug, PR: unreviewed, PR: partially-approved

#544 API integration clients revenue report
  app/javascript/src/apis/reports/clientRevenue.ts
  app/javascript/src/components/Reports/Header/NavigationFilter.tsx
  app/javascript/src/components/Reports/Header/fetchReport.tsx
  app/javascript/src/components/Reports/Header/index.tsx
  app/javascript/src/components/Reports/api/revenueByClient.ts
  app/javascript/src/components/Reports/context/RevenueByClientContext.tsx
  app/javascript/src/components/Reports/reportList/index.tsx
  app/javascript/src/components/Reports/revenueByClient/Container/TableRow.tsx
  app/javascript/src/components/Reports/revenueByClient/Container/index.tsx
  app/javascript/src/components/Reports/revenueByClient/index.tsx
  app/javascript/src/components/Reports/revenueByClient/interface.ts
Labels: PR: partially-approved, Priority: High

#551 owner can access new client button
  app/views/clients/index.html.erb
Labels: PR: partially-approved

#550 Bug/close add line item box on edit page
  app/javascript/src/components/Invoices/Edit/InvoiceTable.tsx
Labels: PR: partially-approved

#475 Update the cypress specs
  app/views/devise/invitations/_new.html.erb
  cypress/fixtures/fake.js
  cypress/integration/auth/login.spec.js
  cypress/integration/auth/signup.spec.js
  cypress/integration/root/rootPage.spec.js
  cypress/integration/team/teamPageForAdmin.spec.js
  cypress/integration/team/teamPageForOwner.spec.js
  cypress/support/commands.js
  cypress/support/utils/team.js
  package.json
  yarn.lock
Labels: PR: unreviewed

#490 Enable cypress tests on CI
  .github/workflows/validations.yml
Labels: PR: partially-approved, Do not merge

#545 UI/payments manual entry
  app/helpers/navigation_helper.rb
  app/javascript/src/components/payments/Header.tsx
  app/javascript/src/components/payments/Modals/AddManualEntry.tsx
  app/javascript/src/components/payments/index.tsx
Labels: PR: partially-approved

#553 toast message updated
  app/javascript/src/components/Invoices/Generate/index.tsx
Labels: PR: partially-approved

#477 Search dropdown added in time-tracking
  app/controllers/time_tracking_controller.rb
  app/javascript/src/common/SyncAutoComplete.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/index.tsx
  app/javascript/src/components/time-tracking/Index.tsx
  app/javascript/stylesheets/time-tracking.scss
  app/views/time_tracking/index.html.erb
  db/schema.rb
  tailwind.config.js
Labels: PR: reviewed-approved, frontend

#543 Create API to view & update user's personal details
  app/controllers/internal_api/v1/team_members/details_controller.rb
  app/policies/team_members/detail_policy.rb
  app/views/internal_api/v1/team_members/details/_detail.json.jbuilder
  app/views/internal_api/v1/team_members/details/show.json.jbuilder
  app/views/internal_api/v1/team_members/details/update.json.jbuilder
  config/routes/internal_api.rb
  spec/factories/users.rb
  spec/requests/internal_api/v1/team_members/details/show_spec.rb
  spec/requests/internal_api/v1/team_members/details/update_spec.rb
Labels: PR: reviewed-approved, feature

#559 CVE-2022-32224 fix
  Gemfile.lock
Labels: PR: partially-approved

#540 New invitation flow - part 3
  app/controllers/invitations/accept_controller.rb
  app/controllers/invitations_controller.rb
  app/controllers/team_controller.rb
  app/javascript/packs/team/modal.js
  app/javascript/src/components/EmailVerification/index.tsx
  app/mailers/user_invitation_mailer.rb
  app/models/employment.rb
  app/models/invitation.rb
  app/models/invoice.rb
  app/models/timesheet_entry.rb
  app/models/user.rb
  app/policies/invitation_policy.rb
  app/services/create_invited_user_service.rb
  app/views/internal_api/v1/team/index.json.jbuilder
  app/views/invitations/_form.html.erb
  app/views/invitations/edit.js.erb
  app/views/mailers/user_invitation_mailer/send_user_invitation.html.erb
  app/views/team/_form.html.erb
  app/views/team/_invitation.html.erb
  app/views/team/_team.html.erb
  app/views/team/index.html.erb
  app/views/team/new.js.erb
  app/views/users/invitations/edit.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20220701064720_add_company_and_email_unqiue_index_to_invitation.rb
  db/migrate/20220707125827_remove_company_email_unqiue_index_from_invitation.rb
  db/schema.rb
  spec/factories/invitations.rb
  spec/mailers/previews/user_invitation_preview.rb
  spec/mailers/user_invitation_mailer_spec.rb
  spec/models/invitation_spec.rb
  spec/models/user_spec.rb
  spec/requests/invitations/accept/index_spec.rb
  spec/requests/invitations/create_spec.rb
  spec/services/create_invited_user_service_spec.rb
Labels: PR: partially-approved

#563 Tailwind width patch
  app/javascript/src/components/Reports/reportList/reportCard.tsx
  tailwind.config.js
Labels: PR: partially-approved

#565 Minor UI fixes
  app/javascript/src/components/Clients/Modals/NewClient.tsx
  app/javascript/src/components/Invoices/Generate/index.tsx
  app/javascript/src/components/Profile/SubNav.tsx
  app/javascript/src/components/Projects/List/project.tsx
  app/javascript/src/components/time-tracking/BillTag.tsx
  app/javascript/src/components/time-tracking/EntryCard.tsx
Labels: PR: partially-approved

#547 Invoice status will be updated based on stripe response
  app/controllers/invoices/payments_controller.rb
  app/models/company.rb
  app/models/invoice.rb
  app/services/invoice_payment/checkout.rb
  app/services/invoice_payment/success.rb
  config/locales/en.yml
  db/migrate/20220708095031_add_payment_info_to_invoice.rb
  db/schema.rb
  spec/cassettes/InvoicePayment_Success/_process/invoice_will_be_in_sent_status_even_when_checkout_session_is_not_created.yml
  spec/cassettes/InvoicePayment_Success/_process/invoice_will_be_in_sent_status_until_payment_is_complete_through_checkout_page.yml
  spec/cassettes/InvoicePayment_Success/_process/updates_invoice_as_paid_by_confirming_payment_in_stripe.yml
  spec/cassettes/InvoicePayment_Success/_process/updates_invoice_with_payment_intent_to_paid_status_by_confirming_payment_in_stripe.yml
  spec/cassettes/Invoices_PaymentsController/GET_cancel/renders_time_tracking_page_with_status_200.yml
  spec/cassettes/Invoices_PaymentsController/GET_new/when_invoice_is_paid/redirects_user_to_success_path.yml
  spec/cassettes/Invoices_PaymentsController/GET_new/when_invoice_is_unpaid/creates_stripe_session_and_redirects_user_to_url_returned_by_session.yml
  spec/cassettes/Invoices_PaymentsController/GET_success/invoice_status_will_remain_as_sent.yml
  spec/cassettes/Invoices_PaymentsController/GET_success/marks_invoice_status_as_paid.yml
  spec/factories/clients.rb
  spec/requests/invoices/payments_controller_spec.rb
  spec/services/invoice_payment/success_spec.rb
Labels: PR: reviewed-approved

#556 Routes Cleanup
  app/controllers/clients_controller.rb
  app/controllers/home_controller.rb
  app/controllers/internal_api/v1/time_tracking_controller.rb
  app/controllers/invoices_controller.rb
  app/controllers/payments_controller.rb
  app/controllers/projects_controller.rb
  app/controllers/reports_controller.rb
  app/controllers/root_controller.rb
  app/controllers/subscriptions_controller.rb
  app/controllers/users/sessions_controller.rb
  app/helpers/application_helper.rb
  app/helpers/navigation_helper.rb
  app/javascript/src/apis/timeTracking.ts
  app/javascript/src/components/App.tsx
  app/javascript/src/components/Clients/RouteConfig.tsx
  app/javascript/src/components/Invoices/RouteConfig.tsx
  app/javascript/src/components/Main.tsx
  app/javascript/src/components/Projects/RouteConfig.tsx
  app/javascript/src/components/Reports/RouteConfig.tsx
  app/javascript/src/components/Subscriptions/RouteConfig.tsx
  app/javascript/src/components/time-tracking/Index.tsx
  app/javascript/src/constants/index.tsx
  app/javascript/src/constants/routes.ts
  app/views/clients/index.html.erb
  app/views/home/index.html.erb
  app/views/invoices/index.erb
  app/views/mailers/send_weekly_reminder_to_user_mailer/notify_user_about_missed_entries.html.erb
  app/views/mailers/send_weekly_reminder_to_user_mailer/notify_user_about_missed_entries.text.erb
  app/views/payments/index.html.erb
  app/views/projects/index.html.erb
  app/views/reports/index.html.erb
  app/views/subscriptions/index.html.erb
  app/views/time_tracking/index.html.erb
  config/routes.rb
  config/routes/internal_api.rb
  spec/requests/clients/index_spec.rb
  spec/requests/invoices_controller_spec.rb
  spec/requests/payments/index_spec.rb
  spec/requests/projects/index_spec.rb
  spec/requests/reports/index_spec.rb
  spec/requests/root/index_spec.rb
  spec/requests/subscriptions_controller_spec.rb
  spec/requests/time_tracking/index_spec.rb
  spec/requests/users/sessions/create_spec.rb
Labels: PR: unreviewed, Do not merge

#532 Project search
  .eslintrc
  app/controllers/internal_api/v1/projects/search_controller.rb
  app/controllers/internal_api/v1/timesheet_entry_controller.rb
  app/javascript/src/apis/clients.ts
  app/javascript/src/apis/projects.ts
  app/javascript/src/common/AutoComplete.tsx
  app/javascript/src/components/Clients/Details/index.tsx
  app/javascript/src/components/Clients/List/Header.tsx
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/components/Clients/Modals/DeleteClient.tsx
  app/javascript/src/components/Clients/Modals/EditClient.tsx
  app/javascript/src/components/Clients/Modals/NewClient.tsx
  app/javascript/src/components/Projects/List/Header.tsx
  app/models/project.rb
  config/routes/internal_api.rb
  db/schema.rb
  spec/models/project_spec.rb
  spec/requests/internal_api/v1/projects/search_spec.rb
Labels: PR: unreviewed, frontend

#568 New invitation flow
  Gemfile
  Gemfile.lock
  app/controllers/concerns/devise_whitelist.rb
  app/controllers/internal_api/v1/team_controller.rb
  app/controllers/invitations/accept_controller.rb
  app/controllers/invitations_controller.rb
  app/controllers/team_controller.rb
  app/controllers/users/invitations_controller.rb
  app/javascript/packs/team/modal.js
  app/javascript/src/components/EmailVerification/index.tsx
  app/mailers/user_invitation_mailer.rb
  app/models/company.rb
  app/models/employment.rb
  app/models/invitation.rb
  app/models/user.rb
  app/policies/invitation_policy.rb
  app/policies/users/invitations_policy.rb
  app/services/create_invited_user_service.rb
  app/views/devise/invitations/edit.html.erb
  app/views/devise/mailer/invitation_instructions.html.erb
  app/views/devise/mailer/invitation_instructions.text.erb
  app/views/internal_api/v1/team/index.json.jbuilder
  app/views/invitations/_form.html.erb
  app/views/invitations/edit.js.erb
  app/views/mailers/user_invitation_mailer/send_user_invitation.html.erb
  app/views/team/_form.html.erb
  app/views/team/_invitation.html.erb
  app/views/team/_team.html.erb
  app/views/team/index.html.erb
  app/views/team/new.js.erb
  config/initializers/devise.rb
  config/locales/devise_invitable.en.yml
  config/locales/en.yml
  config/routes.rb
  db/data/20220628121346_create_invitations.rb
  db/data/verifiers/invitation_verifier.rb
  db/data_schema.rb
  db/migrate/20220628121346_create_invitations.rb
  db/migrate/20220629105511_remove_devise_invitable_columns_from_users.rb
  db/migrate/20220701064720_add_company_and_email_unqiue_index_to_invitation.rb
  db/migrate/20220707125827_remove_company_email_unqiue_index_from_invitation.rb
  db/schema.rb
  db/seeds/02_users.rb
  spec/factories/invitations.rb
  spec/factories/users.rb
  spec/mailers/previews/user_invitation_preview.rb
  spec/mailers/user_invitation_mailer_spec.rb
  spec/models/invitation_spec.rb
  spec/models/user_spec.rb
  spec/policies/users/invitations_policy_spec.rb
  spec/requests/internal_api/v1/reports/outstanding_overdue_invoices/index_spec.rb
  spec/requests/internal_api/v1/team/index_spec.rb
  spec/requests/invitations/accept/index_spec.rb
  spec/requests/invitations/create_spec.rb
  spec/requests/users/invitations/create_spec.rb
  spec/services/create_invited_user_service_spec.rb
Labels: PR: unreviewed

#570 Revert "New invitation flow"
  Gemfile
  Gemfile.lock
  app/controllers/concerns/devise_whitelist.rb
  app/controllers/internal_api/v1/team_controller.rb
  app/controllers/invitations/accept_controller.rb
  app/controllers/invitations_controller.rb
  app/controllers/team_controller.rb
  app/controllers/users/invitations_controller.rb
  app/javascript/packs/team/modal.js
  app/javascript/src/components/EmailVerification/index.tsx
  app/mailers/user_invitation_mailer.rb
  app/models/company.rb
  app/models/employment.rb
  app/models/invitation.rb
  app/models/user.rb
  app/policies/invitation_policy.rb
  app/policies/users/invitations_policy.rb
  app/services/create_invited_user_service.rb
  app/views/devise/invitations/_new.html.erb
  app/views/devise/invitations/edit.html.erb
  app/views/devise/mailer/invitation_instructions.html.erb
  app/views/devise/mailer/invitation_instructions.text.erb
  app/views/internal_api/v1/team/index.json.jbuilder
  app/views/invitations/edit.js.erb
  app/views/mailers/user_invitation_mailer/send_user_invitation.html.erb
  app/views/team/_form.html.erb
  app/views/team/_invitation.html.erb
  app/views/team/_team.html.erb
  app/views/team/index.html.erb
  app/views/team/new.js.erb
  config/initializers/devise.rb
  config/locales/devise_invitable.en.yml
  config/locales/en.yml
  config/routes.rb
  db/data/20220628121346_create_invitations.rb
  db/data/verifiers/invitation_verifier.rb
  db/data_schema.rb
  db/migrate/20220628121346_create_invitations.rb
  db/migrate/20220629105511_remove_devise_invitable_columns_from_users.rb
  db/migrate/20220701064720_add_company_and_email_unqiue_index_to_invitation.rb
  db/migrate/20220707125827_remove_company_email_unqiue_index_from_invitation.rb
  db/schema.rb
  db/seeds/02_users.rb
  spec/factories/invitations.rb
  spec/factories/users.rb
  spec/mailers/previews/user_invitation_preview.rb
  spec/mailers/user_invitation_mailer_spec.rb
  spec/models/invitation_spec.rb
  spec/models/user_spec.rb
  spec/policies/users/invitations_policy_spec.rb
  spec/requests/internal_api/v1/reports/outstanding_overdue_invoices/index_spec.rb
  spec/requests/internal_api/v1/team/index_spec.rb
  spec/requests/invitations/accept/index_spec.rb
  spec/requests/invitations/create_spec.rb
  spec/requests/users/invitations/create_spec.rb
  spec/services/create_invited_user_service_spec.rb
Labels: PR: reviewed-approved

#575 Disable cypress team specs temporarily
  cypress/integration/team/teamPageForAdmin.spec.js
  cypress/integration/team/teamPageForEmployee.spec.js
  cypress/integration/team/teamPageForOwner.spec.js
Labels: PR: reviewed-approved

#571 resolved toaster closing issue on clicking close button.
  app/javascript/src/common/Toastr.tsx
Labels: PR: unreviewed, frontend

#554 Add manual payment entry
  app/controllers/internal_api/v1/payments_controller.rb
  app/models/payment.rb
  app/policies/payment_policy.rb
  app/services/invoice_payment/add_payment.rb
  app/views/internal_api/v1/payments/create.json.jbuilder
  app/views/internal_api/v1/payments/index.json.jbuilder
  config/routes/internal_api.rb
  db/migrate/20220712065450_create_payments.rb
  db/schema.rb
  spec/requests/internal_api/v1/payments/create_spec.rb
Labels: PR: partially-approved

#576 New invitation flow
  Gemfile
  Gemfile.lock
  app/controllers/concerns/devise_whitelist.rb
  app/controllers/internal_api/v1/team_controller.rb
  app/controllers/invitations/accept_controller.rb
  app/controllers/invitations_controller.rb
  app/controllers/team_controller.rb
  app/controllers/users/invitations_controller.rb
  app/javascript/packs/team/modal.js
  app/javascript/src/components/EmailVerification/index.tsx
  app/mailers/user_invitation_mailer.rb
  app/models/company.rb
  app/models/employment.rb
  app/models/invitation.rb
  app/models/user.rb
  app/policies/invitation_policy.rb
  app/policies/users/invitations_policy.rb
  app/services/create_invited_user_service.rb
  app/views/devise/invitations/edit.html.erb
  app/views/devise/mailer/invitation_instructions.html.erb
  app/views/devise/mailer/invitation_instructions.text.erb
  app/views/internal_api/v1/team/index.json.jbuilder
  app/views/invitations/_form.html.erb
  app/views/invitations/edit.js.erb
  app/views/mailers/user_invitation_mailer/send_user_invitation.html.erb
  app/views/team/_form.html.erb
  app/views/team/_invitation.html.erb
  app/views/team/_team.html.erb
  app/views/team/index.html.erb
  app/views/team/new.js.erb
  config/initializers/devise.rb
  config/locales/devise_invitable.en.yml
  config/locales/en.yml
  config/routes.rb
  db/data/20220628121346_create_invitations.rb
  db/data/verifiers/invitation_verifier.rb
  db/data_schema.rb
  db/migrate/20220628121346_create_invitations.rb
  db/migrate/20220629105511_remove_devise_invitable_columns_from_users.rb
  db/migrate/20220701064720_add_company_and_email_unqiue_index_to_invitation.rb
  db/migrate/20220707125827_remove_company_email_unqiue_index_from_invitation.rb
  db/schema.rb
  db/seeds/02_users.rb
  spec/factories/invitations.rb
  spec/factories/users.rb
  spec/mailers/previews/user_invitation_preview.rb
  spec/mailers/user_invitation_mailer_spec.rb
  spec/models/invitation_spec.rb
  spec/models/user_spec.rb
  spec/policies/users/invitations_policy_spec.rb
  spec/requests/internal_api/v1/reports/outstanding_overdue_invoices/index_spec.rb
  spec/requests/internal_api/v1/team/index_spec.rb
  spec/requests/invitations/accept/index_spec.rb
  spec/requests/invitations/create_spec.rb
  spec/requests/users/invitations/create_spec.rb
  spec/services/create_invited_user_service_spec.rb
Labels: PR: unreviewed

#579 Removed unwanted routes
  config/routes.rb
Labels: PR: reviewed-approved

#562 Invoices list for add payments
  app/controllers/internal_api/v1/payments_controller.rb
  app/policies/payment_policy.rb
  app/views/internal_api/v1/payments/new.json.jbuilder
  config/routes/internal_api.rb
  spec/requests/internal_api/v1/payments/new_spec.rb
Labels: PR: reviewed-approved

#580 Fixed the decimal issue in manual line item
  app/models/invoice_line_item.rb
  spec/models/invoice_line_item_spec.rb
  spec/requests/internal_api/v1/invoices/create_spec.rb
Labels: PR: reviewed-approved

#574 Payments list
  app/controllers/internal_api/v1/payments_controller.rb
  app/models/company.rb
  app/models/invoice.rb
  app/models/payment.rb
  app/views/internal_api/v1/payments/index.json.jbuilder
  config/routes/internal_api.rb
  db/seeds/09_invoice.rb
  db/seeds/13_payments.rb
  spec/factories/payments.rb
  spec/requests/internal_api/v1/payments/index_spec.rb
Labels: PR: unreviewed

#581 API integration for create manual entry and invoice list
  app/javascript/src/apis/payments/payments.ts
  app/javascript/src/components/payments/Modals/AddManualEntry.tsx
  app/javascript/src/components/payments/index.tsx
  app/javascript/src/mapper/interface.ts
  app/javascript/src/mapper/payment.mapper.ts
Labels: PR: partially-approved

#558 Create API for Viewing & Updating User Addresses
  app/controllers/internal_api/v1/addresses_controller.rb
  app/policies/address_policy.rb
  app/views/internal_api/v1/addresses/_address.json.jbuilder
  app/views/internal_api/v1/addresses/show.json.jbuilder
  app/views/internal_api/v1/addresses/update.json.jbuilder
  config/routes/internal_api.rb
  spec/requests/internal_api/v1/addresses/show_spec.rb
  spec/requests/internal_api/v1/addresses/update_spec.rb
Labels: PR: partially-approved, feature

#590 Consider overdue invoices while creating payment
  app/controllers/internal_api/v1/payments_controller.rb
  spec/requests/internal_api/v1/payments/new_spec.rb
Labels: PR: partially-approved

#592 Confirmation email content updated
  app/views/devise/mailer/confirmation_instructions.html.erb
Labels: PR: reviewed-approved

#593 Removed devise toaster from the sign up page
  config/locales/devise.en.yml
  spec/requests/users/registrations/create_spec.rb
Labels: PR: reviewed-approved

#569 Fixed time entry report UI bug
  app/javascript/src/components/Reports/Container/ReportRow.tsx
  app/javascript/src/components/Reports/Container/index.tsx
  app/javascript/src/components/Reports/Filters/filterOptions.ts
  app/javascript/src/components/Reports/Filters/index.tsx
  app/javascript/src/components/Reports/Header/NavigationFilter.tsx
  app/javascript/src/components/Reports/api/applyFilter.ts
  app/javascript/src/components/Reports/context/TimeEntryReportContext.tsx
  app/javascript/src/components/Reports/revenueByClient/Filters/filterOptions.ts
  app/javascript/src/components/Reports/timeEntry/index.tsx
  app/services/reports/time_entries/filters.rb
  app/services/reports/time_entries/result.rb
  lib/utility_functions.rb
Labels: PR: partially-approved

#588 Add scheduler to update invoices status to overdue
  app/jobs/update_invoice_status_to_overdue_job.rb
  app/services/update_invoice_status_to_overdue_service.rb
  config/sidekiq.yml
  spec/services/update_invoice_status_to_overdue_service_spec.rb
Labels: PR: partially-approved

#589 Fix review comments on PR-582
  app/javascript/src/components/Team/List/Table/TableRow.tsx
  app/javascript/src/components/Team/List/index.tsx
  app/models/employment.rb
  spec/requests/internal_api/v1/team/update_spec.rb
Labels: PR: unreviewed

#586 Api integration payment list
  app/javascript/src/components/payments/Modals/AddManualEntry.tsx
  app/javascript/src/components/payments/Table/TableHeader.tsx
  app/javascript/src/components/payments/Table/TableRow.tsx
  app/javascript/src/components/payments/Table/index.tsx
  app/javascript/src/components/payments/index.tsx
  app/javascript/src/utils/getStatusTag.ts
  app/services/invoice_payment/add_payment.rb
Labels: PR: reviewed-approved

#594 Prevent accepting different user invitation
  app/controllers/invitations/accept_controller.rb
  app/services/create_invited_user_service.rb
  spec/requests/invitations/accept/index_spec.rb
  spec/services/create_invited_user_service_spec.rb
Labels: PR: reviewed-approved

#572 Update-cypress-version
  .gitignore
  cypress.config.ts
  cypress.json
  cypress/config/cypress.development.json
  cypress/config/cypress.production.json
  cypress/config/cypress.staging.json
  cypress/e2e/auth/login.spec.js
  cypress/e2e/auth/signup.spec.js
  cypress/e2e/root/rootPage.spec.js
  cypress/e2e/team/teamPageForAdmin.spec.js
  cypress/e2e/team/teamPageForEmployee.spec.js
  cypress/e2e/team/teamPageForOwner.spec.js
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#596 Import csv excel tab Miru
  app/javascript/images/Step.svg
  app/javascript/images/fileIcon.svg
  app/javascript/images/xls.svg
  app/javascript/src/common/ProgressBar/index.tsx
  app/javascript/src/components/Profile/Organization/Import/Styles.ts
  app/javascript/src/components/Profile/Organization/Import/TableHeader.tsx
  app/javascript/src/components/Profile/Organization/Import/TableRow.tsx
  app/javascript/src/components/Profile/Organization/Import/importCard.tsx
  app/javascript/src/components/Profile/Organization/Import/importModal.tsx
  app/javascript/src/components/Profile/Organization/Import/index.tsx
  app/javascript/src/components/Profile/RouteConfig.tsx
  app/javascript/src/components/Profile/SubNav.tsx
  app/javascript/src/helpers/byteToSizeConverter.ts
  app/javascript/stylesheets/application.scss
  tailwind.config.js
Labels: PR: partially-approved

#564 Create API for Previous Employments with Create, View and Update methods
  app/controllers/internal_api/v1/previous_employments_controller.rb
  app/models/timesheet_entry.rb
  app/policies/application_policy.rb
  app/policies/previous_employment_policy.rb
  app/views/internal_api/v1/previous_employments/_previous_employment.json.jbuilder
  app/views/internal_api/v1/previous_employments/create.json.jbuilder
  app/views/internal_api/v1/previous_employments/show.json.jbuilder
  app/views/internal_api/v1/previous_employments/update.json.jbuilder
  config/routes/internal_api.rb
  spec/models/previous_employment_spec.rb
  spec/policies/previous_employment_policy_spec.rb
  spec/requests/internal_api/v1/previous_employments/create_spec.rb
  spec/requests/internal_api/v1/previous_employments/show_spec.rb
  spec/requests/internal_api/v1/previous_employments/update_spec.rb
Labels: PR: partially-approved, feature
