Repository saeloun/miru-web, pull requests merged in 2022-06, with the labels that each got.

#421 Rails toast redesign
  app/javascript/packs/application.js
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/toast.scss
Labels: PR: partially-approved

#431 Fix reports test failing due to date range on month change
  spec/requests/internal_api/v1/reports/index_spec.rb
Labels: PR: partially-approved

#428 Purge Companies Logo API
  app/controllers/internal_api/v1/companies/purge_logo_controller.rb
  app/javascript/src/apis/companies.ts
  app/policies/company_policy.rb
  config/locales/en.yml
  config/routes/internal_api.rb
  spec/requests/internal_api/v1/companies/purge_logo/destroy_spec.rb
Labels: PR: unreviewed, backend

#396 Enable stripe connect in invoice settings
  app/controllers/internal_api/v1/payment_settings_controller.rb
  app/controllers/internal_api/v1/payments/providers_controller.rb
  app/javascript/src/apis/payments/providers.ts
  app/javascript/src/common/CustomToggle.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceSettings.tsx
  app/javascript/src/components/Invoices/Generate/Invoice_settings.tsx
  app/javascript/src/components/Invoices/Generate/index.tsx
  app/models/company.rb
  app/models/payments_provider.rb
  app/policies/payments/provider_policy.rb
  app/views/internal_api/v1/payments/providers/create.json.jbuilder
  app/views/internal_api/v1/payments/providers/index.json.jbuilder
  app/views/internal_api/v1/payments/providers/update.json.jbuilder
  config/routes/internal_api.rb
  db/migrate/20220525091818_create_payments_providers.rb
  db/schema.rb
  spec/factories/payments_providers.rb
  spec/models/payments_provider_spec.rb
  spec/requests/internal_api/v1/payments/providers/create_spec.rb
  spec/requests/internal_api/v1/payments/providers/index_spec.rb
  spec/requests/internal_api/v1/payments/providers/update_spec.rb
Labels: PR: reviewed-approved

#437 Remove payment options list from view invoice page
  app/javascript/src/components/InvoiceEmail/Header.tsx
Labels: PR: partially-approved

#439 Bug/redirect to invoice list page
  app/javascript/src/components/Invoices/popups/SendInvoice/index.tsx
Labels: PR: partially-approved

#441 [BE]Remove payments provider creation route
  app/controllers/internal_api/v1/payments/providers_controller.rb
  config/routes/internal_api.rb
  spec/requests/internal_api/v1/payments/providers/create_spec.rb
Labels: PR: partially-approved

#436 project add edit fix
  app/javascript/src/components/Projects/List/project.tsx
  app/javascript/src/components/Projects/Modals/AddEditProject.tsx
  app/javascript/src/components/Projects/interface.ts
Labels: PR: reviewed-approved

#438 flipkart, microsoft client seed added
  config/database.yml
  db/seeds/05_clients.rb
  db/seeds/06_projects.rb
  db/seeds/07_project_member.rb
  db/seeds/08_timesheet_entry.rb
  db/seeds/09_invoice.rb
Labels: PR: reviewed-approved

#429 Group reports
  app/controllers/internal_api/v1/reports_controller.rb
  app/models/timesheet_entry.rb
  app/services/report/filters.rb
  app/services/report/group_by.rb
  app/services/report/result.rb
  app/views/internal_api/v1/reports/index.json.jbuilder
  spec/factories/timesheet_entries.rb
  spec/requests/internal_api/v1/clients/index_spec.rb
  spec/requests/internal_api/v1/reports/index_spec.rb
  spec/services/reports/group_by_spec.rb
Labels: PR: partially-approved

#449 Invoice email design fixes
  app/mailers/invoice_mailer.rb
  app/views/invoice_mailer/invoice.html.erb
  public/Instagram.svg
  public/Twitter.svg
  public/miruLogoWithText.svg
Labels: PR: unreviewed

#444 Group filters UI
  app/javascript/src/components/Reports/Container/TableRow.tsx
  app/javascript/src/components/Reports/Container/index.tsx
  app/javascript/src/components/Reports/Filters/filterOptions.ts
  app/javascript/src/components/Reports/Filters/index.tsx
  app/javascript/src/components/Reports/Header/NavigationFilter.tsx
  app/javascript/src/components/Reports/api/applyFilter.ts
  app/javascript/src/components/Reports/context/EntryContext.tsx
  app/javascript/src/components/Reports/index.tsx
  app/javascript/src/mapper/report.mapper.ts
Labels: PR: unreviewed

#450 Filtered entries using timeframe
  app/javascript/src/apis/projects.ts
  app/javascript/src/components/Projects/Details/index.tsx
  app/models/project.rb
Labels: PR: reviewed-approved

#451 Fix Invoice Date Format and icon
  app/javascript/src/components/Invoices/Invoice/InvoiceInfo.tsx
  app/javascript/src/components/Invoices/Invoice/LineItem.tsx
  app/javascript/src/components/time-tracking/EntryCard.tsx
  app/javascript/stylesheets/time-tracking.scss
Labels: PR: reviewed-approved

#455 [BUGFIX]Allow invitation to another workspace
  app/controllers/users/invitations_controller.rb
  app/models/user.rb
  app/views/devise/mailer/invitation_instructions.html.erb
Labels: PR: partially-approved

#456 Client details menu options added
  app/controllers/internal_api/v1/clients_controller.rb
  app/javascript/src/components/Clients/Details/Header.tsx
  app/javascript/src/components/Clients/Modals/AddProject.tsx
  app/javascript/src/components/Clients/Modals/DeleteClient.tsx
  spec/requests/internal_api/v1/clients/show_spec.rb
Labels: PR: partially-approved

#463 Display Client in Project List
  app/javascript/src/components/Projects/List/project.tsx
Labels: PR: partially-approved

#460 resolved cash formatter issue
  app/javascript/src/helpers/cashFormater.ts
Labels: bug, PR: unreviewed, PR: partially-approved

#464 Env typo fixed
  config/environments/development.rb
Labels: PR: unreviewed

#454 Team member Delete Api
  app/controllers/internal_api/v1/team_controller.rb
  app/models/company_user.rb
  config/locales/en.yml
  config/routes/internal_api.rb
  db/migrate/20220609024351_add_discarded_at_to_company_users.rb
  db/schema.rb
  spec/models/company_user_spec.rb
  spec/requests/internal_api/v1/team/destroy_spec.rb
Labels: PR: reviewed-approved

#457 Time entry report export
  app/controllers/concerns/error_handler.rb
  app/controllers/internal_api/v1/reports_controller.rb
  app/javascript/src/apis/reports.ts
  app/javascript/src/components/Reports/Header/index.tsx
  app/javascript/src/components/Reports/api/applyFilter.ts
  app/javascript/src/components/Reports/index.tsx
  app/models/timesheet_entry.rb
  app/policies/report_policy.rb
  app/services/report/generate_csv.rb
  app/services/report/generate_pdf.rb
  app/views/reports/pdf.html.erb
  config/routes/internal_api.rb
  spec/policies/report_policy_spec.rb
  spec/requests/internal_api/v1/reports/download_spec.rb
  spec/services/report/generate_csv_spec.rb
  spec/services/report/generate_pdf_spec.rb
  spec/services/report/group_by_spec.rb
Labels: PR: partially-approved

#459 [BUGFIX]Allow user to be invited to multiple admins' workspaces
  app/controllers/users/invitations_controller.rb
Labels: PR: partially-approved

#411 Organisation settings page
  app/controllers/internal_api/v1/companies_controller.rb
  app/javascript/src/apis/companies.ts
  app/javascript/src/apis/companyProfile.ts
  app/javascript/src/components/Profile/Layout.tsx
  app/javascript/src/components/Profile/Organization/Billing/index.tsx
  app/javascript/src/components/Profile/Organization/Edit/index.tsx
  app/javascript/src/components/Profile/Organization/Payment/index.tsx
  app/javascript/src/components/Profile/RouteConfig.tsx
  app/javascript/src/components/Profile/SubNav.tsx
  app/javascript/src/constants/countryList.ts
  app/javascript/src/constants/currencyList.ts
  app/views/devise/registrations/edit.html.erb
  spec/requests/internal_api/v1/companies/index_spec.rb
Labels: PR: partially-approved, frontend

#458 Code refactor
  app/models/client.rb
  app/models/project.rb
  app/services/report/filters.rb
  lib/utility_functions.rb
  spec/models/client_spec.rb
  spec/models/project_spec.rb
  spec/policies/payments/provider_policy_spec.rb
Labels: PR: partially-approved

#461 Creates EmploymentDetail model
  app/models/company_user.rb
  app/models/employment_detail.rb
  db/migrate/20220608124607_create_employment_details.rb
  db/migrate/20220609122157_remove_official_email_id_from_employment_details.rb
  db/migrate/20220613093839_remove_user_from_employment_details.rb
  db/migrate/20220613094006_add_company_user_to_employment_details.rb
  db/schema.rb
  spec/factories/employment_details.rb
  spec/models/company_user_spec.rb
  spec/models/employment_detail_spec.rb
Labels: PR: unreviewed, feature

#468 React code restructured
  app/javascript/src/apis/companies.ts
  app/javascript/src/apis/companyProfile.ts
  app/javascript/src/apis/profile.ts
  app/javascript/src/common/ChartBar/index.tsx
  app/javascript/src/components/Clients/Details/index.tsx
  app/javascript/src/components/Clients/List/Header.tsx
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/components/InvoiceEmail/PayOnlineMenu.tsx
  app/javascript/src/components/InvoiceEmail/index.tsx
  app/javascript/src/components/Invoices/Edit/InvoiceTable.tsx
  app/javascript/src/components/Invoices/Edit/index.tsx
  app/javascript/src/components/Invoices/Generate/ClientSelection.tsx
  app/javascript/src/components/Invoices/Generate/Header.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceSettings.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceTable.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceStatus.tsx
  app/javascript/src/components/Invoices/Invoice/index.tsx
  app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
  app/javascript/src/components/Invoices/List/SendInvoice/index.tsx
  app/javascript/src/components/Invoices/List/SendInvoice/utils.ts
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Invoices/List/index.tsx
  app/javascript/src/components/Invoices/popups/SendInvoice/index.tsx
  app/javascript/src/components/Invoices/popups/SendInvoice/utils.tsx
  app/javascript/src/components/Profile/Organization/Billing/index.tsx
  app/javascript/src/components/Profile/Organization/Edit/index.tsx
  app/javascript/src/components/Profile/Organization/Payment/index.tsx
  app/javascript/src/components/Profile/UserDetail/index.tsx
  app/javascript/src/components/Projects/Details/index.tsx
  app/javascript/src/components/Projects/List/index.tsx
  app/javascript/src/components/Reports/Container/TableRow.tsx
  app/javascript/src/components/payment_settings/SideNav.tsx
  app/javascript/src/components/payment_settings/index.tsx
  app/javascript/src/components/time-tracking/AddEntry.tsx
  app/javascript/src/components/time-tracking/EntryCard.tsx
  app/javascript/src/components/time-tracking/Index.tsx
  app/javascript/src/components/time-tracking/WeeklyEntriesCard.tsx
  config/webpack/alias.js
  tsconfig.json
Labels: PR: unreviewed

#472 Toaster and interceptor issue
  app/javascript/src/components/Profile/BankAccountDetails/CurrencyDropdown.tsx
  app/javascript/src/components/Profile/BankAccountDetails/index.tsx
  app/javascript/src/components/Profile/Layout.tsx
  app/javascript/src/components/Profile/Organization/Edit/index.tsx
  app/javascript/src/components/Profile/UserDetail/index.tsx
Labels: PR: reviewed-approved

#422 An external user should not be able to modify invoice URL to view any invoice in Miru.
  app/controllers/invoices/view_controller.rb
  app/mailers/invoice_mailer.rb
  app/models/invoice.rb
  app/policies/invoice_policy.rb
  db/migrate/20220530064957_add_external_view_key_to_invoice.rb
  db/schema.rb
  db/seeds/09_invoice.rb
  spec/factories/invoices.rb
  spec/models/invoice_spec.rb
  spec/policies/invoice_policy_spec.rb
  spec/requests/invoices/view_spec.rb
Labels: PR: partially-approved

#473 Adds new personal detail fields to Users table
  app/models/user.rb
  db/data/20220614094240_add_personal_detail_fields_to_users.rb
  db/data/verifiers/user_default_social_account_verifier.rb
  db/data_schema.rb
  db/migrate/20220614060405_add_personal_details_to_users.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: PR: unreviewed, feature

#470 Email Verification Window - Backend
  app/controllers/email_confirmations_controller.rb
  app/views/email_confirmations/show.html.erb
  config/initializers/devise.rb
  config/locales/en.yml
  config/routes.rb
  lib/custom_failure.rb
  spec/requests/email_confirmations/resend_spec.rb
  spec/requests/email_confirmations/show_spec.rb
Labels: bug, PR: unreviewed, PR: draft, PR: partially-approved

#480 Added external view key data migration for existing invoices
  db/data/20220615092122_add_external_view_key_to_invoices.rb
  db/data/verifiers/invoice_default_external_view_key_verifier.rb
  db/data_schema.rb
Labels: PR: reviewed-approved

#483 UI/buy plan page
  app/javascript/src/components/PlanDetails/index.tsx
  app/javascript/src/constants/index.tsx
Labels: PR: unreviewed, frontend

#482 Team page updates
  app/controllers/team_controller.rb
  app/javascript/src/common/Toastr.tsx
  app/javascript/src/components/Clients/Modals/EditClient.tsx
  app/javascript/src/components/Clients/Modals/NewClient.tsx
  app/javascript/src/components/Team/Details/index.tsx
  app/javascript/src/components/Team/List/Header.tsx
  app/javascript/src/components/Team/List/Table/TableHead.tsx
  app/javascript/src/components/Team/List/Table/TableRow.tsx
  app/javascript/src/components/Team/List/Table/index.tsx
  app/javascript/src/components/Team/List/index.tsx
  app/javascript/src/components/Team/RouteConfig.tsx
  app/javascript/src/components/Team/modals/AddEditMember.tsx
  app/javascript/src/components/Team/modals/DeleteMember.tsx
  app/javascript/src/components/Team/modals/Modals.tsx
  app/javascript/src/constants/index.tsx
  app/javascript/src/context/TeamContext.tsx
  app/javascript/src/context/UserContext.tsx
  app/javascript/src/mapper/team.mapper.ts
  app/views/team/index.html.erb
  config/routes.rb
  config/webpack/alias.js
  spec/requests/teams/delete_spec.rb
  spec/requests/teams/edit_spec.rb
  spec/requests/teams/index_spec.rb
  spec/requests/teams/update_spec.rb
  tsconfig.json
Labels: PR: partially-approved

#476 Fix VIEW INVOICE button
  app/controllers/invoices/view_controller.rb
  app/mailers/invoice_mailer.rb
  app/views/invoice_mailer/invoice.html.erb
Labels: PR: reviewed-approved

#481 Creates previous_employment_details table
  app/models/employment_detail.rb
  app/models/previous_employment_detail.rb
  app/models/user.rb
  db/migrate/20220614063702_create_previous_employment_details.rb
  db/migrate/20220615152505_remove_company_user_reference_from_previous_employment_details.rb
  db/migrate/20220615152617_add_user_reference_to_previous_employment_details.rb
  db/schema.rb
  spec/factories/previous_employment_details.rb
  spec/models/employment_detail_spec.rb
  spec/models/previous_employment_detail_spec.rb
  spec/models/user_spec.rb
Labels: PR: unreviewed, feature

#487 Fix missing values from invoice screen
  app/javascript/src/components/InvoiceEmail/InvoiceTotalSummary.tsx
  app/javascript/src/components/Invoices/Invoice/LineItem.tsx
Labels: PR: reviewed-approved

#479 Fixed manual line item
  app/javascript/src/components/Invoices/Edit/InvoiceTable.tsx
  app/javascript/src/components/Invoices/Edit/InvoiceTotal.tsx
  app/javascript/src/components/Invoices/Edit/NewLineItemTable.tsx
  app/javascript/src/components/Invoices/Edit/index.tsx
  app/javascript/src/components/Invoices/Generate/Container.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceTable.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceTotal.tsx
  app/javascript/src/components/Invoices/Generate/ManualEntry.tsx
  app/javascript/src/components/Invoices/Generate/NewLineItemTable.tsx
  app/javascript/src/components/Invoices/Generate/index.tsx
  app/javascript/src/components/Invoices/common/utils.js
  app/javascript/src/mapper/generateInvoice.mapper.ts
  app/mailers/invoice_mailer.rb
  app/models/company.rb
  app/views/invoice_mailer/invoice.html.erb
  app/views/invoices/view/show.html.erb
  config/initializers/grover.rb
  db/schema.rb
Labels: PR: unreviewed

#478 Added loader component
  app/javascript/src/common/Loader/index.tsx
  app/javascript/src/components/Profile/Organization/Edit/index.tsx
  app/javascript/src/components/Profile/UserDetail/index.tsx
Labels: enhancement, PR: unreviewed, PR: partially-approved, frontend

#471 Add API to get team members
  app/controllers/internal_api/v1/team_controller.rb
  app/views/internal_api/v1/team/index.json.jbuilder
  config/routes/internal_api.rb
  spec/factories/users.rb
  spec/requests/internal_api/v1/team/index_spec.rb
Labels: PR: reviewed-approved

#485 Team details page
  app/assets/images/user_avatar.svg
  app/javascript/src/components/Team/Details/CompensationDetails/StaticPage.tsx
  app/javascript/src/components/Team/Details/CompensationDetails/index.tsx
  app/javascript/src/components/Team/Details/DeviceDetails/StaticPage.tsx
  app/javascript/src/components/Team/Details/DeviceDetails/index.tsx
  app/javascript/src/components/Team/Details/DocumentDetails/index.tsx
  app/javascript/src/components/Team/Details/EmploymentDetails/StaticPage.tsx
  app/javascript/src/components/Team/Details/EmploymentDetails/index.tsx
  app/javascript/src/components/Team/Details/Layout/Header.tsx
  app/javascript/src/components/Team/Details/Layout/OutletWrapper.tsx
  app/javascript/src/components/Team/Details/Layout/SideNav.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/StaticPage.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/index.tsx
  app/javascript/src/components/Team/Details/ReimburstmentDetails/StaticPage.tsx
  app/javascript/src/components/Team/Details/ReimburstmentDetails/index.tsx
  app/javascript/src/components/Team/Details/index.tsx
  app/javascript/src/components/Team/List/Header.tsx
  app/javascript/src/components/Team/List/Table/TableRow.tsx
  app/javascript/src/components/Team/RouteConfig.tsx
  app/javascript/src/context/TeamDetailsContext.tsx
  app/javascript/stylesheets/application.scss
  tsconfig.json
  yarn.lock
Labels: PR: partially-approved

#492 Removed login redirection for 401 responses
  app/javascript/src/apis/axios.ts
Labels: PR: unreviewed

#494 Api integration team list
  app/javascript/src/apis/team.ts
  app/javascript/src/components/Team/Details/EmploymentDetails/StaticPage.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/StaticPage.tsx
  app/javascript/src/components/Team/List/Table/TableRow.tsx
  app/javascript/src/components/Team/List/index.tsx
  app/javascript/src/components/Team/modals/DeleteMember.tsx
  app/javascript/src/mapper/team.mapper.ts
Labels: PR: partially-approved

#495 Fixed the issue in displaying the invoice total in edit page
  app/javascript/src/components/Invoices/Edit/InvoiceTotal.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceTotalSummary.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/EditLineItems.tsx
  app/javascript/src/mapper/editInvoice.mapper.ts
  app/views/internal_api/v1/partial/_invoice_line_item.json.jbuilder
Labels: PR: partially-approved

#488 Delete entry issue for admin
  app/javascript/src/components/time-tracking/Index.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved, PR: partially-approved, frontend

#491 Overdue and outstanding amount in project detail page
  app/javascript/src/components/Invoices/common/NewLineItemRow/EditLineItems.tsx
  app/javascript/src/components/Projects/Details/index.tsx
  app/javascript/src/helpers/cashFormater.ts
  app/javascript/src/mapper/project.mapper.ts
  app/models/invoice.rb
  app/models/project.rb
  app/views/internal_api/v1/projects/show.json.jbuilder
  spec/models/invoice_spec.rb
  spec/models/project_spec.rb
  spec/requests/internal_api/v1/projects/show_spec.rb
Labels: PR: partially-approved

#484 Redirect to email verification window
  app/controllers/users/registrations_controller.rb
  app/javascript/src/components/EmailVerification/index.tsx
  app/views/email_confirmations/show.html.erb
  spec/requests/users/registrations/create_spec.rb
Labels: bug, PR: unreviewed, PR: reviewed-changes-requested, PR: partially-approved, Do not merge

#498 Update email content
  app/views/devise/mailer/invitation_instructions.html.erb
  app/views/devise/mailer/invitation_instructions.text.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  config/locales/devise.en.yml
  config/locales/devise_invitable.en.yml
Labels: PR: partially-approved

#500 Update PreviousEmployment reference and Table name
  app/models/employment_detail.rb
  app/models/previous_employment.rb
  app/models/previous_employment_detail.rb
  app/models/user.rb
  db/migrate/20220620121544_remove_employment_detail_reference_from_previous_employment_details.rb
  db/migrate/20220620122048_change_previous_employment_detail_to_previous_employment.rb
  db/schema.rb
  spec/factories/previous_employments.rb
  spec/models/employment_detail_spec.rb
  spec/models/previous_employment_spec.rb
  spec/models/user_spec.rb
Labels: enhancement, PR: unreviewed, PR: reviewed-approved, PR: partially-approved

#499 Add members id to team members API
  app/views/internal_api/v1/team/index.json.jbuilder
  spec/requests/internal_api/v1/team/index_spec.rb
Labels: PR: reviewed-approved

#506 Fixed duplicate toasters
  app/javascript/src/common/Toastr.tsx
  app/javascript/src/components/Projects/Details/index.tsx
  db/schema.rb
Labels: PR: partially-approved

#497 React Context in settings app
  app/javascript/src/components/Profile/Layout.tsx
  app/javascript/src/components/Profile/Organization/Edit/index.tsx
  app/javascript/src/components/Profile/UserDetail/index.tsx
  app/javascript/src/components/Profile/context/EntryContext.tsx
Labels: enhancement, PR: unreviewed, PR: reviewed-changes-requested, PR: partially-approved

#510 Use slice instead of fetch-values
  app/services/report/result.rb
Labels: PR: reviewed-approved

#505 Removed duplicate line items and ordered the results by date
  app/models/client.rb
  spec/models/client_spec.rb
Labels: PR: partially-approved

#507 Creates devices table and associations
  app/models/company.rb
  app/models/device.rb
  app/models/user.rb
  db/migrate/20220621054843_create_devices.rb
  db/migrate/20220621150746_change_column_name_in_devices.rb
  db/schema.rb
  spec/factories/devices.rb
  spec/models/company_spec.rb
  spec/models/device_spec.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved, feature

#512 Added index to work_date column
  app/models/timesheet_entry.rb
  db/migrate/20220622064230_add_index_to_work_date.rb
  db/schema.rb
Labels: PR: unreviewed

#502 Fixed the loader issue
  app/javascript/src/components/Profile/BankAccountDetails/BankInfo.tsx
  app/javascript/src/components/Profile/BankAccountDetails/CurrencyDropdown.tsx
  app/javascript/src/components/Profile/BankAccountDetails/index.tsx
Labels: PR: unreviewed

#517 Fixed the issue in closing the send invoice modal
  app/javascript/src/components/Invoices/List/SendInvoice/index.tsx
  app/javascript/src/components/Invoices/List/index.tsx
Labels: PR: partially-approved

#501 Edit/delete existing line items
  app/javascript/src/components/Invoices/Edit/InvoiceTable.tsx
  app/javascript/src/components/Invoices/Edit/InvoiceTotal.tsx
  app/javascript/src/components/Invoices/Edit/index.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceTable.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceLineItems.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/EditLineItems.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/index.tsx
  app/javascript/src/components/Invoices/common/utils.js
Labels: PR: partially-approved

#515 Update 'company_users' table with employment details
  app/models/company_user.rb
  app/models/employment_detail.rb
  app/models/timesheet_entry.rb
  db/migrate/20220622155051_add_employment_details_to_company_users.rb
  db/migrate/20220622160123_drop_employment_details_table.rb
  db/schema.rb
  spec/factories/company_users.rb
  spec/factories/employment_details.rb
  spec/models/company_user_spec.rb
  spec/models/employment_detail_spec.rb
Labels: PR: reviewed-approved, feature

#523 [Testing Review App] Invoice no-reply mail id typo fixed
  app/mailers/invoice_mailer.rb
Labels: PR: unreviewed

#516 Refactor route to consider report type
  app/controllers/internal_api/v1/reports/time_entries_controller.rb
  app/javascript/src/apis/reports.ts
  app/services/reports/time_entries/filters.rb
  app/services/reports/time_entries/generate_csv.rb
  app/services/reports/time_entries/generate_pdf.rb
  app/services/reports/time_entries/group_by.rb
  app/services/reports/time_entries/result.rb
  app/views/internal_api/v1/reports/time_entries/index.json.jbuilder
  config/routes/internal_api.rb
  spec/requests/internal_api/v1/clients/index_spec.rb
  spec/requests/internal_api/v1/clients/show_spec.rb
  spec/requests/internal_api/v1/generate_invoice/index_spec.rb
  spec/requests/internal_api/v1/generate_invoice/show_spec.rb
  spec/requests/internal_api/v1/time_entry_reports/download_spec.rb
  spec/requests/internal_api/v1/time_entry_reports/index_spec.rb
  spec/services/reports/time_entries/generate_csv_spec.rb
  spec/services/reports/time_entries/generate_pdf_spec.rb
  spec/services/reports/time_entries/group_by_spec.rb
Labels: PR: partially-approved

#528 Added social media link and currency symbol to amount
  app/mailers/invoice_mailer.rb
  app/services/format_amount_service.rb
  app/services/invoice_payment/pdf_generation.rb
  app/views/mailers/invoice_mailer/invoice.html.erb
  app/views/mailers/invoice_mailer/invoice.text.erb
  spec/mailers/invoice_mailer_spec.rb
  spec/models/project_spec.rb
  spec/services/format_amount_service_spec.rb
Labels: PR: partially-approved

#518 Fixed the issue in assigning role to team member
  app/controllers/team_controller.rb
  config/locales/en.yml
Labels: PR: partially-approved

#527 Client revenue report
  app/controllers/internal_api/v1/reports/client_revenues_controller.rb
  app/models/client.rb
  app/views/internal_api/v1/reports/client_revenues/index.json.jbuilder
  config/routes/internal_api.rb
  spec/requests/internal_api/v1/client_revenue_report/index_spec.rb
  spec/requests/internal_api/v1/team/index_spec.rb
Labels: PR: unreviewed

#529 Amount in project detail page will have company default currency symbol
  app/javascript/src/components/Projects/Details/index.tsx
  app/javascript/src/mapper/project.mapper.ts
  app/models/project.rb
  spec/models/project_spec.rb
Labels: PR: unreviewed

#524 Refactor: Added Navigation Helper to generate navbar items dynamically
  app/helpers/navigation_helper.rb
  app/views/partial/_navbar.html.erb
  spec/helpers/navigation_helper_spec.rb
Labels: PR: unreviewed

#530 Reports List Page
  app/javascript/images/Calendar.svg
  app/javascript/images/Hours.svg
  app/javascript/images/OverdueOutstanding.svg
  app/javascript/images/Revenue.svg
  app/javascript/images/back-arrow.svg
  app/javascript/src/components/Reports/Header/index.tsx
  app/javascript/src/components/Reports/RouteConfig.tsx
  app/javascript/src/components/Reports/index.tsx
  app/javascript/src/components/Reports/outstandingInvoices/index.tsx
  app/javascript/src/components/Reports/reportList/index.tsx
  app/javascript/src/components/Reports/reportList/reportCard.tsx
  app/javascript/src/components/Reports/revenueByClient/index.tsx
  app/javascript/src/components/Reports/timeEntry/index.tsx
  app/javascript/src/components/Reports/totalHoursLogged/index.tsx
  config/routes.rb
  db/schema.rb
  tailwind.config.js
Labels: PR: unreviewed, feature

#533 Invitation migration - part 1
  app/models/company.rb
  app/models/invitation.rb
  app/models/timesheet_entry.rb
  app/models/user.rb
  db/data/20220628121346_create_invitations.rb
  db/data/verifiers/invitation_verifier.rb
  db/data_schema.rb
  db/migrate/20220628121346_create_invitations.rb
  db/schema.rb
  spec/factories/invitations.rb
  spec/models/invitation_spec.rb
Labels: PR: partially-approved

#536 Fix: CVE-2022-32099
  Gemfile.lock
Labels: PR: partially-approved
