Repository saeloun/miru-web, pull requests merged in 2023-05, with the labels that each got.

#1272 Fix responsiveness of client list
  app/javascript/src/common/AutoSearch/index.tsx
  app/javascript/src/components/Clients/List/Header.tsx
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/components/Clients/Modals/DeleteClient.tsx
  app/javascript/src/components/Clients/Modals/EditClient.tsx
  app/javascript/src/components/Clients/Modals/MobileClientForm.tsx
  app/javascript/src/components/Clients/Modals/NewClient.tsx
  app/javascript/stylesheets/application.scss
  spec/system/clients/create_spec.rb
Labels: PR: reviewed-approved

#1279 Profile picture add/delete on teams mobile page
  app/javascript/src/components/Team/Details/Layout/SideNav.tsx
  app/javascript/src/components/Team/Details/Layout/UserInformation.tsx
Labels: PR: reviewed-approved

#1285 Fix: Redirect to invoice page after marking payments as paid
  app/javascript/src/components/payments/Modals/PaymentEntryForm.tsx
Labels: PR: reviewed-approved

#1284 Fix responsive issues in project details
  app/javascript/src/components/Projects/Details/EditMembersListForm.tsx
  app/javascript/src/components/Projects/Details/Mobile/ProjectDetailsForm.tsx
Labels: PR: reviewed-approved

#1281 Added empty state message to projects list page
  app/javascript/src/components/Projects/List/Header.tsx
  app/javascript/src/components/Projects/List/index.tsx
Labels: PR: reviewed-approved

#1282 Update pagination UI on time entry report page
  app/javascript/src/common/Pagination/Pagination.tsx
  app/javascript/src/components/Reports/TimeEntryReport/TimeEntryReportMobileView.tsx
  app/javascript/src/components/Reports/TimeEntryReport/index.tsx
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#1283 Fixed data migration issue
  db/data/20220628121346_create_invitations.rb
  db/schema.rb
Labels: PR: reviewed-approved

#1288 Close image modal on outside click
  app/javascript/src/components/Profile/CommonComponents/UserInformation/index.tsx
  app/javascript/src/components/Team/Details/Layout/SideNav.tsx
Labels: PR: reviewed-approved

#1280 Fix-responsive-client-details
  app/javascript/src/common/FormikFields/InputField/index.tsx
  app/javascript/src/components/Clients/Details/Header.tsx
  app/javascript/src/components/Clients/Details/index.tsx
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/components/Clients/Modals/MobileMenu.tsx
  app/javascript/src/components/Projects/Details/HeadermenuList.tsx
  app/javascript/src/components/Projects/List/Mobile/ProjectForm.tsx
  spec/system/projects/edit_spec.rb
Labels: PR: reviewed-approved

#1286 Fix: Add close button on Send invoice modal on mobile view.
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
Labels: PR: reviewed-approved

#1287 Show client address on invoices
  app/javascript/src/components/Invoices/Generate/MobileView/Container/InvoicePreview/InvoiceInfo.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Container/MenuContainer/InvoiceDetails.tsx
  app/javascript/src/components/Invoices/Generate/index.tsx
  app/javascript/src/components/Invoices/Invoice/ClientInfo.tsx
  app/javascript/src/components/Invoices/Invoice/MobileView/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceDetails/ClientSelection.tsx
  app/models/company.rb
  app/views/internal_api/v1/invoices/_invoice.json.jbuilder
  app/views/internal_api/v1/invoices/edit.json.jbuilder
  app/views/internal_api/v1/invoices/view/show.json.jbuilder
  app/views/internal_api/v1/partial/_client.json.jbuilder
Labels: PR: reviewed-approved

#1291 Design client list page amount section and resolve horizontal scrolling issue in client list table
  app/javascript/src/common/AmountBox/MobileAmountBox.tsx
  app/javascript/src/common/AutoSearch/index.tsx
  app/javascript/src/common/ChartBar/index.tsx
  app/javascript/src/components/Clients/List/Header.tsx
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/helpers/cashFormater.ts
Labels: PR: reviewed-approved

#1294 Fix invoice line items quantity on mobile
  app/javascript/src/components/Invoices/Generate/MobileView/Container/AddLineItemContainer/index.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Container/MenuContainer/LineItemRow.tsx
Labels: PR: reviewed-approved

#1296 Default logo for mail view
  app/views/mailers/invoice_mailer/invoice.html.erb
Labels: PR: partially-approved

#1295 send invoice: UI issues
  app/javascript/src/components/Invoices/Generate/MobileView/Container/SendInvoiceContainer/index.tsx
  app/javascript/src/components/Invoices/Invoice/BackButton.tsx
  app/javascript/src/components/Invoices/Invoice/MobileView/index.tsx
  app/javascript/src/components/Invoices/Invoice/index.tsx
Labels: PR: reviewed-approved

#1297 Fix: Invalid Date on changing date format to DD-MM-YYYY
  app/javascript/src/components/Invoices/common/InvoiceForm/SendInvoice/utils.tsx
Labels: PR: reviewed-approved

#1298 Feat/terms of service privacy
  app/javascript/src/StyledComponents/Modal/index.tsx
  app/javascript/src/components/Authentication/FooterLinks/index.tsx
  app/javascript/src/components/Authentication/SignIn/SignInForm.tsx
  app/javascript/src/components/Authentication/SignUp/PrivacyPolicyModal.tsx
  app/javascript/src/components/Authentication/SignUp/SignUpForm.tsx
  app/javascript/src/components/Authentication/SignUp/TermsOfServiceModal.tsx
  app/javascript/src/components/Authentication/SignUp/utils.ts
  app/javascript/src/components/Profile/SubNav.tsx
  app/javascript/src/constants/index.tsx
  spec/system/users/email_confirmations_spec.rb
  spec/system/users/signup_spec.rb
  tailwind.config.js
Labels: PR: unreviewed
