Repository saeloun/miru-web, pull requests merged in 2023-10, with the labels that each got.

#1515 Miru icons docs
  docs/docs/contributing-guide/icons/_category_.json
  docs/docs/contributing-guide/icons/list.md
  docs/docs/contributing-guide/icons/miruicons.md
Labels: hacktoberfest, hacktoberfest-approved

#1516 Miru avatar component docs
  docs/docs/contributing-guide/components/_category_.json
  docs/docs/contributing-guide/components/avatar.md
  docs/static/img/avatar/default.png
  docs/static/img/avatar/with-initials-count.png
  docs/static/img/avatar/with-name.png
  docs/static/img/avatar/with-url.png
Labels: hacktoberfest

#1518 Miru button component docs
  app/javascript/src/StyledComponents/Button.tsx
  docs/docs/contributing-guide/component-library/button.md
  docs/static/img/button/primary-btn.png
  docs/static/img/button/secondary-btn.png
  docs/static/img/button/ternary-btn.png
Labels: hacktoberfest, hacktoberfest-approved

#1521 Miru modal component docs
  docs/docs/contributing-guide/component-library/modal.md
  docs/static/img/modal/default.png
  docs/static/img/modal/with-props.png
Labels: hacktoberfest

#1514 [Feature][UI] Allocated devices tab read only view
  app/controllers/internal_api/v1/users/devices_controller.rb
  app/javascript/src/apis/devices.ts
  app/javascript/src/components/Profile/Layout.tsx
  app/javascript/src/components/Profile/RouteConfig.tsx
  app/javascript/src/components/Profile/SubNav.tsx
  app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/Device.ts
  app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/StaticPage.tsx
  app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/index.tsx
  app/javascript/src/components/Profile/constants.js
  app/javascript/src/miruIcons/index.ts
Labels: hacktoberfest

#1523 TimeInput component docs
  app/javascript/src/StyledComponents/TimeInput/index.tsx
  docs/docs/contributing-guide/component-library/timeinput.md
  docs/static/img/timeinput/default.png
Labels: hacktoberfest

#1522 Sidepanel component docs
  docs/docs/contributing-guide/component-library/sidepanel.md
  docs/static/img/sidepanel/with-props.png
Labels: hacktoberfest

#1532 Create document structure for Miru Docs
  docs/docs/contributing-guide/_category_.json
  docs/docs/product-guide/05-time-tracking.md
  docs/docs/product-guide/_category_.json
  docs/docs/product-guide/account-setup/01-signin-signup.md
  docs/docs/product-guide/account-setup/02-organisation-setup.md
  docs/docs/product-guide/clients/01-client-homepage.md
  docs/docs/product-guide/clients/02-client-add-new.md
  docs/docs/product-guide/clients/_category_.json
  docs/docs/product-guide/invoicing/01-invoice-homepage.md
  docs/docs/product-guide/invoicing/02-invoice-create.md
  docs/docs/product-guide/invoicing/03-invoice-actions.md
  docs/docs/product-guide/invoicing/_category_.json
  docs/docs/product-guide/payments/01-payments.md
  docs/docs/product-guide/payments/_category_.json
  docs/docs/product-guide/projects/01-project-homepage.md
  docs/docs/product-guide/projects/02-project-add-new.md
  docs/docs/product-guide/projects/_category_.json
  docs/docs/product-guide/reports/02-time-entry-report.md
  docs/docs/product-guide/reports/03-revenue-report.md
  docs/docs/product-guide/reports/04-invoices-report.md
  docs/docs/product-guide/reports/05-accounts-aging.md
  docs/docs/product-guide/reports/_category_.json
  docs/docs/product-guide/team/01-team-homepage.md
  docs/docs/product-guide/team/02-team-add-new.md
  docs/docs/product-guide/team/_category_.json
Labels: documentation, hacktoberfest

#1549 Documentation for payments page
  docs/docs/product-guide/payments/01-payments.md
  docs/static/img/product-guide/manual_payment.png
  docs/static/img/product-guide/payment_dashboard.png
Labels: documentation, hacktoberfest

#1488 View holidays calendar
  app/controllers/internal_api/v1/companies_controller.rb
  app/javascript/src/common/CustomYearPicker/index.tsx
  app/javascript/src/components/App.tsx
  app/javascript/src/components/Profile/Organization/Edit/index.tsx
  app/javascript/src/components/Profile/Organization/Holidays/Details/TableRow.tsx
  app/javascript/src/components/Profile/Organization/Holidays/Details/index.tsx
  app/javascript/src/components/Profile/Organization/Holidays/EditHolidays/index.tsx
  app/javascript/src/components/Profile/Organization/Holidays/HolidaysModal.tsx
  app/javascript/src/components/Profile/Organization/Holidays/index.tsx
  app/javascript/src/components/Profile/Organization/Holidays/utils.js
  app/javascript/src/components/Profile/constants.js
  app/javascript/src/context/UserContext.tsx
  app/views/internal_api/v1/holidays/index.json.jbuilder
Labels: hacktoberfest
