Repository saeloun/miru-web, pull requests merged in 2023-03, with the labels that each got.

#1074 Manual entry bug fixes
  app/javascript/src/components/Invoices/common/InvoiceTable/index.tsx
  app/javascript/src/components/Invoices/common/ManualEntry/index.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/NewLineItemStatic.tsx
  app/javascript/src/components/Invoices/common/NewLineItemTable/Header.tsx
  app/javascript/src/components/Invoices/common/NewLineItemTable/index.tsx
Labels: PR: unreviewed

#1091 Reports empty states
  app/javascript/src/common/EmptyStates/index.tsx
  app/javascript/src/components/Invoices/List/NoInvoices.tsx
  app/javascript/src/components/Invoices/common/NewLineItemTable/index.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/Container/index.tsx
  app/javascript/src/components/Reports/Container/index.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/Container/index.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/Container/index.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/index.tsx
  app/javascript/src/components/Reports/TimeEntryReport/TimeEntryReportMobileView.tsx
  app/javascript/src/components/Reports/TimeEntryReport/index.tsx
  app/javascript/src/miruIcons/index.ts
  app/javascript/src/miruIcons/svgIcons/NoSearchResultsState.svg
  app/javascript/src/miruIcons/svgIcons/emptyState.svg
Labels: PR: partially-approved

#1097 Organization settings common components
  app/javascript/src/components/Profile/CommonComponents/Header/index.tsx
  app/javascript/src/components/Profile/CommonComponents/UserInformation/index.tsx
  app/javascript/src/components/Profile/Organization/Edit/FileAcceptanceText.tsx
  app/javascript/src/components/Profile/Organization/Edit/ProfileImage.tsx
  app/javascript/src/components/Profile/Organization/Edit/Uploader.tsx
  app/javascript/src/miruIcons/index.ts
  app/javascript/stylesheets/application.scss
  tailwind.config.js
Labels: PR: partially-approved

#1096 Add Index prefix to ES to avoid name collisions in Index
  config/initializers/elasticsearch.rb
Labels: PR: unreviewed

#1043 Fixed "Invoice page is not getting Automatically refreshed after creating an invoice
  app/controllers/internal_api/v1/invoices_controller.rb
  app/models/invoice.rb
  spec/requests/internal_api/v1/invoices/create_spec.rb
Labels: PR: partially-approved

#1048 Added client logo key in the API response of reports and listing invoices.
  app/controllers/internal_api/v1/reports/outstanding_overdue_invoices_controller.rb
  app/javascript/src/components/Invoices/List/RecentlyUpdated/RecentlyUpdatedCard.tsx
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/Container/Table/TableRow.tsx
  app/javascript/src/components/Reports/Container/ReportRow.tsx
  app/javascript/src/components/Reports/Container/index.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/Container/Table/TableRow.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/Container/Table/TableTitle.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/Container/Table/index.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/interface.ts
  app/javascript/src/components/Reports/RevenueByClientReport/Container/TableRow.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/interface.ts
  app/javascript/src/components/Reports/TimeEntryReport/ReportMobileRow.tsx
  app/javascript/src/components/Reports/TimeEntryReport/TimeEntryReportMobileView.tsx
  app/models/client.rb
  app/models/invoice.rb
  app/services/reports/accounts_aging/fetch_overdue_amount.rb
  app/services/reports/client_revenues/index_service.rb
  app/services/reports/time_entries/result.rb
  app/views/internal_api/v1/partial/_invoice_item.json.jbuilder
  app/views/internal_api/v1/reports/accounts_aging/index.json.jbuilder
  app/views/internal_api/v1/reports/client_revenues/index.json.jbuilder
  app/views/internal_api/v1/reports/outstanding_overdue_invoices/index.json.jbuilder
  app/views/internal_api/v1/reports/time_entries/index.json.jbuilder
  spec/factories/clients.rb
  spec/requests/internal_api/v1/invoices/index_spec.rb
  spec/requests/internal_api/v1/reports/accounts_aging/index_spec.rb
  spec/requests/internal_api/v1/reports/client_revenue/index_spec.rb
  spec/requests/internal_api/v1/reports/outstanding_overdue_invoices/index_spec.rb
  spec/requests/internal_api/v1/reports/time_entry/index_spec.rb
Labels: PR: reviewed-approved

#1099 Employee role mobile view issue
  app/javascript/src/common/Mobile/HOC/withLayout/index.tsx
  app/javascript/src/components/Invoices/List/MoreOptions.tsx
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
Labels: PR: reviewed-approved

#1102 Changed react phone input version to 2.5.3
  app/javascript/src/components/Team/Details/PersonalDetails/Edit/MobileEditPage.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/Edit/StaticPage.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/Edit/index.tsx
  app/javascript/src/mapper/teams.mapper.ts
  app/javascript/stylesheets/application.scss
  package.json
  yarn.lock
Labels: PR: unreviewed

#1105 Phone input field issue in react version update
  app/javascript/src/components/Team/Details/PersonalDetails/Edit/MobileEditPage.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/Edit/StaticPage.tsx
Labels: PR: unreviewed

#1108 Upgrade react-router to latest release
  package.json
  yarn.lock
Labels: PR: unreviewed

#1098 Issues Accounts Aging Report
  app/javascript/src/components/Reports/AccountsAgingReport/Container/Table/TableRow.tsx
  app/javascript/src/components/Reports/Header/index.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1111 Bugfix- Time entry report UI issue
  app/assets/images/moreOption.svg
  app/javascript/src/common/ClickableCheckboxText.tsx
  app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
  app/javascript/src/components/Reports/Filters/ClientFilter.tsx
  app/javascript/src/components/Reports/Filters/DateRangeFilter.tsx
  app/javascript/src/components/Reports/Filters/FilterSideBar.tsx
  app/javascript/src/components/Reports/Filters/GroupByFilter.tsx
  app/javascript/src/components/Reports/Filters/StatusFilter.tsx
  app/javascript/src/components/Reports/Filters/TeamMembersFilter.tsx
  app/javascript/src/components/Reports/Header/index.tsx
  app/javascript/src/components/Reports/List/reportCard.tsx
  app/javascript/src/components/Reports/TimeEntryReport/ReportMobileRow.tsx
  app/javascript/src/components/Reports/TimeEntryReport/TimeEntryReportMobileView.tsx
  app/javascript/src/miruIcons/index.ts
Labels: PR: partially-approved

#1101 Refactor time tracking components for Mobile/Desktop view
  app/javascript/src/common/CustomInputText/index.tsx
  app/javascript/src/common/CustomReactSelect/index.tsx
  app/javascript/src/common/CustomTextareaAutosize.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/Edit/MobileEditPage.tsx
  app/javascript/src/components/TimeTracking/EntryCard.tsx
  app/javascript/src/components/TimeTracking/Header.tsx
  app/javascript/src/components/TimeTracking/MobileView/MobileEntryForm.tsx
  app/javascript/src/components/TimeTracking/MonthCalender.tsx
  app/javascript/src/components/TimeTracking/index.tsx
  app/javascript/stylesheets/application.scss
Labels: PR: reviewed-approved

#1113 Bugfix - Invoice filter issue and send Invoice issue
  app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
  app/javascript/src/components/Invoices/List/MoreOptions.tsx
Labels: PR: reviewed-approved

#1119 Ensure that menu on project page should close on clicking anywhere outside the menu box
  app/javascript/src/components/Projects/Details/index.tsx
Labels: PR: reviewed-approved

#1115 Fix: unable to add time entries on week view
  app/javascript/src/components/TimeTracking/SelectProject.tsx
  app/javascript/src/components/TimeTracking/WeeklyEntriesCard.tsx
Labels: PR: reviewed-approved

#1117 Duplicate timesheet entry
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/TimeTracking/EntryCard.tsx
  app/javascript/src/components/TimeTracking/index.tsx
Labels: PR: partially-approved

#1123 Edit project bug: client details page
  app/javascript/src/components/Clients/Details/index.tsx
  app/javascript/src/components/Projects/Modals/AddEditProject.tsx
Labels: PR: partially-approved

#1106 Moved auth routes to react
  app/controllers/application_controller.rb
  app/controllers/companies/purge_logo_controller.rb
  app/controllers/companies_controller.rb
  app/controllers/concerns/error_handler.rb
  app/controllers/email_confirmations_controller.rb
  app/controllers/home_controller.rb
  app/controllers/internal_api/v1/users/registrations_controller.rb
  app/controllers/internal_api/v1/users/sessions_controller.rb
  app/controllers/invitations/accept_controller.rb
  app/controllers/root_controller.rb
  app/controllers/users/confirmations_controller.rb
  app/helpers/application_helper.rb
  app/javascript/packs/application.js
  app/javascript/src/apis/api.ts
  app/javascript/src/common/FormikFields/InputErrors/index.tsx
  app/javascript/src/common/FormikFields/InputField/index.tsx
  app/javascript/src/common/FormikFields/index.tsx
  app/javascript/src/common/Toastr.tsx
  app/javascript/src/components/App.tsx
  app/javascript/src/components/Authentication/ForgotPassword/index.tsx
  app/javascript/src/components/Authentication/ResetPassword/index.tsx
  app/javascript/src/components/Authentication/SignIn/SignInForm.tsx
  app/javascript/src/components/Authentication/SignUp/SignUpForm.tsx
  app/javascript/src/components/EmailVerification/index.tsx
  app/javascript/src/components/Main.tsx
  app/javascript/src/components/Navbar/UserActions.tsx
  app/javascript/src/components/OrganizationSetup/CompanyDetailsForm/index.tsx
  app/javascript/src/constants/index.tsx
  app/javascript/src/constants/routes.ts
  app/javascript/src/context/UserContext.tsx
  app/javascript/stylesheets/application.scss
  app/views/devise/passwords/edit.html.erb
  app/views/email_confirmations/show.html.erb
  app/views/layouts/application.html.erb
  config/initializers/devise.rb
  config/routes.rb
  package.json
  spec/concerns/error_handler/test_controller_spec.rb
  spec/requests/companies/create_spec.rb
  spec/requests/companies/purge_logo/destroy_spec.rb
  spec/requests/email_confirmations/resend_spec.rb
  spec/requests/email_confirmations/show_spec.rb
  spec/requests/home/index_spec.rb
  spec/requests/internal_api/v1/users/sessions/create_spec.rb
  spec/requests/users/registrations/create_spec.rb
  spec/requests/users/registrations/update_spec.rb
  spec/requests/users/sessions/create_spec.rb
  spec/system/clients/create_spec.rb
  spec/system/users/email_confirmations_spec.rb
  spec/system/users/forgot_password_spec.rb
  spec/system/users/login_spec.rb
  spec/system/users/reset_password_spec.rb
  spec/system/users/signup_spec.rb
  yarn.lock
Labels: PR: reviewed-approved

#1122 Employees should not be able to access org. settings
  app/policies/company_policy.rb
  spec/requests/internal_api/v1/companies/index_spec.rb
Labels: PR: unreviewed

#1126 Increase default wait time
  spec/support/capybara.rb
Labels: PR: reviewed-approved

#1129 Fixed time tracking entries unnecessary render on date change
  app/javascript/src/components/TimeTracking/index.tsx
Labels: PR: reviewed-approved

#1131 Removed websocket url in consumer.js
  app/javascript/src/components/Invoices/popups/consumer.js
Labels: PR: partially-approved

#1127 Revenue report: UI changes as per new design
  app/javascript/src/common/TotalHeader/index.tsx
  app/javascript/src/components/Reports/Header/index.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/Container/MobileRow.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/Container/TableRow.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/Container/index.tsx
  app/javascript/stylesheets/application.scss
  tailwind.config.js
Labels: PR: partially-approved

#1133 Fixed workspace navigation for employee
  app/javascript/src/components/Navbar/UserActions.tsx
  app/javascript/src/context/UserContext.tsx
Labels: PR: reviewed-approved

#1135 Redirect user to root path after accepting invitation
  app/controllers/invitations/accept_controller.rb
Labels: PR: unreviewed

#1124 Fix the date time format
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Invoices/common/InvoiceTable/index.tsx
  app/javascript/src/components/Invoices/common/NewLineItemTable/index.tsx
Labels: PR: reviewed-approved

#1109 Refactor stripe checkout service
  app/controllers/webhooks/stripe_controller.rb
  app/services/handle_stripe_checkout_event_service.rb
  lib/stripe_checkout.rb
Labels: PR: unreviewed

#1136 Bulk download loop fixed
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/components/Invoices/List/index.tsx
  app/javascript/src/components/Projects/List/index.tsx
  app/javascript/src/components/Reports/List/index.tsx
  app/javascript/src/components/Team/List/index.tsx
  app/javascript/src/components/payments/index.tsx
Labels: PR: unreviewed

#1130 Generate,Edit,View invoice: UI enhancement
  app/javascript/src/common/CustomAdvanceInput/index.tsx
  app/javascript/src/common/CustomInputText/index.tsx
  app/javascript/src/components/Invoices/Invoice/ClientInfo.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceDetails.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceInfo.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceLineItems.tsx
  app/javascript/src/components/Invoices/Invoice/LineItem.tsx
  app/javascript/src/components/Invoices/common/CompanyInfo/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceDetails/ClientSelection.tsx
  app/javascript/src/components/Invoices/common/InvoiceDetails/index.tsx
  app/javascript/src/components/TimeTracking/index.tsx
Labels: PR: partially-approved

#1110 System specs for clients
  app/javascript/src/StyledComponents/Avatar.tsx
  app/javascript/src/common/AutoSearch/SearchDropdown.tsx
  app/javascript/src/common/AutoSearch/index.tsx
  app/javascript/src/components/Clients/Details/Header.tsx
  app/javascript/src/components/Clients/List/index.tsx
  spec/support/fixtures/invalid-file.png
  spec/support/fixtures/pdf-file.pdf
  spec/support/session_helpers.rb
  spec/system/clients/create_spec.rb
  spec/system/clients/delete_spec.rb
  spec/system/clients/edit_spec.rb
  spec/system/clients/hours_logged_spec.rb
  spec/system/clients/overdue_and_outstanding_calucluation_spec.rb
  spec/system/clients/search_spec.rb
  spec/system/users/signup_spec.rb
Labels: PR: reviewed-approved

#1145 Removed company-related actions outside of internal API.
  app/controllers/companies_controller.rb
  app/controllers/users/sessions_controller.rb
  app/views/companies/new.html.erb
  app/views/companies/show.html.erb
  config/routes.rb
  spec/requests/companies/create_spec.rb
  spec/requests/companies/new_spec.rb
  spec/requests/companies/show_spec.rb
  spec/requests/companies/switch_spec.rb
  spec/requests/companies/update_spec.rb
Labels: PR: reviewed-approved

#1143 Fix projects search
  app/controllers/internal_api/v1/projects/search_controller.rb
  app/models/project.rb
  spec/requests/internal_api/v1/projects/search_spec.rb
Labels: PR: reviewed-approved

#1132 Bugfix- Add manual payment modal
  app/javascript/src/common/CustomAsyncSelect/index.tsx
  app/javascript/src/common/CustomReactSelect/index.tsx
  app/javascript/src/common/CustomReactSelectStyle/Styles/index.ts
  app/javascript/src/components/payments/Modals/AddManualEntry.tsx
  app/javascript/src/components/payments/index.tsx
Labels: PR: partially-approved

#1141 Fix: Export to CSV/PDF functionality is not working on time entry report
  app/javascript/src/components/Reports/Header/index.tsx
Labels: PR: unreviewed

#1137 Add empty states for payments list page
  app/javascript/src/components/payments/PaymentsEmptyState.tsx
  app/javascript/src/components/payments/index.tsx
  tailwind.config.js
Labels: PR: reviewed-approved

#1150 Removed unused devise routes
  app/controllers/users/omniauth_callbacks_controller.rb
  app/controllers/users/passwords_controller.rb
  app/views/devise/passwords/new.html.erb
  config/routes.rb
  spec/requests/dashboards/index_spec.rb
  spec/requests/users/omniauth_callbacks/google_oauth2_spec.rb
  spec/requests/users/passwords/create_spec.rb
  spec/requests/users/passwords/update_spec.rb
  spec/requests/workspaces/update_spec.rb
Labels: PR: reviewed-approved

#1139 Updated the UI for Add Team members modal on project details page
  app/javascript/src/common/CustomInputText/index.tsx
  app/javascript/src/common/CustomReactSelect/index.tsx
  app/javascript/src/common/CustomReactSelectStyle/Styles/index.ts
  app/javascript/src/components/Projects/Details/EditMembersList.tsx
  app/javascript/src/components/Projects/Details/EditMembersListForm.tsx
  app/javascript/stylesheets/application.scss
  dump.rdb
  tailwind.config.js
Labels: PR: partially-approved

#1153 Remove unnecessary auth controllers and views
  app/controllers/users/registrations_controller.rb
  app/controllers/users/sessions_controller.rb
  app/helpers/users/registrations_helper.rb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  config/routes.rb
  spec/requests/users/registrations/purge_avatar_spec.rb
  spec/requests/users/registrations/update_spec.rb
Labels: PR: reviewed-approved

#1138 revenue filter
  app/javascript/src/components/Reports/RevenueByClientReport/Filters/index.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/index.tsx
Labels: PR: partially-approved

#1142 Added empty state design for client list page
  app/javascript/src/components/Clients/List/index.tsx
Labels: PR: reviewed-approved

#1121 Displaying only clients with billable projects on the revenue report.
  app/controllers/internal_api/v1/reports/client_revenues_controller.rb
  app/javascript/src/apis/reports/clientRevenue.ts
  app/javascript/src/components/Reports/RevenueByClientReport/Filters/index.tsx
  app/models/company.rb
  app/policies/report_policy.rb
  app/services/reports/client_revenues/index_service.rb
  app/views/internal_api/v1/reports/client_revenues/new.json.jbuilder
  config/routes/internal_api.rb
  spec/requests/internal_api/v1/clients/index_spec.rb
  spec/requests/internal_api/v1/reports/client_revenue/index_spec.rb
  spec/requests/internal_api/v1/reports/client_revenue/new_spec.rb
  spec/support/shared_examples/reports/client_revenue/new_success_response_shared_example.rb
Labels: PR: reviewed-approved

#1156 Ensure that pagination on Invoices page will be visible on mobile and iPad view
  app/javascript/src/common/Pagination.tsx
Labels: PR: reviewed-approved

#1140 Add Empty states on time tracking mobile view
  app/javascript/src/components/TimeTracking/EmptyStatesMobileView.tsx
  app/javascript/src/components/TimeTracking/index.tsx
  spec/system/clients/create_spec.rb
Labels: PR: partially-approved

#1107 Generate, Edit & Send Invoice - System Specs
  app/javascript/src/components/Invoices/List/MoreOptions.tsx
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Invoices/List/Table/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceDetails/ClientSelection.tsx
  app/javascript/src/components/Invoices/common/InvoiceDetails/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceForm/Header/index.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/NewLineItemStatic.tsx
  app/javascript/src/components/Invoices/common/NewLineItemTable/index.tsx
  spec/factories/invoices.rb
  spec/rails_helper.rb
  spec/system/invoices/edit_invoice_spec.rb
  spec/system/invoices/generate_invoice_spec.rb
  spec/system/invoices/send_invoice_spec.rb
  spec/system/shared_examples/invoices/edit_invoice.rb
  spec/system/shared_examples/invoices/generate_invoice.rb
  spec/system/shared_examples/invoices/send_invoice.rb
Labels: PR: reviewed-approved

#1160 Fix: Multiple entries are created by clicking on the save button multiple times
  app/javascript/src/components/TimeTracking/EntryForm.tsx
Labels: PR: reviewed-approved

#1164 Fix UI issues on Add payment modal and client detail page
  app/javascript/src/components/Clients/Details/index.tsx
  app/javascript/src/components/payments/Modals/AddManualEntry.tsx
Labels: PR: reviewed-approved

#1166 Fixed current user logout
  app/controllers/internal_api/v1/users/sessions_controller.rb
  app/javascript/src/components/Navbar/UserActions.tsx
  spec/requests/internal_api/v1/users/sessions/destroy_spec.rb
  spec/system/users/logout_spec.rb
Labels: PR: reviewed-approved

#1168 Fixed invalid csrf token on signin form by reloading session after logout
  app/javascript/src/components/Navbar/UserActions.tsx
Labels: PR: reviewed-approved

#1155 Update the UI of authentication flow pages as per feedback
  app/assets/images/miru-managing-clients-screen.png
  app/assets/images/miru-managing-employees-screen.png
  app/assets/images/miru-managing-employees-screen.svg
  app/assets/images/miru-managing-projects-screen.png
  app/assets/images/miru-managing-projects-screen.svg
  app/assets/images/miru-payment-and-invoices-screen.png
  app/assets/images/miru-payment-and-invoices-screen.svg
  app/assets/images/miru-report-and-analysis-screen.png
  app/assets/images/miru-report-and-analysis-screen.svg
  app/assets/images/miru-time-tracking-screen.png
  app/assets/images/miru-time-tracking-screen.svg
  app/javascript/src/common/FormikFields/InputErrors/index.tsx
  app/javascript/src/common/FormikFields/InputField/index.tsx
  app/javascript/src/components/Authentication/ForgotPassword/PasswordResetLinkSentMsg.tsx
  app/javascript/src/components/Authentication/ForgotPassword/index.tsx
  app/javascript/src/components/Authentication/MiruWatermark/index.tsx
  app/javascript/src/components/Authentication/ResetPassword/index.tsx
  app/javascript/src/components/Authentication/ResetPassword/utils.ts
  app/javascript/src/components/Authentication/SignIn/SignInForm.tsx
  app/javascript/src/components/Authentication/SignUp/SignUpForm.tsx
  app/javascript/src/components/Authentication/SignUp/utils.ts
  app/javascript/src/components/OrganizationSetup/CompanyDetailsForm/index.tsx
  app/javascript/src/miruIcons/index.ts
  app/javascript/stylesheets/application.scss
  spec/system/users/signup_spec.rb
  tailwind.config.js
Labels: PR: reviewed-approved

#1171 Add Miru logo watermark to all authentication related pages and add resend password reset link button
  app/assets/images/miru-logo-watermark.svg
  app/javascript/src/common/FormikFields/InputField/index.tsx
  app/javascript/src/common/MiruLogoWatermark/index.tsx
  app/javascript/src/components/Authentication/FooterLinks/index.tsx
  app/javascript/src/components/Authentication/ForgotPassword/PasswordResetLinkSentMsg.tsx
  app/javascript/src/components/Authentication/ForgotPassword/index.tsx
  app/javascript/src/components/Authentication/ResetPassword/index.tsx
  app/javascript/src/components/Authentication/SignIn/SignInForm.tsx
  app/javascript/src/components/Authentication/SignIn/index.tsx
  app/javascript/src/components/Authentication/SignUp/SignUpForm.tsx
  app/javascript/src/components/Authentication/SignUp/index.tsx
  app/javascript/src/miruIcons/index.ts
  tailwind.config.js
Labels: PR: reviewed-approved

#1161 System specs projects
  app/javascript/src/components/Projects/Details/EditMembersListForm.tsx
  app/javascript/src/components/Projects/Details/index.tsx
  app/javascript/src/components/Projects/List/project.tsx
  app/javascript/src/components/Projects/Modals/AddEditProject.tsx
  spec/system/projects/add_team_member_spec.rb
  spec/system/projects/create_spec.rb
  spec/system/projects/delete_spec.rb
  spec/system/projects/edit_spec.rb
  spec/system/projects/search_spec.rb
Labels: PR: reviewed-approved

#1165 Fixed reset and filter counter issue on Revenue filter page
  app/javascript/src/common/ClickableCheckboxText.tsx
  app/javascript/src/components/Navbar/UserActions.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/index.tsx
  app/javascript/src/components/Reports/Filters/ClientFilter.tsx
  app/javascript/src/components/Reports/Header/index.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/index.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/Filters/index.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/index.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/util.ts
  app/javascript/src/components/Reports/TimeEntryReport/index.tsx
  app/javascript/src/components/Reports/totalHoursLogged/index.tsx
Labels: PR: partially-approved

#1172 UI issues fixed on time tracking (mobile)
  app/javascript/src/common/SearchTimeEntries.tsx
  app/javascript/src/components/TimeTracking/MobileView/MobileEntryForm.tsx
Labels: PR: partially-approved

#1176 Redirection issue fixed on mobile view
  app/javascript/src/common/Mobile/HOC/withLayout/index.tsx
  app/javascript/src/components/Navbar/Mobile/MoreOptions.tsx
  app/javascript/src/components/Navbar/Mobile/Navigation.tsx
  app/javascript/src/components/Navbar/utils.tsx
Labels: PR: unreviewed

#1177 Bulk download loop bug fixed
  app/javascript/src/components/Invoices/List/index.tsx
Labels: PR: unreviewed

#1104 Fix time entry report
  .vscode/settings.json
  app/controllers/internal_api/v1/reports/time_entries_controller.rb
  app/javascript/src/components/Reports/Container/ReportRow.tsx
  app/javascript/src/components/Reports/Container/index.tsx
  app/javascript/src/components/Reports/TimeEntryReport/index.tsx
  app/javascript/src/components/Reports/api/applyFilter.ts
  app/javascript/src/components/Reports/interface.ts
  app/javascript/src/mapper/report.mapper.ts
  app/models/client.rb
  app/models/project.rb
  app/models/user.rb
  app/services/company_date_formatting_service.rb
  app/services/duration_formatter.rb
  app/services/reports/time_entries/download_service.rb
  app/services/reports/time_entries/generate_csv.rb
  app/services/reports/time_entries/generate_pdf.rb
  app/services/reports/time_entries/group_by.rb
  app/services/reports/time_entries/page_service.rb
  app/services/reports/time_entries/report_service.rb
  app/services/reports/time_entries/result.rb
  app/views/internal_api/v1/reports/time_entries/index.json.jbuilder
  app/views/pdfs/reports.html.erb
  package.json
  spec/requests/internal_api/v1/reports/time_entry/download_spec.rb
  spec/requests/internal_api/v1/reports/time_entry/index_spec.rb
  spec/services/reports/time_entries/download_service_spec.rb
  spec/services/reports/time_entries/generate_csv_spec.rb
  spec/services/reports/time_entries/generate_pdf_spec.rb
  spec/services/reports/time_entries/group_by_spec.rb
  spec/services/reports/time_entries/page_service_spec.rb
  spec/services/reports/time_entries/result_spec.rb
  yarn.lock
Labels: PR: unreviewed

#1184 Fix: If overdue invoices are resent they are marked as “Sent”
  app/controllers/internal_api/v1/invoices_controller.rb
  spec/requests/internal_api/v1/invoices/send_invoice_spec.rb
Labels: PR: partially-approved

#1182 Added cdn to load assets
  config/environments/production.rb
Labels: PR: reviewed-approved

#1181 Bug fixes on Invoice pages
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Invoices/common/InvoiceDetails/ClientSelection.tsx
  app/javascript/src/components/Invoices/common/InvoiceDetails/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceTable/index.tsx
  app/javascript/stylesheets/application.scss
Labels: PR: unreviewed

#1085 Upgrade webpacker to rc6
  .browserslistrc
  .github/workflows/validations.yml
  .node-version
  .nvmrc
  Dockerfile.local
  Dockerfile.test
  Gemfile
  Gemfile.lock
  README.md
  app/javascript/application.js
  app/javascript/modal.js
  app/javascript/org_timezones.js
  app/javascript/server_rendering.js
  app/javascript/settings.js
  app/views/layouts/application.html.erb
  config/webpack/base.js
  config/webpack/development.js
  config/webpack/environment.js
  config/webpack/production.js
  config/webpack/test.js
  config/webpacker.yml
  package.json
  yarn.lock
Labels: PR: unreviewed, Do not merge

#1154 Teams Profile Photo - CRUD
  app/controllers/internal_api/v1/team_members/avatar_controller.rb
  app/javascript/src/apis/team.ts
  app/javascript/src/components/Team/Details/Layout/SideNav.tsx
  app/models/user.rb
  app/policies/team_members/avatar_policy.rb
  app/views/internal_api/v1/team_members/details/_detail.json.jbuilder
  config/routes/internal_api.rb
  spec/requests/internal_api/v1/team_members/avatar/destroy_spec.rb
  spec/requests/internal_api/v1/team_members/avatar/update_spec.rb
  tailwind.config.js
Labels: PR: unreviewed

#1158 Added google auth to signup & signin forms
  Gemfile.lock
  app/controllers/home_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/helpers/application_helper.rb
  app/javascript/src/apis/authentication.ts
  app/javascript/src/components/App.tsx
  app/javascript/src/components/Authentication/SignIn/SignInForm.tsx
  app/javascript/src/components/Authentication/SignUp/SignUpForm.tsx
  app/javascript/src/components/Main.tsx
  app/javascript/src/context/UserContext.tsx
  app/javascript/src/utils/googleOauthLogin.ts
  app/views/devise/confirmations/new.html.erb
Labels: PR: reviewed-approved

#1162 Added Fly io deployment files
  .dockerignore
  Dockerfile
  Gemfile
  Gemfile.lock
  fly.toml
  lib/tasks/fly.rake
  yarn.lock
Labels: PR: unreviewed

#1194 Fix eslint & system specs
  app/javascript/src/components/Authentication/SignIn/SignInForm.tsx
  spec/system/shared_examples/time_tracking/time_tracking.rb
Labels: PR: reviewed-approved

#1195 Fixed omniauth request specs
  spec/requests/users/omniauth_callbacks/google_oauth2_spec.rb
Labels: PR: reviewed-approved

#1196 Upgrade webpacker to shakapacker
  Gemfile
  Gemfile.lock
  Procfile.dev
  app/views/layouts/application.html.erb
  bin/setup
  bin/webpacker
  bin/webpacker-dev-server
  config/webpack/base.js
  config/webpack/webpack.config.js
  config/webpacker.yml
  docker-compose.test.yml
  docker-compose.yml
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#1197 Fix: Flaky tests
  spec/models/invoice_line_item_spec.rb
  spec/system/users/forgot_password_spec.rb
Labels: PR: partially-approved

#1188 Add color for invoice status on payments modal
  app/javascript/src/components/payments/Modals/AddManualEntry.tsx
Labels: PR: reviewed-approved

#1191 Fix: Multiple entries created button click on mobile view
  app/javascript/src/StyledComponents/Button.tsx
  app/javascript/src/components/TimeTracking/EntryForm.tsx
  app/javascript/src/components/TimeTracking/MobileView/MobileEntryForm.tsx
Labels: PR: unreviewed

#1198 Input field background color fixed for autofill
  app/javascript/stylesheets/application.scss
Labels: PR: partially-approved

#1189 Fix: Undefined method pages on time entry report
  app/javascript/src/components/Reports/Filters/filterOptions.ts
  app/javascript/src/components/Reports/TimeEntryReport/index.tsx
Labels: PR: reviewed-approved

#1200 Bugfix- Add payment modal Issue
  app/javascript/src/helpers/outsideClick.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1187 Fix: App breaking if we select ‘flipkart’ as a client on the time tracking module
  app/models/client.rb
  spec/models/client_spec.rb
Labels: PR: unreviewed

#1201 Team member modal bugs
  app/javascript/src/components/Projects/Details/EditMembersList.tsx
  app/javascript/src/components/Projects/Details/EditMembersListForm.tsx
  app/javascript/src/helpers/index.ts
  app/javascript/src/helpers/useKeyPress.ts
Labels: PR: partially-approved

#1202 projet bug fixed on time tracking page
  app/javascript/src/components/TimeTracking/EntryForm.tsx
Labels: PR: reviewed-approved
