Repository saeloun/miru-web, pull requests merged in 2023-02, with the labels that each got.

#981 Log an error for invalid signature
  lib/stripe_checkout.rb
Labels: PR: reviewed-approved

#983 Accounts aging mobile view
  app/javascript/src/StyledComponents/Button.tsx
  app/javascript/src/StyledComponents/MobileMoreOptions.tsx
  app/javascript/src/StyledComponents/SummaryDashboard.tsx
  app/javascript/src/StyledComponents/Tooltip.tsx
  app/javascript/src/StyledComponents/index.tsx
  app/javascript/src/components/App.tsx
  app/javascript/src/components/DisplayView.tsx
  app/javascript/src/components/Invoices/InvoiceSummary/index.tsx
  app/javascript/src/components/Navbar/Mobile/Header.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/Container/Table/TableRow.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/Container/Table/index.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/Container/index.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/Filters/index.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/index.tsx
  app/javascript/src/components/Reports/Header/index.tsx
  app/javascript/src/components/Reports/List/index.tsx
  app/javascript/src/components/Reports/List/reportCard.tsx
  app/javascript/src/context/UserContext.tsx
Labels: PR: reviewed-approved

#980 Set default rounding mode
  Gemfile.lock
  config/initializers/money.rb
Labels: PR: unreviewed

#991 Fixed devise translation error on signup
  config/locales/devise.en.yml
Labels: PR: reviewed-approved

#989 Mobile view invoice page css fixes
  app/javascript/src/StyledComponents/MoreOptions.tsx
  app/javascript/src/StyledComponents/SummaryDashboard.tsx
  app/javascript/src/components/Invoices/InvoiceSummary/index.tsx
  app/javascript/src/components/Invoices/List/BulkActionsWrapper/index.tsx
  app/javascript/src/components/Invoices/List/RecentlyUpdated/RecentlyUpdatedCard.tsx
  app/javascript/src/components/Invoices/List/RecentlyUpdated/index.tsx
  app/javascript/src/components/Invoices/List/Table/TableHeader.tsx
  app/javascript/src/components/Invoices/List/Table/index.tsx
  app/javascript/stylesheets/application.scss
  tailwind.config.js
Labels: PR: unreviewed

#992 Fix Seeds data to always use US information
  db/seeds.rb
  db/seeds/01_company.rb
  db/seeds/02_users.rb
  db/seeds/03_users_roles.rb
  db/seeds/04_employments.rb
  db/seeds/05_clients.rb
  db/seeds/06_projects.rb
  db/seeds/07_project_member.rb
  db/seeds/08_timesheet_entry.rb
  db/seeds/09_invoice.rb
  db/seeds/10_addresses.rb
  db/seeds/11_devices.rb
  db/seeds/12_previous_employment.rb
  db/seeds/13_payments.rb
Labels: PR: unreviewed

#984 Empty state invoice page
  app/javascript/src/components/DisplayView.tsx
  app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
  app/javascript/src/components/Invoices/List/Header.tsx
  app/javascript/src/components/Invoices/List/NoInvoices.tsx
  app/javascript/src/components/Invoices/List/container.tsx
  app/javascript/src/components/Invoices/List/index.tsx
  app/javascript/src/components/Main.tsx
  app/javascript/src/components/Navbar/Mobile/Header.tsx
  app/javascript/src/components/Navbar/Mobile/Navigation.tsx
  app/javascript/src/miruIcons/index.ts
  app/javascript/src/miruIcons/svgIcons/emptyStateInvoices.svg
  tailwind.config.js
Labels: PR: reviewed-approved

#996 Fixed documentation and add employee user to seed data
  README.md
  db/seeds.rb
Labels: PR: unreviewed

#997 Removed PR template for now
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: reviewed-approved

#993 Invoice reports mobile responsive
  app/javascript/src/components/Reports/Header/index.tsx
  app/javascript/src/components/Reports/List/index.tsx
  app/javascript/src/components/Reports/List/reportCard.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/Container/Table/TableHeader.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/Container/Table/TableRow.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/Container/Table/TableTitle.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/Container/Table/index.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/Container/TableRow.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/Container/index.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/index.tsx
Labels: PR: partially-approved

#1008 Use date formats for display from Company date formats settings
  app/controllers/internal_api/v1/payments_controller.rb
  app/models/invoice.rb
  app/presenters/payments_presenter.rb
  app/services/company_date_formatting_service.rb
  app/views/internal_api/v1/partial/_invoice.json.jbuilder
  app/views/internal_api/v1/partial/_invoice_item.json.jbuilder
  spec/factories/companies.rb
  spec/requests/internal_api/v1/payments/index_spec.rb
Labels: PR: unreviewed

#1006 Removed employee access for team member's tab
  app/javascript/src/components/Navbar/utils.tsx
Labels: bug, PR: unreviewed

#998 Invoice UX Feedback - Add entry to the list if name field is present
  app/javascript/src/components/Invoices/common/InvoiceTable/index.tsx
Labels: PR: reviewed-approved

#990 Fixed time entry report bugs and added validation for custom date inputs
  app/javascript/src/common/CustomDateRangePicker/index.tsx
  app/javascript/src/common/CustomDateRangePicker/utils.ts
  app/javascript/src/components/Reports/Filters/index.tsx
  app/javascript/src/components/Reports/Header/index.tsx
  app/javascript/src/components/Reports/TimeEntryReport/index.tsx
  app/javascript/src/components/Reports/TimeEntryReport/utils.ts
Labels: PR: reviewed-approved

#955 Employee to view PTO - Frontend
  app/javascript/src/components/Profile/LeaveBalance/CalendarHeader.tsx
  app/javascript/src/components/Profile/LeaveBalance/QuarterlyCalendar.tsx
  app/javascript/src/components/Profile/LeaveBalance/TileContent.tsx
  app/javascript/src/components/Profile/LeaveBalance/index.tsx
  app/javascript/src/components/Profile/Organization/LeavesAndHolidays/CalendarComponent.tsx
  app/javascript/src/components/Profile/RouteConfig.tsx
  app/javascript/src/components/Profile/SubNav.tsx
  tailwind.config.js
Labels: PR: reviewed-approved

#1000 UX fixed for date field
  app/javascript/src/common/CustomDatePicker/index.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceInfo.tsx
  app/javascript/src/components/Invoices/common/InvoiceDetails/ClientSelection.tsx
  app/javascript/src/components/Invoices/common/InvoiceDetails/index.tsx
  app/javascript/stylesheets/application.scss
Labels: PR: unreviewed

#1010 Fix bug in removing member from a project
  app/models/concerns/project_sql_queries.rb
  spec/models/project_spec.rb
Labels: PR: reviewed-approved

#999 Modifications to Time Entry Report page
  app/javascript/src/components/Reports/Container/ReportRow.tsx
  app/javascript/src/components/Reports/Container/index.tsx
  app/javascript/src/components/Reports/Filters/index.tsx
  app/javascript/src/components/Reports/Header/index.tsx
  app/javascript/src/components/Reports/TimeEntryReport/index.tsx
  app/javascript/src/components/Reports/context/TimeEntryReportContext.tsx
Labels: PR: unreviewed

#1009 Chore: Run a bundle update
  Gemfile
  Gemfile.lock
Labels: PR: unreviewed

#1002 Fix team controller index view
  app/controllers/internal_api/v1/team_controller.rb
  app/presenters/team_presenter.rb
  app/views/internal_api/v1/team/index.json.jbuilder
  spec/presenters/team_presenter_spec.rb
Labels: PR: unreviewed

#1015 UX_feedback/ editable discount and tax fields
  app/javascript/src/components/Invoices/Edit/index.tsx
  app/javascript/src/components/Invoices/Generate/Container.tsx
  app/javascript/src/components/Invoices/common/InvoiceTotal/DiscountMenu.tsx
  app/javascript/src/components/Invoices/common/InvoiceTotal/index.tsx
Labels: PR: unreviewed

#1018 Invoice filter bug
  app/javascript/src/common/CustomDateRangePicker/index.tsx
  app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
  app/javascript/src/components/Invoices/List/index.tsx
Labels: bug, PR: unreviewed, PR: partially-approved

#1014 Axios interceptor setup
  app/javascript/src/apis/api.ts
  app/javascript/src/apis/clients.ts
  app/javascript/src/apis/companies.ts
  app/javascript/src/apis/company-users.ts
  app/javascript/src/apis/companyProfile.ts
  app/javascript/src/apis/generateInvoice.ts
  app/javascript/src/apis/invoices.ts
  app/javascript/src/apis/payment-settings.ts
  app/javascript/src/apis/payments/payments.ts
  app/javascript/src/apis/payments/providers.ts
  app/javascript/src/apis/profile.ts
  app/javascript/src/apis/profiles.ts
  app/javascript/src/apis/project-members.ts
  app/javascript/src/apis/projects.ts
  app/javascript/src/apis/reports.ts
  app/javascript/src/apis/reports/accountsAging.ts
  app/javascript/src/apis/reports/clientRevenue.ts
  app/javascript/src/apis/reports/outstandingOverdueInvoice.ts
  app/javascript/src/apis/team.ts
  app/javascript/src/apis/timeTracking.ts
  app/javascript/src/apis/timesheet-entry.ts
  app/javascript/src/apis/wise.ts
  app/javascript/src/apis/workspaces.ts
  app/javascript/src/components/Clients/Details/index.tsx
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/components/Invoices/Edit/index.tsx
  app/javascript/src/components/Invoices/Invoice/index.tsx
  app/javascript/src/components/OrganizationSetup/CompanyDetailsForm/index.tsx
  app/javascript/src/components/Projects/Details/index.tsx
  app/javascript/src/components/Projects/List/index.tsx
  app/javascript/src/components/payments/index.tsx
Labels: PR: partially-approved

#1017 Add validation for the date range of custom date range picker
  app/javascript/src/common/CustomDateRangePicker/index.tsx
  app/javascript/src/common/CustomDateRangePicker/utils.ts
  app/javascript/src/components/Reports/Header/index.tsx
Labels: PR: reviewed-approved

#1020 Init Sentry
  Gemfile
  Gemfile.lock
  config/initializers/sentry.rb
Labels: PR: unreviewed

#1021 Send error to sentry only if the environment is production or staging
  config/initializers/sentry.rb
Labels: PR: unreviewed

#1016 Refactor presenters - Part 1
  app/controllers/internal_api/v1/clients_controller.rb
  app/presenters/client/index_presenter.rb
  app/presenters/client/show_presenter.rb
  app/presenters/project_members_presenter.rb
  app/services/time_tracking_index_service.rb
Labels: PR: unreviewed

#1019 UX_feedback/disabled new line item button conditionally
  app/javascript/src/components/Invoices/common/InvoiceTable/index.tsx
Labels: PR: unreviewed

#978 Edit Personal details page view
  app/javascript/src/common/CustomAsyncSelect/index.tsx
  app/javascript/src/common/CustomInputText/index.tsx
  app/javascript/src/common/CustomReactSelect/CustomValueContainer.tsx
  app/javascript/src/common/CustomReactSelect/index.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/Edit/StaticPage.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/Edit/index.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/PersonalDetailsState.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/index.tsx
  app/javascript/src/components/Team/Details/index.tsx
  app/javascript/src/components/Team/RouteConfig.tsx
  app/javascript/src/context/TeamDetailsContext.tsx
  app/javascript/src/miruIcons/index.ts
  package.json
  yarn.lock
Labels: PR: unreviewed

#1007 Refactor setup organization page UI
  app/javascript/src/components/OrganizationSetup/CompanyDetailsForm/utils.ts
  app/javascript/src/components/OrganizationSetup/FinancialDetailsForm/index.tsx
  app/javascript/src/components/OrganizationSetup/FinancialDetailsForm/utils.ts
  app/javascript/src/components/OrganizationSetup/index.tsx
Labels: PR: reviewed-approved

#1024 Fix bug which removes employee role of all employees
  app/controllers/internal_api/v1/team_controller.rb
  app/models/user.rb
  spec/models/user_spec.rb
  spec/requests/internal_api/v1/team/destroy_spec.rb
Labels: PR: unreviewed

#1025 Upgrade React Tooltip
  app/javascript/src/common/ChartBar/index.tsx
  app/javascript/stylesheets/application.scss
  package.json
  yarn.lock
Labels: PR: unreviewed

#1005 UX/feedback- Custom datepicker added for manual entry
  app/javascript/src/components/Invoices/Edit/index.tsx
  app/javascript/src/components/Invoices/Generate/Container.tsx
  app/javascript/src/components/Invoices/common/InvoiceTable/index.tsx
  app/javascript/src/components/Invoices/common/ManualEntry/index.tsx
Labels: PR: partially-approved

#1026 Cleaup code comments in spec helpers
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: PR: unreviewed

#1027 Don't run vcr when its a feature spec
  spec/factory_specs/company_factory_spec.rb
  spec/rails_helper.rb
Labels: PR: unreviewed

#1028 Remove empty specs
  spec/models/timesheet_entry_spec.rb
  spec/requests/company_spec.rb
  spec/requests/invoices/payments_spec.rb
Labels: PR: unreviewed

#1033 Increase file upload size limit
  app/javascript/src/components/Clients/Modals/ClientForm.tsx
  app/javascript/src/i18n/index.ts
Labels: PR: unreviewed

#1036 Modified file to be executable
  scripts/ci/eslint.sh
  scripts/ci/rubocop.sh
Labels: PR: reviewed-approved

#1031 Hoc Added
  app/javascript/src/common/Mobile/HOC/withLayout/index.tsx
  app/javascript/src/components/App.tsx
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/components/DisplayView.tsx
  app/javascript/src/components/Invoices/List/index.tsx
  app/javascript/src/components/Main.tsx
  app/javascript/src/components/Navbar/Mobile/Navigation.tsx
  app/javascript/src/components/Projects/List/index.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/index.tsx
  app/javascript/src/components/Reports/List/index.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/index.tsx
  app/javascript/src/components/Team/List/index.tsx
  app/javascript/src/components/TimeTracking/index.tsx
  app/javascript/src/components/payments/index.tsx
  app/javascript/src/context/UserContext.tsx
Labels: PR: unreviewed

#1038 Fix allowed_urls value
  spec/support/database_cleaner.rb
Labels: PR: reviewed-approved

#1039 Close filter panel on rest button click
  app/javascript/src/components/Invoices/List/index.tsx
Labels: PR: reviewed-approved

#933 Expenses APIs - Part 1
  app/controllers/internal_api/v1/expense_categories_controller.rb
  app/controllers/internal_api/v1/vendors_controller.rb
  app/models/company.rb
  app/models/expense.rb
  app/models/expense_category.rb
  app/models/invoice.rb
  app/models/vendor.rb
  app/policies/expense_category_policy.rb
  app/policies/vendor_policy.rb
  app/views/internal_api/v1/expense_categories/create.json.jbuilder
  app/views/internal_api/v1/vendors/create.json.jbuilder
  config/routes/internal_api.rb
  db/migrate/20230111104506_create_expense_categories.rb
  db/migrate/20230111120347_create_vendors.rb
  db/migrate/20230111121547_create_expenses.rb
  db/migrate/20230214122149_add_default_expense_categories.rb
  db/schema.rb
  spec/factories/expense_categories.rb
  spec/factories/expenses.rb
  spec/factories/vendors.rb
  spec/models/company_spec.rb
  spec/models/expense_category_spec.rb
  spec/models/expense_spec.rb
  spec/models/vendor_spec.rb
  spec/policies/expense_category_policy_spec.rb
  spec/policies/vendor_policy_spec.rb
  spec/requests/internal_api/v1/expense_categories/create_spec.rb
  spec/requests/internal_api/v1/vendors/create_spec.rb
Labels: PR: unreviewed, Do not merge

#1029 Basic setup for feature specs
  .rubocop.yml
  Dockerfile.test
  Gemfile
  Gemfile.lock
  docker-compose.test.yml
  scripts/ci/rspec.sh
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/capybara.rb
  spec/support/database_cleaner.rb
  spec/system/users/login_spec.rb
Labels: PR: unreviewed

#1042 Save manual entry with only name
  app/models/invoice_line_item.rb
  spec/models/invoice_line_item_spec.rb
Labels: PR: reviewed-approved

#1041 Add client side validations for team and client name
  app/javascript/src/components/Team/modals/AddEditMember.tsx
  app/models/client.rb
  spec/models/client_spec.rb
Labels: PR: reviewed-approved

#1037 Feature/time entry report mobile
  app/javascript/src/components/Reports/TimeEntryReport/ReportMobileRow.tsx
  app/javascript/src/components/Reports/TimeEntryReport/TimeEntryReportMobileView.tsx
  app/javascript/src/components/Reports/TimeEntryReport/index.tsx
Labels: PR: partially-approved

#1047 Replaced DNS with env
  config/initializers/sentry.rb
Labels: PR: partially-approved

#1040 Stretched logo issue resolution
  app/javascript/src/components/Invoices/common/CompanyInfo/index.tsx
  app/views/mailers/invoice_mailer/invoice.html.erb
Labels: PR: reviewed-approved

#1046 NoInvoices height fixed
  app/javascript/src/components/Invoices/List/index.tsx
Labels: PR: partially-approved

#1051 Fix check on floating number and update pipeline
  .buildkite/pipeline.yml
  spec/models/invoice_line_item_spec.rb
Labels: PR: unreviewed

#1052 Return only kept invoices data in summary
  app/models/company.rb
  app/models/invoice_line_item.rb
  app/services/invoice_payment/pdf_generation.rb
  spec/models/company_spec.rb
  spec/models/invoice_line_item_spec.rb
  spec/spec_helper.rb
Labels: PR: unreviewed

#1044 Fix date format at multiple places
  app/controllers/internal_api/v1/payments_controller.rb
  app/javascript/src/components/InvoiceEmail/InvoiceDetails.tsx
  app/javascript/src/components/Invoices/Edit/index.tsx
  app/javascript/src/components/Invoices/Generate/Container.tsx
  app/javascript/src/components/Invoices/Generate/index.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceDetails.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceInfo.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceLineItems.tsx
  app/javascript/src/components/Invoices/Invoice/LineItem.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/Table.tsx
  app/javascript/src/components/Invoices/MultipleEntriesModal/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceDetails/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceTable/index.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/NewLineItemStatic.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/index.tsx
  app/javascript/src/components/Reports/Container/ReportRow.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/Container/Table/TableRow.tsx
  app/javascript/src/components/payments/Modals/AddManualEntry.tsx
  app/javascript/src/components/payments/index.tsx
  app/models/client.rb
  app/models/timesheet_entry.rb
  app/services/invoices/index_service.rb
  app/services/reports/time_entries/report_service.rb
  app/views/internal_api/v1/partial/_company.json.jbuilder
  app/views/internal_api/v1/payments/new.json.jbuilder
  app/views/internal_api/v1/reports/outstanding_overdue_invoices/index.json.jbuilder
  app/views/internal_api/v1/reports/time_entries/index.json.jbuilder
  spec/requests/internal_api/v1/reports/outstanding_overdue_invoices/index_spec.rb
Labels: PR: reviewed-approved

#1035 Restricted team page access for Employee role. Updated team policy.
  app/policies/team_policy.rb
  spec/policies/team_policy_spec.rb
  spec/requests/internal_api/v1/team/index_spec.rb
Labels: PR: partially-approved

#1055 Only consider kept invoices while calculating invoice summary
  spec/factories/invoices.rb
  spec/requests/internal_api/v1/invoices/index_spec.rb
Labels: PR: reviewed-approved

#1054 Feature specs for login and signup
  spec/system/users/login_spec.rb
  spec/system/users/signup_spec.rb
Labels: PR: partially-approved

#1030 Fix project access on time tracking
  app/policies/client_policy.rb
  app/policies/project_policy.rb
  app/presenters/client/index_presenter.rb
  app/services/time_tracking_index_service.rb
  spec/models/client_spec.rb
  spec/policies/client_policy_spec.rb
  spec/policies/project_policy_spec.rb
Labels: PR: unreviewed, Do not merge

#1063 Fixed flaky specs
  spec/models/invoice_spec.rb
Labels: PR: unreviewed

#1056 feature spec for forgot password
  spec/system/users/forgot_password_spec.rb
Labels: PR: unreviewed

#1060 Time entry filter mobile responsive design
  app/javascript/src/common/CustomDateRangeWIthInput/index.tsx
  app/javascript/src/components/Reports/Header/index.tsx
Labels: PR: unreviewed

#1058 Refactor save stripe settings fn
  app/controllers/internal_api/v1/payment_settings_controller.rb
  app/controllers/internal_api/v1/payments/providers_controller.rb
  app/services/payment_providers/create_stripe_provider_service.rb
  spec/services/payment_providers/create_stripe_provider_service_spec.rb
Labels: PR: reviewed-approved

#1066 Upgrade ruby to 3.2.1
  .ruby-version
  Dockerfile.local
  Dockerfile.test
  Gemfile
  Gemfile.lock
  README.md
Labels: PR: reviewed-approved

#1070 Invoices report: The invoices grouped by client sorted by the invoice issue date in descending order.
  app/models/client.rb
  spec/requests/internal_api/v1/reports/outstanding_overdue_invoices/index_spec.rb
Labels: PR: reviewed-approved

#1062 Fix the issue where long client name was getting into the note column on the time entry report table
  app/javascript/src/components/Reports/Container/ReportRow.tsx
Labels: PR: unreviewed

#1061 Make the invoice email sent to the client mobile responsive
  app/views/mailers/invoice_mailer/invoice.html.erb
Labels: PR: unreviewed

#1067 Added react components for authentication
  app/assets/images/miru-managing-clients-screen.png
  app/assets/images/miru-managing-employees-screen.svg
  app/assets/images/miru-managing-projects-screen.svg
  app/assets/images/miru-payment-and-invoices-screen.svg
  app/assets/images/miru-report-and-analysis-screen.svg
  app/assets/images/miru-time-tracking-screen.svg
  app/assets/images/transparent-miru-logo.svg
  app/javascript/src/apis/authentication.ts
  app/javascript/src/components/Authentication/FeaturePreviews/index.tsx
  app/javascript/src/components/Authentication/FeaturePreviews/utils.ts
  app/javascript/src/components/Authentication/FooterLinks/index.tsx
  app/javascript/src/components/Authentication/FooterLinks/utils.ts
  app/javascript/src/components/Authentication/ForgotPassword/PasswordResetLinkSentMsg.tsx
  app/javascript/src/components/Authentication/ForgotPassword/index.tsx
  app/javascript/src/components/Authentication/ForgotPassword/utils.ts
  app/javascript/src/components/Authentication/MiruWatermark/index.tsx
  app/javascript/src/components/Authentication/ResetPassword/index.tsx
  app/javascript/src/components/Authentication/ResetPassword/utils.ts
  app/javascript/src/components/Authentication/SignIn/SignInForm.tsx
  app/javascript/src/components/Authentication/SignIn/index.tsx
  app/javascript/src/components/Authentication/SignIn/utils.ts
  app/javascript/src/components/Authentication/SignUp/SignUpForm.tsx
  app/javascript/src/components/Authentication/SignUp/index.tsx
  app/javascript/src/components/Authentication/SignUp/utils.ts
  app/javascript/src/components/Main.tsx
  app/javascript/src/constants/index.tsx
  app/javascript/src/constants/routes.ts
  app/javascript/src/miruIcons/index.ts
  app/javascript/src/miruIcons/svgIcons/blurred-miru-logo.svg
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/authentication.scss
  package.json
  yarn.lock
Labels: PR: unreviewed

#1053 Time entry report filter new design
  app/javascript/src/common/CustomDateRangeWIthInput/index.tsx
  app/javascript/src/components/Reports/Filters/ClientFilter.tsx
  app/javascript/src/components/Reports/Filters/DateRangeFilter.tsx
  app/javascript/src/components/Reports/Filters/FilterSideBar.tsx
  app/javascript/src/components/Reports/Filters/FilterSidebarOptions.tsx
  app/javascript/src/components/Reports/Filters/GroupByFilter.tsx
  app/javascript/src/components/Reports/Filters/StatusFilter.tsx
  app/javascript/src/components/Reports/Filters/TeamMembersFilter.tsx
  app/javascript/src/components/Reports/Header/index.tsx
  app/javascript/src/components/Reports/TimeEntryReport/index.tsx
Labels: enhancement, PR: unreviewed, PR: reviewed-approved, PR: reviewed-changes-requested, PR: partially-approved

#1072 Personal details API integration common components PR.
  app/javascript/src/apis/teams.ts
  app/javascript/src/common/CustomReactSelect/CustomErrStyle.ts
  app/javascript/src/common/CustomReactSelect/CustomStyle.ts
  app/javascript/src/common/ErrorSpan/index.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/Edit/validationSchema.ts
  app/javascript/src/components/Team/TeamsRouteConfig.tsx
  app/javascript/src/constants/index.tsx
  app/javascript/src/mapper/teams.mapper.ts
Labels: PR: partially-approved

#986 Fix: Unable to add time entry on week view
  app/javascript/src/components/TimeTracking/WeeklyEntriesCard.tsx
Labels: PR: partially-approved

#1071 Added auth context and its reducer to handle authentication on client side
  app/javascript/src/context/auth.tsx
  app/javascript/src/reducers/auth.ts
  app/javascript/src/utils/storage.ts
Labels: PR: unreviewed

#1073 Update the boundary line dates used in the spec
  spec/requests/internal_api/v1/reports/time_entry/index_spec.rb
Labels: PR: unreviewed

#994 Api integration personal details
  app/javascript/src/StyledComponents/Tooltip.tsx
  app/javascript/src/common/CustomAsyncSelect/index.tsx
  app/javascript/src/common/CustomInputText/index.tsx
  app/javascript/src/common/CustomReactSelect/index.tsx
  app/javascript/src/components/Navbar/utils.tsx
  app/javascript/src/components/Profile/LeaveBalance/QuarterlyCalendar.tsx
  app/javascript/src/components/Team/Details/Layout/Header.tsx
  app/javascript/src/components/Team/Details/Layout/SideNav.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/Edit/StaticPage.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/Edit/index.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/PersonalDetailsState.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/StaticPage.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/index.tsx
  app/javascript/src/components/Team/Details/index.tsx
  app/javascript/src/components/Team/List/Table/TableRow.tsx
  app/javascript/src/components/Team/RouteConfig.tsx
  app/javascript/src/components/TimeTracking/AddEntry.tsx
  app/javascript/src/constants/routes.ts
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/pto.scss
  app/views/internal_api/v1/addresses/_address.json.jbuilder
  app/views/internal_api/v1/partial/_invoice_item.json.jbuilder
  app/views/internal_api/v1/team_members/details/_detail.json.jbuilder
  package.json
  tailwind.config.js
  yarn.lock
Labels: PR: partially-approved

#1075 Added auth email, token to request headers and updated toastr to handle error message of object type
  app/javascript/src/apis/api.ts
  app/javascript/src/common/Toastr.tsx
  app/javascript/src/components/Authentication/FeaturePreviews/index.tsx
  app/javascript/src/components/Authentication/SignUp/SignUpForm.tsx
  tailwind.config.js
Labels: PR: unreviewed

#970 Expense APIs - Part 2
  app/controllers/internal_api/v1/expenses_controller.rb
  app/models/company.rb
  app/models/expense.rb
  app/models/expense_category.rb
  app/models/vendor.rb
  app/policies/expense_policy.rb
  app/presenters/expense/show_presenter.rb
  app/services/expenses/fetch_service.rb
  app/services/expenses/filters_service.rb
  app/views/internal_api/v1/expenses/_expense.json.jbuilder
  app/views/internal_api/v1/expenses/create.json.jbuilder
  app/views/internal_api/v1/expenses/index.json.jbuilder
  app/views/internal_api/v1/expenses/show.json.jbuilder
  config/routes/internal_api.rb
  db/migrate/20230214122149_add_default_expense_categories.rb
  db/seeds.rb
  spec/factories/expenses.rb
  spec/presenters/expense/show_presenter_spec.rb
  spec/requests/internal_api/v1/expenses/create_spec.rb
  spec/requests/internal_api/v1/expenses/index_spec.rb
  spec/requests/internal_api/v1/expenses/show_spec.rb
Labels: PR: unreviewed

#1076 Updated Authenticable concern to support auth email and token
  app/controllers/concerns/authenticable.rb
  spec/rails_helper.rb
  spec/requests/api/v1/timesheet_entries/create_spec.rb
Labels: PR: unreviewed

#1078 Mobile responsive page common components
  app/javascript/src/common/CustomAsyncSelect/index.tsx
  app/javascript/src/common/CustomReactSelect/index.tsx
  app/javascript/src/common/CustomReactSelectStyle/CustomValueContainer/index.tsx
  app/javascript/src/common/CustomReactSelectStyle/ErrStyles/index.ts
  app/javascript/src/common/CustomReactSelectStyle/Styles/index.ts
  app/javascript/src/common/CustomReactSelectStyle/index.tsx
  app/javascript/src/common/Mobile/InfoDescription/index.tsx
  app/javascript/src/common/Mobile/MobileDetailsHeader/index.tsx
  app/javascript/src/common/Mobile/MobileEditHeader/index.tsx
Labels: PR: unreviewed

#1079 Removed registerIntercepts, setAuthHeaders from the components and axios.ts file
  app/javascript/src/apis/axios.ts
  app/javascript/src/components/App.tsx
  app/javascript/src/components/Authentication/ForgotPassword/index.tsx
  app/javascript/src/components/Authentication/ResetPassword/index.tsx
  app/javascript/src/components/Authentication/SignIn/index.tsx
  app/javascript/src/components/Authentication/SignUp/index.tsx
Labels: PR: reviewed-approved

#1032 Mobile responsive personal details page
  app/javascript/src/components/App.tsx
  app/javascript/src/components/Team/Details/Layout/MobileNav.tsx
  app/javascript/src/components/Team/Details/Layout/TeamUrl.tsx
  app/javascript/src/components/Team/Details/Layout/UserInformation.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/Edit/MobileEditPage.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/Edit/index.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/MobilePersonalDetails.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/index.tsx
  app/javascript/src/components/Team/Details/index.tsx
  app/javascript/src/components/Team/List/Table/TableRow.tsx
  app/javascript/src/components/Team/RouteConfig.tsx
  app/javascript/src/context/UserContext.tsx
  tailwind.config.js
  yarn.lock
Labels: PR: partially-approved

#1080 Refactored Main component to handle all the client side view
  app/javascript/src/components/App.tsx
  app/javascript/src/components/Dashboard/Home.tsx
  app/javascript/src/components/Dashboard/index.tsx
  app/javascript/src/components/Main.tsx
Labels: PR: reviewed-approved

#1081 Resolution of UTC date issue
  app/javascript/src/components/Team/Details/PersonalDetails/Edit/index.tsx
Labels: PR: unreviewed

#1082 Add, remove auth token & email on Login and Logout respectively
  app/javascript/src/components/App.tsx
  app/javascript/src/components/Main.tsx
  app/javascript/src/components/Navbar/UserActions.tsx
Labels: PR: reviewed-approved

#1084 Move modal.js to top level packs
  app/javascript/packs/modal.js
Labels: PR: unreviewed

#1086 Add setup to run specs in parallel on local
  Gemfile
  Gemfile.lock
  README.md
Labels: PR: unreviewed

#1087 Add --frozen-lockfile when doing local bin/yarn
  bin/setup
Labels: PR: unreviewed

#1050 Only billable projects/clients should be displayed on the list.
  app/services/reports/accounts_aging/fetch_overdue_amount.rb
  spec/requests/internal_api/v1/reports/accounts_aging/index_spec.rb
Labels: PR: reviewed-approved

#1088 Run npx browserslist@latest --update-db
  yarn.lock
Labels: PR: reviewed-approved

#1011 Fix calculation of revenue on revenue reports
  app/javascript/src/components/Reports/RevenueByClientReport/Container/TableRow.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/Container/index.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/index.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/interface.ts
  app/javascript/src/components/Reports/context/RevenueByClientContext.tsx
  app/models/client.rb
  app/services/reports/client_revenues/index_service.rb
  app/views/internal_api/v1/reports/client_revenues/index.json.jbuilder
  spec/requests/internal_api/v1/reports/client_revenue/index_spec.rb
Labels: PR: reviewed-approved

#1092 Deliver email with AWS SES
  .env.example
  app/mailers/application_mailer.rb
  config/environment.rb
  config/initializers/devise.rb
  docker-compose.test.yml
Labels: PR: reviewed-approved

#1064 Create client spec
  spec/rails_helper.rb
  spec/support/session_helpers.rb
  spec/system/clients/create_spec.rb
Labels: PR: unreviewed

#1093 Edit project bug
  app/javascript/src/components/Projects/Modals/AddEditProject.tsx
Labels: PR: partially-approved
