Repository saeloun/miru-web, pull requests merged in 2023-04, with the labels that each got.

#1207 Removed unnecessary invoice views
  app/views/invoices/edit.erb
  app/views/invoices/show.erb
Labels: PR: unreviewed

#1208 Update packages causing warning with react 18
  app/javascript/src/common/CustomTextareaAutosize.tsx
  app/javascript/src/components/Invoices/common/ManualEntry/index.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/NewLineItemStatic.tsx
  app/javascript/src/components/TimeTracking/EntryForm.tsx
  package.json
  spec/system/projects/add_team_member_spec.rb
  yarn.lock
Labels: PR: partially-approved

#1205 Upgrade Rails and puma
  Gemfile
  Gemfile.lock
Labels: PR: reviewed-approved

#1209 System specs for payments
  app/javascript/src/components/payments/Header.tsx
  app/javascript/src/components/payments/Modals/AddManualEntry.tsx
  spec/factories/invoices.rb
  spec/system/payments/create_spec.rb
  spec/system/payments/index_spec.rb
Labels: PR: reviewed-approved

#1186 added image requirement
  app/assets/images/redDelete.svg
  app/javascript/src/components/Clients/Modals/ClientForm.tsx
  app/javascript/src/components/Clients/Modals/EditClient.tsx
  app/javascript/src/miruIcons/index.ts
  app/javascript/stylesheets/application.scss
  config/webpack/alias.js
Labels: PR: unreviewed

#1212 Added jsx to the extensions config in config/webpacker.yml
  config/webpack/base.js
Labels: PR: unreviewed

#1215 Move invoice views to react
  .env.example
  app/controllers/internal_api/v1/invoices/view_controller.rb
  app/javascript/src/apis/invoices.ts
  app/javascript/src/common/Loader.tsx
  app/javascript/src/components/InvoiceEmail/index.tsx
  app/javascript/src/components/Main.tsx
  app/javascript/src/constants/routes.ts
  app/mailers/invoice_mailer.rb
  app/views/internal_api/v1/invoices/view/show.json.jbuilder
  config/routes.rb
  config/routes/internal_api.rb
  spec/requests/internal_api/v1/invoices/view_spec.rb
Labels: PR: reviewed-approved

#1216 Fixed application.scss pseduo class errors
  app/javascript/src/components/Clients/Modals/ClientForm.tsx
  app/javascript/stylesheets/application.scss
Labels: PR: reviewed-approved

#1203 Fix: Pagination on time entry reports for mobile and iPad screens
  app/javascript/src/components/Reports/TimeEntryReport/TimeEntryReportMobileView.tsx
  app/javascript/src/components/Reports/TimeEntryReport/index.tsx
Labels: PR: reviewed-approved

#1214 Sign in page spacing fixed
  app/javascript/src/common/FormikFields/InputField/index.tsx
Labels: PR: reviewed-approved

#1210 View Invoice (mobile design)
  app/javascript/src/components/Invoices/Generate/MobileView/Container/InvoicePreview/InvoiceInfo.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Container/InvoicePreview/InvoiceTotal.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Container/MenuContainer/LineItemRow.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Header.tsx
  app/javascript/src/components/Invoices/Invoice/MobileView/index.tsx
  app/javascript/src/components/Invoices/Invoice/index.tsx
  app/javascript/src/components/Invoices/popups/DeleteInvoice.tsx
Labels: PR: reviewed-approved

#1220 Fixed unbilled timsheet entries bug on generate invoice
  app/services/generate_invoice/new_line_items_service.rb
Labels: PR: reviewed-approved

#1221 Removed unnecessary invoice views
  app/views/invoices/view/show.html.erb
Labels: PR: unreviewed

#1225 Send invoice page: mobile view
  app/javascript/src/common/CustomAdvanceInput/index.tsx
  app/javascript/src/common/CustomTextareaAutosize.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Container/InvoicePreview/index.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Container/MenuContainer/InvoiceDetails.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Container/MenuContainer/InvoicePreview.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Container/MenuContainer/index.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Container/MenuContainer/utils.ts
  app/javascript/src/components/Invoices/Generate/MobileView/Container/SendInvoiceContainer/index.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Container/index.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/utils.js
Labels: PR: reviewed-approved

#1226 Remove unnecessary rails views
  app/controllers/dashboard_controller.rb
  app/policies/dashboard_policy.rb
  app/views/clients/new.html.erb
  app/views/invitations/_form.html.erb
  app/views/invitations/edit.js.erb
  config/locales/en.yml
  config/routes.rb
  spec/policies/dashboard_policy_spec.rb
  spec/requests/clients/destroy_spec.rb
  spec/requests/dashboards/index_spec.rb
Labels: PR: unreviewed

#1180 System specs for teams
  app/javascript/src/components/Team/List/Table/TableRow.tsx
  app/javascript/src/components/Team/modals/AddEditMember.tsx
  spec/rails_helper.rb
  spec/system/teams/create_spec.rb
  spec/system/teams/delete_spec.rb
  spec/system/teams/edit_spec.rb
Labels: PR: reviewed-approved

#1227 Fix warning for find_by_id selector
  spec/system/shared_examples/time_tracking/time_tracking.rb
Labels: PR: unreviewed

#1224 Added fix for react phone input package
  app/javascript/src/components/Team/Details/PersonalDetails/Edit/MobileEditPage.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/Edit/StaticPage.tsx
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#1230 Fixed client search on generate and edit invoice
  app/javascript/src/components/Invoices/common/InvoiceDetails/ClientSelection.tsx
Labels: PR: reviewed-approved

#1231 Added logic to reset bundle config without arguments
  scripts/ci/rspec.sh
  scripts/ci/rubocop.sh
  scripts/ci/setup.sh
  scripts/ci/system_spec.sh
Labels: PR: reviewed-approved

#1228 Fix some resolutions, upgrade types packages, and fix typos
  .eslint-rules/imports/enforced.js
  .eslintrc
  app/javascript/src/StyledComponents/Tooltip.tsx
  app/javascript/src/common/ClickableCheckboxText.tsx
  app/javascript/src/common/CustomCheckbox.tsx
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/OrganizationSetup/CompanyDetailsForm/index.tsx
  app/javascript/src/components/OrganizationSetup/FinancialDetailsForm/index.tsx
  package.json
  tsconfig.json
  yarn.lock
Labels: PR: unreviewed

#1235 mobile view project list page
  app/javascript/src/common/CustomRadio.tsx
  app/javascript/src/common/FormikFields/InputField/index.tsx
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Invoices/popups/DeleteInvoice.tsx
  app/javascript/src/components/Projects/List/Header.tsx
  app/javascript/src/components/Projects/List/Mobile/ProjectForm.tsx
  app/javascript/src/components/Projects/List/index.tsx
  app/javascript/src/components/Projects/List/project.tsx
  app/javascript/src/components/Projects/Modals/DeleteProject.tsx
Labels: PR: reviewed-approved

#1234 Add mobile responsive clients list page
  app/javascript/src/common/Table/index.tsx
  app/javascript/src/components/Clients/List/index.tsx
Labels: PR: reviewed-approved

#1241 Fixed dockerfile bundler version
  deployment/fly/Dockerfile
Labels: PR: reviewed-approved

#1238 Responsive page for client details
  app/javascript/src/components/Clients/Details/Header.tsx
  app/javascript/src/components/Clients/Details/index.tsx
  app/javascript/src/components/Clients/Modals/DeleteClient.tsx
  app/javascript/src/components/Clients/Modals/MobileMenu.tsx
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#1243 Mobile responsive project details page
  app/javascript/src/StyledComponents/SummaryDashboard.tsx
  app/javascript/src/common/EmptyStates/index.tsx
  app/javascript/src/components/Projects/Details/EditMembersList.tsx
  app/javascript/src/components/Projects/Details/EditMembersListForm.tsx
  app/javascript/src/components/Projects/Details/HeadermenuList.tsx
  app/javascript/src/components/Projects/Details/Mobile/MemberListForm.tsx
  app/javascript/src/components/Projects/Details/Mobile/ProjectDetailsForm.tsx
  app/javascript/src/components/Projects/Details/index.tsx
  app/javascript/src/components/Projects/List/Mobile/ProjectForm.tsx
Labels: PR: reviewed-approved

#1204 Send email to owner and admin once payment is successful
  app/controllers/internal_api/v1/invoices/payments_controller.rb
  app/controllers/invoices/payments_controller.rb
  app/javascript/src/apis/invoices.ts
  app/javascript/src/components/payments/Success/index.tsx
  app/javascript/src/constants/routes.ts
  app/mailers/payment_mailer.rb
  app/views/invoices/payments/success.html.erb
  app/views/mailers/payment_mailer/payment.html.erb
  config/routes.rb
  config/routes/internal_api.rb
  spec/mailers/payment_mailer_spec.rb
  spec/requests/invoices/payments_controller_spec.rb
  spec/services/invoice_payment/stripe_payment_intent_spec.rb
Labels: PR: partially-approved

#1244 added personal details new design
  app/controllers/internal_api/v1/profile_controller.rb
  app/javascript/src/apis/profile.ts
  app/javascript/src/components/Navbar/Mobile/MoreOptions.tsx
  app/javascript/src/components/Navbar/Mobile/Navigation.tsx
  app/javascript/src/components/Navbar/UserActions.tsx
  app/javascript/src/components/Profile/Layout.tsx
  app/javascript/src/components/Profile/Layout/MobileNav.tsx
  app/javascript/src/components/Profile/Layout/TeamUrl.tsx
  app/javascript/src/components/Profile/Layout/UserInformation.tsx
  app/javascript/src/components/Profile/Organization/index.tsx
  app/javascript/src/components/Profile/RouteConfig.tsx
  app/javascript/src/components/Profile/UserDetail/Edit/MobileEditPage.tsx
  app/javascript/src/components/Profile/UserDetail/Edit/StaticPage.tsx
  app/javascript/src/components/Profile/UserDetail/Edit/index.tsx
  app/javascript/src/components/Profile/UserDetail/Edit/validationSchema.ts
  app/javascript/src/components/Profile/UserDetail/UserDetailsView/StaticPage.tsx
  app/javascript/src/components/Profile/UserDetail/UserDetailsView/index.tsx
  app/javascript/src/components/Profile/context/EntryContext.tsx
  app/javascript/src/components/Profile/context/PersonalDetailsState.tsx
  app/javascript/src/miruIcons/index.ts
Labels: PR: unreviewed

#1218 New address changes in client modal
  app/controllers/internal_api/v1/clients_controller.rb
  app/javascript/src/components/Clients/Details/Header.tsx
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/components/Clients/Modals/ClientForm.tsx
  app/javascript/src/components/Clients/Modals/EditClient.tsx
  app/javascript/src/components/Clients/Modals/NewClient.tsx
  app/javascript/src/components/Clients/Modals/formValidationSchema.ts
  app/javascript/src/components/Clients/Modals/utils.ts
  app/javascript/stylesheets/application.scss
  app/models/client.rb
  app/policies/client_policy.rb
  app/presenters/client/show_presenter.rb
  app/views/internal_api/v1/clients/_client.json.jbuilder
  app/views/internal_api/v1/clients/create.json.jbuilder
  app/views/pdfs/invoices.html.erb
  db/migrate/20230309090124_copy_client_address_to_address_model.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/addresses.rb
  spec/factories/clients.rb
  spec/models/client_spec.rb
  spec/policies/client_policy_spec.rb
  spec/requests/internal_api/v1/clients/create_spec.rb
  spec/requests/internal_api/v1/clients/index_spec.rb
  spec/requests/internal_api/v1/clients/show_spec.rb
  spec/requests/internal_api/v1/clients/update_spec.rb
  spec/system/clients/create_spec.rb
  spec/system/clients/edit_spec.rb
Labels: PR: unreviewed

#1247 Generate invoice(mobile view) :feedback fixes
  app/javascript/src/common/FormikFields/InputField/index.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Container/AddLineItemContainer/index.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Container/MenuContainer/InvoiceDetails.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Container/MenuContainer/LineItemRow.tsx
  app/javascript/src/components/TimeTracking/MobileView/MobileEntryForm.tsx
Labels: PR: reviewed-approved

#1237 Search filter enhancement on invoice list page.
  app/javascript/src/components/Invoices/Invoice/BackButton.tsx
  app/javascript/src/components/Invoices/List/Header.tsx
  app/javascript/src/components/Invoices/List/RecentlyUpdated/index.tsx
  app/javascript/src/components/Invoices/List/index.tsx
  app/javascript/src/constants/index.tsx
Labels: PR: reviewed-approved

#1251 Default organisation logo added
  app/javascript/src/StyledComponents/Avatar.tsx
  app/javascript/src/components/Invoices/common/CompanyInfo/index.tsx
  app/javascript/src/components/Navbar/UserActions.tsx
  app/javascript/src/components/Profile/Organization/Details/StaticPage.tsx
Labels: PR: reviewed-approved

#1252 Fix messages for logo
  app/javascript/src/components/Clients/Modals/ClientForm.tsx
  app/javascript/src/i18n/index.ts
  spec/system/clients/create_spec.rb
Labels: PR: unreviewed

#1253 Time tracking module bugs
  app/javascript/src/StyledComponents/TimeInput/index.tsx
  app/javascript/src/common/Pagination/Pagination.tsx
  app/javascript/src/components/TimeTracking/MobileView/MobileEntryForm.tsx
  app/javascript/src/components/TimeTracking/SelectProject.tsx
  app/javascript/src/components/TimeTracking/WeeklyEntries.tsx
  app/javascript/src/components/TimeTracking/WeeklyEntriesCard.tsx
Labels: PR: reviewed-approved

#1256 Feat/profile image users
  app/javascript/src/components/Profile/CommonComponents/UserInformation/index.tsx
  app/javascript/src/components/Profile/SubNav.tsx
Labels: PR: reviewed-approved

#1255 Add & edit project bug fix : mobile view
  app/javascript/src/StyledComponents/SummaryDashboard.tsx
  app/javascript/src/common/CustomRadio.tsx
  app/javascript/src/components/Projects/Details/Mobile/ProjectDetailsForm.tsx
  app/javascript/src/components/Projects/List/Mobile/ProjectForm.tsx
  app/javascript/src/components/Projects/List/project.tsx
  app/javascript/src/helpers/hhmmParser.ts
Labels: PR: reviewed-approved

#1258 fix country code bug
  app/javascript/src/components/OrganizationSetup/CompanyDetailsForm/utils.ts
Labels: PR: reviewed-approved

#1245 Add client responsive form
  app/javascript/src/StyledComponents/Button.tsx
  app/javascript/src/common/CustomReactSelect/index.tsx
  app/javascript/src/common/FormikFields/InputField/index.tsx
  app/javascript/src/components/Clients/Modals/EditClient.tsx
  app/javascript/src/components/Clients/Modals/MobileClientForm.tsx
  app/javascript/src/components/Clients/Modals/NewClient.tsx
Labels: PR: partially-approved

#1260 Create address for new users
  app/javascript/src/apis/profile.ts
  app/javascript/src/apis/teams.ts
  app/javascript/src/components/Profile/UserDetail/Edit/index.tsx
  app/javascript/src/components/Team/Details/PersonalDetails/Edit/index.tsx
Labels: PR: reviewed-approved

#1261 Remove search for employess
  app/javascript/src/components/Projects/List/Header.tsx
  app/javascript/src/components/Projects/List/project.tsx
Labels: PR: reviewed-approved

#1254 Added a page where users can add payment details manually
  app/javascript/src/components/payments/Mobile/AddManualEntryScreen/index.tsx
  app/javascript/src/components/payments/Modals/AddManualEntry.tsx
  app/javascript/src/components/payments/Modals/PaymentEntryForm.tsx
  app/javascript/src/components/payments/Modals/constants.ts
  app/javascript/src/components/payments/Modals/styles.ts
  app/javascript/src/components/payments/index.tsx
  tailwind.config.js
Labels: PR: reviewed-approved

#1259 invoice list more options Bugs
  app/javascript/src/components/Invoices/Edit/Mobile/index.tsx
  app/javascript/src/components/Invoices/Edit/index.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Container/InvoicePreview/index.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Container/MenuContainer/InvoiceDetails.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Container/MenuContainer/index.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Container/SendInvoiceContainer/index.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Container/index.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/Header.tsx
  app/javascript/src/components/Invoices/Generate/MobileView/index.tsx
  app/javascript/src/components/Invoices/Generate/index.tsx
  app/javascript/src/components/Invoices/Invoice/MobileView/index.tsx
  app/javascript/src/components/Invoices/List/MoreOptions.tsx
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Invoices/List/Table/index.tsx
  app/javascript/src/components/Invoices/List/container.tsx
  app/javascript/src/components/Invoices/List/index.tsx
  app/javascript/src/components/Invoices/common/CompanyInfo/index.tsx
Labels: PR: reviewed-approved

#1249 Mobile responsive team list page
  app/javascript/src/components/Team/List/Header.tsx
  app/javascript/src/components/Team/List/Table/TableHead.tsx
  app/javascript/src/components/Team/List/Table/TableRow.tsx
  app/javascript/src/components/Team/List/Table/index.tsx
  app/javascript/src/components/Team/List/index.tsx
  app/javascript/src/components/Team/modals/AddEditMember.tsx
  app/javascript/src/components/Team/modals/DeleteMember.tsx
  app/javascript/src/components/Team/modals/TeamForm.tsx
Labels: PR: reviewed-approved

#1262 Fix: Show payment success page after paying for an invoice
  app/controllers/invoices/payments_controller.rb
  spec/requests/invoices/payments_controller_spec.rb
  spec/services/invoice_payment/stripe_payment_intent_spec.rb
Labels: PR: reviewed-approved

#1263 Fix: Client list responsive page.
  app/javascript/src/components/Clients/List/index.tsx
Labels: PR: partially-approved

#1265 Fixed total hours calculation on time tracking header
  app/javascript/src/components/TimeTracking/Header.tsx
  app/javascript/src/components/TimeTracking/index.tsx
Labels: PR: reviewed-approved

#1267 Sign up page alignment
  app/javascript/src/common/FormikFields/InputField/index.tsx
  app/javascript/src/components/Authentication/FooterLinks/index.tsx
  app/javascript/src/components/Authentication/SignIn/SignInForm.tsx
  app/javascript/src/components/Authentication/SignUp/SignUpForm.tsx
  app/javascript/src/components/Navbar/UserActions.tsx
  tailwind.config.js
Labels: PR: partially-approved

#1270 Fix country code in seed data
  db/seeds.rb
Labels: PR: reviewed-approved

#1269 Fix: Duplicate entry is added to the old date
  app/javascript/src/components/TimeTracking/index.tsx
  spec/system/time_tracking/day_view_spec.rb
Labels: PR: partially-approved

#1276 Fixed device seed data
  db/seeds.rb
Labels: PR: reviewed-approved

#1274 Fix camelcase on team's email column
  app/javascript/src/components/Team/List/Table/TableRow.tsx
Labels: PR: reviewed-approved

#1277 Shift focus from one field to another (Time tracking mobile view)
  app/javascript/src/common/CustomInputText/index.tsx
  app/javascript/src/common/CustomReactSelect/index.tsx
  app/javascript/src/components/TimeTracking/MobileView/MobileEntryForm.tsx
Labels: PR: reviewed-approved

#1278 Empty state message updated
  app/javascript/src/components/Reports/AccountsAgingReport/Container/index.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/Container/index.tsx
Labels: PR: reviewed-approved

#1268 Make organization settings pages mobile responsive
  app/javascript/src/components/Profile/Header.tsx
  app/javascript/src/components/Profile/Layout/MobileNav.tsx
  app/javascript/src/components/Profile/Layout/NavItem.tsx
  app/javascript/src/components/Profile/Layout/TeamUrl.tsx
  app/javascript/src/components/Profile/Layout/UserDetails.tsx
  app/javascript/src/components/Profile/Layout/UserInformation.tsx
  app/javascript/src/components/Profile/Organization/Details/MobileHeader.tsx
  app/javascript/src/components/Profile/Organization/Details/StaticPage.tsx
  app/javascript/src/components/Profile/Organization/Details/index.tsx
  app/javascript/src/components/Profile/Organization/Edit/FileAcceptanceText.tsx
  app/javascript/src/components/Profile/Organization/Edit/ProfileImage.tsx
  app/javascript/src/components/Profile/Organization/Edit/StaticPage.tsx
  app/javascript/src/components/Profile/Organization/Edit/Uploader.tsx
  app/javascript/src/components/Profile/Organization/Edit/index.tsx
  app/javascript/src/miruIcons/index.ts
  tailwind.config.js
Labels: PR: partially-approved
