Repository saeloun/miru-web, pull requests merged in 2023-01, with the labels that each got.

#809 Client revenue flaky rspec test fixes
  app/controllers/internal_api/v1/reports/client_revenues_controller.rb
  app/models/invoice.rb
  app/services/reports/accounts_aging/fetch_overdue_amount.rb
  spec/factories/invoice_line_items.rb
  spec/factories/payments.rb
  spec/requests/internal_api/v1/invoices/index_spec.rb
  spec/requests/internal_api/v1/reports/client_revenue/index_spec.rb
Labels: PR: unreviewed, backend, Do not merge

#871 Refactor company create action to move fatty code to service
  app/controllers/internal_api/v1/companies_controller.rb
  app/services/create_company_service.rb
Labels: PR: unreviewed

#868 Move client revenue controller private functions to service
  app/controllers/internal_api/v1/reports/client_revenues_controller.rb
  app/services/reports/client_revenues/index_service.rb
Labels: PR: unreviewed

#866 Refactor payment views
  app/controllers/internal_api/v1/payments_controller.rb
  app/presenters/payments_presenter.rb
  app/views/internal_api/v1/payments/create.json.jbuilder
  app/views/internal_api/v1/payments/index.json.jbuilder
  app/views/internal_api/v1/payments/new.json.jbuilder
Labels: PR: unreviewed

#861 Fix views to avoid double dots
  app/controllers/internal_api/v1/companies_controller.rb
  app/controllers/internal_api/v1/invoices_controller.rb
  app/views/internal_api/v1/companies/index.json.jbuilder
  app/views/internal_api/v1/invoices/edit.json.jbuilder
  app/views/internal_api/v1/invoices/show.json.jbuilder
Labels: PR: unreviewed

#854 Mark as paid with in invoice
  app/controllers/internal_api/v1/invoices_controller.rb
  app/javascript/src/components/Invoices/Invoice/InvoiceActions.tsx
  app/javascript/src/components/Invoices/common/InvoiceForm/Header/index.tsx
  app/javascript/src/components/Invoices/common/MoreOptions.tsx
  app/javascript/src/components/payments/Modals/AddManualEntry.tsx
  app/javascript/src/components/payments/index.tsx
  app/javascript/src/miruIcons/index.ts
  app/models/invoice.rb
  app/policies/invoice_policy.rb
  spec/policies/invoice_policy_spec.rb
Labels: PR: reviewed-approved

#857 Move fatty project index controller code to service
  app/controllers/internal_api/v1/projects_controller.rb
  app/services/projects_fetch_service.rb
  app/views/internal_api/v1/projects/index.json.jbuilder
Labels: PR: unreviewed

#898 Team page font
  app/javascript/src/components/Team/List/Table/TableRow.tsx
Labels: PR: reviewed-approved

#873 Retained applied filters on invoice even on refresh or page loads
  app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
  app/javascript/src/components/Invoices/List/container.tsx
  app/javascript/src/components/Invoices/List/index.tsx
  app/javascript/src/components/Navbar/UserActions.tsx
  app/javascript/src/constants/index.tsx
Labels: PR: reviewed-approved

#894 Add Discard Model checks on Invoices table
  .env.example
  app/controllers/internal_api/v1/invoices_controller.rb
  app/models/invoice.rb
  config/database.yml
  db/migrate/20221229153456_add_discard_to_invoices.rb
  db/schema.rb
  spec/models/invoice_spec.rb
  spec/requests/internal_api/v1/invoices/destroy_spec.rb
  spec/requests/internal_api/v1/invoices/index_spec.rb
Labels: PR: unreviewed

#884 Refactor time entries report controller
  app/controllers/internal_api/v1/reports/time_entries_controller.rb
  app/services/reports/time_entries/report_service.rb
Labels: PR: reviewed-approved

#903 Refactor factories using traits and nested factories
  spec/factories/clients.rb
  spec/factories/invoices.rb
  spec/factories/users.rb
Labels: PR: reviewed-approved

#875 Custom icons are added to miruIcons
  app/javascript/src/StyledComponents/Avatar.tsx
  app/javascript/src/components/EmailVerification/index.tsx
  app/javascript/src/components/InvoiceEmail/PayOnlineMenu.tsx
  app/javascript/src/components/InvoiceEmail/index.tsx
  app/javascript/src/components/Invoices/Generate/InvoiceSettings.tsx
  app/javascript/src/components/Navbar/Header.tsx
  app/javascript/src/components/Navbar/Mobile/Header.tsx
  app/javascript/src/components/Navbar/UserInfo.tsx
  app/javascript/src/components/Navbar/utils.tsx
  app/javascript/src/components/Profile/BankAccountDetails/BankDetails.tsx
  app/javascript/src/components/Profile/Organization/Edit/index.tsx
  app/javascript/src/components/Profile/Organization/Payment/index.tsx
  app/javascript/src/components/Profile/SubNav.tsx
  app/javascript/src/components/Profile/UserDetail/index.tsx
  app/javascript/src/components/Team/Details/Layout/SideNav.tsx
  app/javascript/src/components/TimeTracking/AddEntry.tsx
  app/javascript/src/components/TimeTracking/EntryCard.tsx
  app/javascript/src/components/TimeTracking/WeeklyEntriesCard.tsx
  app/javascript/src/constants/index.tsx
  app/javascript/src/miruIcons/index.ts
Labels: PR: reviewed-approved

#904 changes in client page and team icon
  app/javascript/src/common/ChartBar/index.tsx
  app/javascript/src/common/Table/index.tsx
  app/javascript/src/components/Clients/Details/index.tsx
  app/javascript/src/components/Clients/List/index.tsx
Labels: PR: reviewed-approved

#867 Accounts Aging reports UI and API integration
  app/assets/images/accounts-aging.svg
  app/javascript/src/StyledComponents/SummaryDashboard.tsx
  app/javascript/src/StyledComponents/index.tsx
  app/javascript/src/apis/reports/accountsAging.ts
  app/javascript/src/components/Reports/AccountsAgingReport/Container/Table/TableHeader.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/Container/Table/TableRow.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/Container/Table/TableTotal.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/Container/Table/index.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/Container/index.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/Filters/index.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/index.tsx
  app/javascript/src/components/Reports/Header/NavigationFilter.tsx
  app/javascript/src/components/Reports/Header/fetchReport.tsx
  app/javascript/src/components/Reports/Header/index.tsx
  app/javascript/src/components/Reports/List/index.tsx
  app/javascript/src/components/Reports/List/reportCard.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/Container/TableRow.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/Container/index.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/Filters/filterOptions.ts
  app/javascript/src/components/Reports/OutstandingInvoiceReport/Filters/index.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/Filters/style.ts
  app/javascript/src/components/Reports/OutstandingInvoiceReport/index.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/interface.ts
  app/javascript/src/components/Reports/RevenueByClientReport/Container/TableRow.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/Container/index.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/Filters/filterOptions.ts
  app/javascript/src/components/Reports/RevenueByClientReport/Filters/index.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/Filters/style.ts
  app/javascript/src/components/Reports/RevenueByClientReport/index.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/interface.ts
  app/javascript/src/components/Reports/TimeEntryReport/index.tsx
  app/javascript/src/components/Reports/api/accountsAging.ts
  app/javascript/src/components/Reports/api/applyFilter.ts
  app/javascript/src/components/Reports/context/AccountsAgingReportContext.tsx
  app/javascript/src/components/Reports/context/EntryContext.tsx
  app/javascript/src/constants/routes.ts
  app/javascript/stylesheets/application.scss
  app/services/reports/accounts_aging/fetch_overdue_amount.rb
  app/views/internal_api/v1/reports/accounts_aging/index.json.jbuilder
Labels: PR: reviewed-approved

#899 loading message added and invoice tab changed
  app/javascript/src/components/DisplayView.tsx
  app/javascript/src/components/Invoices/List/index.tsx
  app/javascript/src/components/Navbar/utils.tsx
Labels: PR: reviewed-approved

#905 invoice page UI changes and report page icon, UI changes
  app/assets/images/accounts-aging.svg
  app/javascript/images/Calendar.svg
  app/javascript/images/Hours.svg
  app/javascript/images/OverdueOutstanding.svg
  app/javascript/images/Revenue.svg
  app/javascript/src/StyledComponents/Badge.tsx
  app/javascript/src/components/Invoices/InvoiceSummary/index.tsx
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Reports/List/index.tsx
  app/javascript/src/components/Reports/List/reportCard.tsx
  app/javascript/src/miruIcons/index.ts
  app/javascript/src/miruIcons/svgIcons/Calendar.svg
  app/javascript/src/miruIcons/svgIcons/CalendarHover.svg
  app/javascript/src/miruIcons/svgIcons/Hours.svg
  app/javascript/src/miruIcons/svgIcons/HoursHover.svg
  app/javascript/src/miruIcons/svgIcons/OverdueOutstanding.svg
  app/javascript/src/miruIcons/svgIcons/OverdueOutstandingHover.svg
  app/javascript/src/miruIcons/svgIcons/Revenue.svg
  app/javascript/src/miruIcons/svgIcons/RevenueHover.svg
  app/javascript/src/miruIcons/svgIcons/accountsAging.svg
  app/javascript/src/miruIcons/svgIcons/accountsAgingHover.svg
  tailwind.config.js
Labels: PR: reviewed-approved

#853 Move Db queries from project show views to controller
  app/controllers/internal_api/v1/projects_controller.rb
  app/models/concerns/project_sql_queries.rb
  app/models/project.rb
  app/views/internal_api/v1/projects/show.json.jbuilder
  spec/models/project_spec.rb
  spec/requests/internal_api/v1/projects/show_spec.rb
Labels: PR: reviewed-approved

#914 Use presenters in OutstandingOverdueInvoicesController
  app/controllers/internal_api/v1/reports/outstanding_overdue_invoices_controller.rb
  app/controllers/internal_api/v1/reports/time_entries_controller.rb
  app/presenters/outstanding_overdue_invoices_report_presenter.rb
Labels: PR: reviewed-approved

#915 Refactor companies controller to use service
  app/controllers/companies_controller.rb
  app/controllers/internal_api/v1/companies_controller.rb
  app/services/create_company_service.rb
Labels: PR: reviewed-approved

#846 Clients specs cypress
  app/javascript/src/common/Table/index.tsx
  app/javascript/src/components/Clients/Details/Header.tsx
  app/javascript/src/components/Clients/List/Header.tsx
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/components/Clients/Modals/DeleteClient.tsx
  app/javascript/src/components/Clients/Modals/EditClient.tsx
  app/javascript/src/components/Clients/Modals/NewClient.tsx
  cypress/constants/routes/paths.js
  cypress/constants/selectors/clients.js
  cypress/e2e/clients/clientsPageForAdmin.spec.js
  cypress/e2e/clients/clientsPageForEmployees.spec.js
  cypress/fixtures/fake.js
Labels: PR: reviewed-approved

#918 Updating copyright year
  README.md
Labels: PR: unreviewed

#911 Bulk Downloads Invoices
  Gemfile
  Gemfile.lock
  app/channels/bulk_invoice_download_channel.rb
  app/controllers/internal_api/v1/invoices/bulk_download_controller.rb
  app/javascript/channels/consumer.js
  app/javascript/channels/index.js
  app/jobs/bulk_invoice_download_job.rb
  app/jobs/delete_active_storage_blob_job.rb
  app/models/invoice.rb
  app/policies/invoices/bulk_download_policy.rb
  app/services/bulk_invoice_download_service.rb
  app/services/invoice_payment/pdf_generation.rb
  config/routes/internal_api.rb
  lib/file_uploader.rb
  lib/zipper.rb
  spec/channels/bulk_invoice_download_channel_spec.rb
  spec/jobs/bulk_invoice_download_job_spec.rb
  spec/requests/internal_api/v1/invoices/bulk_download/index_spec.rb
  spec/services/bulk_invoice_download_service_spec.rb
Labels: PR: reviewed-approved

#919 Refactor invitation controller create action
  app/controllers/internal_api/v1/invitations_controller.rb
  app/services/invitations/create_invitation_service.rb
Labels: PR: reviewed-approved

#917 Fixed: can add new manual line items on the generate & edit invoice
  app/javascript/src/components/Invoices/common/utils.js
Labels: PR: reviewed-approved

#923 UI fixes for invoice page and report page
  app/javascript/src/StyledComponents/SummaryDashboard.tsx
  app/javascript/src/common/CustomCheckbox.tsx
  app/javascript/src/components/Invoices/InvoiceSummary/index.tsx
  app/javascript/src/components/Invoices/List/MoreOptions.tsx
  app/javascript/src/components/Invoices/List/Table/TableHeader.tsx
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Invoices/common/InvoiceTotal/DiscountMenu.tsx
  app/javascript/src/components/Invoices/common/InvoiceTotal/index.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/Container/index.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/index.tsx
Labels: PR: partially-approved

#921 Bugfix on TimeEntry report filters
  app/javascript/src/components/Reports/Header/NavigationFilter.tsx
  app/javascript/src/components/Reports/Header/index.tsx
Labels: bug, PR: unreviewed, PR: partially-approved

#916 Refactor PDF operations [updated]
  app/controllers/internal_api/v1/reports/time_entries_controller.rb
  app/models/invoice.rb
  app/models/invoice_line_item.rb
  app/presenters/invoice_line_item_presenter.rb
  app/services/invoice_payment/pdf_generation.rb
  app/services/reports/time_entries/generate_pdf.rb
  app/views/pdfs/invoices.html.erb
  app/views/pdfs/reports.html.erb
  lib/pdf.rb
  lib/pdf/html_generator.rb
  lib/pdf/temporary.rb
  spec/models/invoice_line_item_spec.rb
  spec/presenters/invoice_line_item_presenter_spec.rb
Labels: PR: partially-approved

#924 Moved timesheet searchkick filters to word middle
  app/models/timesheet_entry.rb
  spec/requests/internal_api/v1/generate_invoice/index_spec.rb
Labels: PR: reviewed-approved

#926 Turn force_ssl to false on production as we already have it on kubernetes
  Dockerfile.local
  Gemfile
  Gemfile.lock
  config/environments/production.rb
Labels: PR: reviewed-approved

#927 Admin & owner should be able to upload client logo when adding a new client
  app/controllers/internal_api/v1/clients_controller.rb
  app/javascript/src/components/Clients/List/Header.tsx
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/components/Clients/Modals/ClientForm.tsx
  app/javascript/src/components/Clients/Modals/EditClient.tsx
  app/javascript/src/components/Clients/Modals/NewClient.tsx
  app/javascript/src/i18n/index.ts
  app/javascript/src/mapper/client.mapper.ts
  app/models/client.rb
  app/policies/client_policy.rb
  app/views/internal_api/v1/clients/_client.json.jbuilder
  app/views/internal_api/v1/partial/_client_list.json.jbuilder
  package.json
  spec/policies/client_policy_spec.rb
  spec/requests/internal_api/v1/clients/create_spec.rb
  spec/requests/internal_api/v1/clients/index_spec.rb
  spec/requests/internal_api/v1/clients/show_spec.rb
  yarn.lock
Labels: PR: partially-approved

#929 Remove Sentry
  config/initializers/sentry.rb
Labels: PR: reviewed-approved

#932 client name fixed on filter
  app/javascript/src/components/Invoices/Generate/InvoiceSettings.tsx
  app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/Filters/index.tsx
Labels: PR: partially-approved

#931 Fixed entries & calendar mismatch bug on time tracking when changing months
  app/javascript/src/components/TimeTracking/MonthCalender.tsx
Labels: PR: reviewed-approved

#910 Bulk download invoices
  app/javascript/src/StyledComponents/MoreOptions.tsx
  app/javascript/src/StyledComponents/index.tsx
  app/javascript/src/apis/invoices.ts
  app/javascript/src/components/Invoices/List/BulkActionsWrapper/AppliedFilters.tsx
  app/javascript/src/components/Invoices/List/BulkActionsWrapper/BulkActions.tsx
  app/javascript/src/components/Invoices/List/BulkActionsWrapper/index.tsx
  app/javascript/src/components/Invoices/List/Header.tsx
  app/javascript/src/components/Invoices/List/RecentlyUpdated/RecentlyUpdatedCard.tsx
  app/javascript/src/components/Invoices/List/RecentlyUpdated/index.tsx
  app/javascript/src/components/Invoices/List/container.tsx
  app/javascript/src/components/Invoices/List/index.tsx
  app/javascript/src/components/Invoices/popups/BulkDownloadInvoices.tsx
  app/javascript/src/components/Invoices/popups/consumer.js
  app/javascript/src/miruIcons/index.ts
  app/services/bulk_invoice_download_service.rb
  lib/zipper.rb
  package.json
  spec/lib/file_uploader_spec.rb
  yarn.lock
Labels: PR: reviewed-approved

#850 Projects cypress specs
  app/javascript/src/components/Projects/List/Header.tsx
  app/javascript/src/components/Projects/List/index.tsx
  app/javascript/src/components/Projects/List/project.tsx
  app/javascript/src/components/Projects/Modals/AddEditProject.tsx
  app/javascript/src/components/Projects/Modals/DeleteProject.tsx
  cypress/constants/routes/paths.js
  cypress/constants/selectors/projects.js
  cypress/e2e/clients/clientsPageForAdmin.spec.js
  cypress/e2e/projects/admin.spec.js
  cypress/e2e/projects/employees.spec.js
  cypress/fixtures/fake.js
  cypress/support/commands.js
Labels: PR: reviewed-approved

#826 Refactored AddPayment to Settle service by moving responsibility into models
  app/controllers/internal_api/v1/payments_controller.rb
  app/models/invoice.rb
  app/models/payment.rb
  app/services/invoice_payment/add_payment.rb
  app/services/invoice_payment/settle.rb
  app/services/invoice_payment/stripe_checkout_fulfillment.rb
  spec/requests/internal_api/v1/payments/create_spec.rb
  spec/requests/internal_api/v1/payments/new_spec.rb
  spec/services/invoice_payment/settle_spec.rb
Labels: PR: reviewed-approved

#937 Can't click on disabled save & update buttons on timesheet entry with updated validations
  app/javascript/src/components/TimeTracking/AddEntry.tsx
  app/javascript/src/helpers/validateTimesheetEntry.ts
Labels: PR: reviewed-approved

#936 Added websocket url to env
  .env.example
  app/javascript/src/components/Invoices/popups/consumer.js
Labels: PR: unreviewed, Do not merge

#939 Updated new entry button styling
  app/javascript/src/components/TimeTracking/AddEntry.tsx
Labels: PR: reviewed-approved

#874 New invoice from project details page
  app/javascript/src/components/Invoices/Generate/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceDetails/ClientSelection.tsx
  app/javascript/src/components/Projects/Details/index.tsx
  app/views/internal_api/v1/projects/show.json.jbuilder
  spec/requests/internal_api/v1/projects/show_spec.rb
Labels: PR: unreviewed

#912 Refactored index action of invoice controller with searchkick, filters & services.
  app/controllers/internal_api/v1/invoices_controller.rb
  app/javascript/src/common/Pagination.tsx
  app/javascript/src/components/Invoices/List/index.tsx
  app/models/invoice.rb
  app/models/timesheet_entry.rb
  app/services/invoices/filters.rb
  app/services/invoices/index_service.rb
  app/views/internal_api/v1/invoices/index.json.jbuilder
  spec/factories/clients.rb
  spec/factories/companies.rb
  spec/factory_specs/company_factory_spec.rb
  spec/models/invoice_spec.rb
  spec/requests/internal_api/v1/invoices/index_spec.rb
Labels: PR: reviewed-approved

#925 currency format function updated
  app/javascript/src/StyledComponents/SummaryDashboard.tsx
  app/javascript/src/components/InvoiceEmail/InvoiceInfo.tsx
  app/javascript/src/components/InvoiceEmail/InvoiceTotalSummary.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceInfo.tsx
  app/javascript/src/components/Invoices/Invoice/InvoiceTotalSummary.tsx
  app/javascript/src/components/Invoices/Invoice/LineItem.tsx
  app/javascript/src/components/Invoices/InvoiceSummary/index.tsx
  app/javascript/src/components/Invoices/List/InvoiceSearch/SearchedDataRow.tsx
  app/javascript/src/components/Invoices/List/RecentlyUpdated/RecentlyUpdatedCard.tsx
  app/javascript/src/components/Invoices/List/SendInvoice/utils.ts
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Invoices/common/InvoiceDetails/index.tsx
  app/javascript/src/components/Invoices/common/InvoiceForm/SendInvoice/utils.tsx
  app/javascript/src/components/Invoices/common/InvoiceTotal/index.tsx
  app/javascript/src/components/Invoices/common/NewLineItemRow/NewLineItemStatic.tsx
  app/javascript/src/components/Invoices/popups/SendInvoice/utils.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/Container/Table/TableRow.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/Container/Table/TableTotal.tsx
  app/javascript/src/components/Reports/OutstandingInvoiceReport/Container/TableRow.tsx
  app/javascript/src/components/Reports/RevenueByClientReport/Container/TableRow.tsx
  app/javascript/src/components/payments/Table/TableRow.tsx
  app/javascript/src/helpers/currency.ts
  app/javascript/src/helpers/index.ts
Labels: PR: partially-approved

#940 Add Kept to company users scope
  app/models/company.rb
Labels: PR: unreviewed

#941 Introduce Strong migrations gem
  Gemfile
  Gemfile.lock
  config/initializers/strong_migrations.rb
Labels: PR: unreviewed

#943 Setup Buildkite test collector
  Gemfile
  Gemfile.lock
  spec/spec_helper.rb
Labels: PR: unreviewed

#945 Removed Test Analytics
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: PR: reviewed-approved

#946 Fixes related to deleted user and indexing
  db/seeds/03_users_roles.rb
  db/seeds/07_project_member.rb
  db/seeds/09_invoice.rb
Labels: PR: merged

#938 updated mapped import to absolute path in all files
  app/javascript/src/components/Clients/Details/index.tsx
  app/javascript/src/components/Clients/List/Header.tsx
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/components/Invoices/Edit/index.tsx
  app/javascript/src/components/Invoices/Generate/index.tsx
  app/javascript/src/components/Projects/Details/index.tsx
  app/javascript/src/components/Reports/api/applyFilter.ts
  app/javascript/src/components/payments/Modals/AddManualEntry.tsx
  app/javascript/src/components/payments/index.tsx
  app/javascript/src/mapper/mappedIndex/index.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved, PR: reviewed-changes-requested

#920 Refactor client show action
  app/controllers/internal_api/v1/clients_controller.rb
  app/models/client.rb
  app/presenters/client_presenter.rb
Labels: PR: reviewed-approved

#948 Hide Billing tab under settings for admin and owner user role
  app/javascript/src/components/Profile/SubNav.tsx
Labels: PR: partially-approved

#951 Bulk download bug
  app/javascript/src/components/Invoices/popups/BulkDownloadInvoices.tsx
Labels: PR: partially-approved

#950 0-30 days total fixed
  app/javascript/src/StyledComponents/SummaryDashboard.tsx
  app/javascript/src/components/Invoices/InvoiceSummary/index.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/Container/Table/index.tsx
Labels: PR: reviewed-approved

#909 Refactored in project_members_controller.rb
  app/controllers/internal_api/v1/project_members_controller.rb
  app/javascript/src/components/Projects/Details/EditMembersList.tsx
  app/services/project_member_service.rb
  spec/requests/internal_api/v1/project_members/update_spec.rb
Labels: PR: reviewed-approved

#954 Fix: capitalize client and project name (#703)
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/components/Projects/List/project.tsx
Labels: PR: unreviewed

#960 Remove Test Analytics
  Gemfile
  Gemfile.lock
  spec/spec_helper.rb
Labels: PR: reviewed-approved

#947 More options mobile view design
  app/javascript/src/StyledComponents/SidePanel/Body.tsx
  app/javascript/src/StyledComponents/SidePanel/index.tsx
  app/javascript/src/components/DisplayView.tsx
  app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
  app/javascript/src/components/Navbar/Mobile/Header.tsx
  app/javascript/src/components/Navbar/Mobile/MoreOptions.tsx
  app/javascript/src/components/Navbar/Mobile/Navigation.tsx
  app/javascript/src/components/Navbar/UserActions.tsx
  app/javascript/src/components/Navbar/UserInfo.tsx
  app/javascript/src/components/Navbar/utils.tsx
  app/javascript/src/components/Reports/AccountsAgingReport/Filters/index.tsx
Labels: PR: partially-approved

#961 Ux review invoice list
  app/javascript/src/StyledComponents/MoreOptions.tsx
  app/javascript/src/common/CustomCheckbox.tsx
  app/javascript/src/components/Invoices/InvoiceSummary/index.tsx
  app/javascript/src/components/Invoices/List/BulkActionsWrapper/BulkActions.tsx
  app/javascript/src/components/Invoices/List/BulkActionsWrapper/index.tsx
  app/javascript/src/components/Invoices/List/Header.tsx
  app/javascript/src/components/Invoices/List/MoreOptions.tsx
  app/javascript/src/components/Invoices/List/RecentlyUpdated/RecentlyUpdatedCard.tsx
  app/javascript/src/components/Invoices/List/RecentlyUpdated/index.tsx
  app/javascript/src/components/Invoices/List/Table/TableHeader.tsx
  app/javascript/src/components/Invoices/List/Table/TableRow.tsx
  app/javascript/src/components/Invoices/List/Table/index.tsx
  tailwind.config.js
Labels: bug, PR: unreviewed, PR: reviewed-changes-requested, PR: partially-approved

#944 Frontend - Add PTO/Holidays [Admin]
  app/javascript/src/components/Profile/DetailsHeader.tsx
  app/javascript/src/components/Profile/Organization/LeavesAndHolidays/CalendarComponent.tsx
  app/javascript/src/components/Profile/Organization/LeavesAndHolidays/Details.tsx
  app/javascript/src/components/Profile/Organization/LeavesAndHolidays/EditLeavesAndHolidays.tsx
  app/javascript/src/components/Profile/Organization/LeavesAndHolidays/HolidaysModal.tsx
  app/javascript/src/components/Profile/Organization/LeavesAndHolidays/index.tsx
  app/javascript/src/components/Profile/RouteConfig.tsx
  app/javascript/src/components/Profile/SubNav.tsx
  app/javascript/src/constants/leaveType.ts
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/pto.scss
  app/javascript/stylesheets/time-tracking.scss
  package.json
  tailwind.config.js
  yarn.lock
Labels: PR: reviewed-approved

#956 workspace switcher broken UI fixed
  app/javascript/src/StyledComponents/Tooltip.tsx
  app/javascript/src/components/Navbar/UserActions.tsx
  app/javascript/src/miruIcons/index.ts
Labels: PR: partially-approved

#953 Fixed download on above 24 hour
  app/models/timesheet_entry.rb
Labels: bug, PR: unreviewed, PR: reviewed-approved, PR: partially-approved, backend

#964 timesheet date issue fixed
  app/javascript/src/components/TimeTracking/MonthCalender.tsx
Labels: PR: partially-approved

#897 Optimize and moved project_list method to service
  app/controllers/internal_api/v1/projects_controller.rb
  app/models/company.rb
  app/services/projects/index_service.rb
  app/services/projects/search_service.rb
  app/services/projects_fetch_service.rb
  app/views/internal_api/v1/projects/index.json.jbuilder
  db/schema.rb
  spec/models/company_spec.rb
  spec/requests/internal_api/v1/projects/index_spec.rb
  spec/services/projects/search_service_spec.rb
Labels: PR: reviewed-approved

#949 Refactoring in ProjectMembersPresenter
  app/presenters/project_members_presenter.rb
Labels: PR: reviewed-approved

#971 Added fix for send invoice bug
  app/javascript/src/components/Invoices/List/MoreOptions.tsx
  app/javascript/src/components/Invoices/List/SendInvoice/index.tsx
Labels: PR: partially-approved

#967 Resolved Timesheet entry datepicker bug
  app/javascript/src/components/TimeTracking/AddEntry.tsx
  app/javascript/src/components/TimeTracking/index.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#972 route created
  app/javascript/src/components/App.tsx
  app/javascript/src/components/Main.tsx
  app/javascript/src/constants/index.tsx
  app/javascript/src/constants/miruApp.ts
Labels: PR: unreviewed

#973 log out error fixed
  app/javascript/src/components/Navbar/UserActions.tsx
Labels: PR: reviewed-approved

#962 Fix remove team member
  app/controllers/internal_api/v1/team_controller.rb
  app/controllers/internal_api/v1/workspaces_controller.rb
  app/models/company.rb
  app/models/employment.rb
  app/models/user.rb
  app/services/time_tracking_index_service.rb
  config/locales/en.yml
  spec/requests/internal_api/v1/team/destroy_spec.rb
Labels: PR: unreviewed

#976 Hover issue fix for invoice page
  app/javascript/src/components/Invoices/List/Header.tsx
  app/javascript/src/components/Invoices/List/MoreOptions.tsx
  app/javascript/src/components/Invoices/List/RecentlyUpdated/RecentlyUpdatedCard.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#974 client page alignment fixed
  app/javascript/src/common/AmountBox/index.tsx
  app/javascript/src/components/Clients/List/index.tsx
  tailwind.config.js
Labels: PR: reviewed-approved

#888 config for running cypress on production
  cypress/e2e/production/auth/login.spec.js
  cypress/e2e/production/auth/signup.spec.js
  cypress/fixtures/production/credentials.json
  cypress_production.config.ts
  package.json
Labels: PR: reviewed-approved

#969 common component used for client logo
  app/javascript/src/components/Clients/List/index.tsx
  app/javascript/src/components/Clients/Modals/ClientForm.tsx
  app/javascript/src/components/Reports/Header/index.tsx
Labels: PR: reviewed-approved

#977 Default route changed for owner
  app/controllers/root_controller.rb
  app/controllers/users/sessions_controller.rb
  app/javascript/src/components/Main.tsx
  app/views/root/index.html.erb
  spec/requests/root/index_spec.rb
Labels: PR: unreviewed

#979 ElasticSearch Prefix Prodcution
  config/initializers/searhkick.rb
Labels: PR: reviewed-approved

#975 Redevelop Organization settings page on React
  app/javascript/src/components/OrganizationSetup/CompanyDetailsForm/index.tsx
  app/javascript/src/components/OrganizationSetup/CompanyDetailsForm/interface.ts
  app/javascript/src/components/OrganizationSetup/CompanyDetailsForm/utils.ts
  app/javascript/src/components/OrganizationSetup/FinancialDetailsForm/index.tsx
  app/javascript/src/components/OrganizationSetup/FinancialDetailsForm/interface.ts
  app/javascript/src/components/OrganizationSetup/FinancialDetailsForm/utils.ts
  app/javascript/src/components/OrganizationSetup/Step.tsx
  app/javascript/src/components/OrganizationSetup/index.tsx
  app/javascript/src/components/OrganizationSetup/utils.ts
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/rc-steps.scss
  app/views/companies/new.html.erb
  package.json
  spec/requests/companies/new_spec.rb
  tailwind.config.js
Labels: PR: unreviewed

#982 Fixed invoice loading duration issue by removing unnecessary es calls
  app/models/invoice.rb
  app/services/invoices/index_service.rb
Labels: PR: partially-approved
